### ISSUE TITLE
Permission response

### ISSUE THREAD

**Issue by OpenDog** [actions-on-google/actions-on-google-nodejs#10]
I'm not sure if this is an issue (at least not here) but here it goes. I'm using the API.AI assistant, everything basic stuff works. Then I make a permission request. Google grants it, I see the JSON going back to API.AI (I'm testing with the Web Simulator), but nothing gets back to my webhook. I was wondering maybe I'm doing something wrong when asking for the permission. 

How to set this up with API.AI? How did you test it? Do I need an event (GOOGLE_ASSISTANT_PERMISSON?) on an intent, something similar to the welcome event mechanism?

**Comment by smishra2** [comment]
Hi @OpenDog, currently you can use a Fallback intent in API.AI to catch the permission response. The Fallback intent should include an incoming context equal to one output by the permission-request intent. In this response, use `isPermissionGranted()` to check if permission was granted or not. To see this implemented, check out the [Name Psychic](https://github.com/actions-on-google/apiai-name-psychic-nodejs) sample.

**Comment by OpenDog** [comment]
Thank you!
