### ISSUE TITLE
app.StandardIntents.MAIN returns v1 intent names

### ISSUE THREAD

**Issue by julianweise** [actions-on-google/actions-on-google-nodejs#102]
Hey guys,
following your [ActionsSDK](https://developers.google.com/actions/sdk/fulfillment) guide and making use of your npm package, I noticed that the standard intent identifier accessor `app.StandardIntents.XXXX` (e.g.: app.StandardIntents.MAIN) seem to return the old identifiers (`assistant.intent.action.MAIN` vs. `actions.intent.MAIN`). 
Changes of the migration from v1 to v2 are described [here](https://developers.google.com/actions/reference/v1/migration).

From my point of view, [assistant-app.js](https://github.com/actions-on-google/actions-on-google-nodejs/blob/master/assistant-app.js) has to be adapted.

**Comment by Canain** [comment]
Are you sure you are using the v2 API and put [`"fulfillmentApiVersion": 2`](https://github.com/actions-on-google/actionssdk-eliza-nodejs/blob/a44a1b0ef0026ce2b0e525ce38bebbf8540ce344/eliza.json#L41) in your action package? Make sure you disabled and reenabled testing for your app to refresh the fulfillment version.

In the client library, it will only give the old intents when it [detects version 1 is being used](https://github.com/actions-on-google/actions-on-google-nodejs/blob/be754b76139bce22aee80b6eef19b6d70f70486a/assistant-app.js#L232).

By default it will give the [v2 intent `actions.intent.MAIN`](https://github.com/actions-on-google/actions-on-google-nodejs/blob/be754b76139bce22aee80b6eef19b6d70f70486a/assistant-app.js#L2794).

**Comment by julianweise** [comment]
Ah alright, I see. Sorry, my bad. I missed the `"fulfillmentApiVersion": 2` in my actions.js.
Maybe it would be a good idea to automatically add it to the actions.js while executing `gactions init`.
