### ISSUE TITLE
v2 alpha - please make actionssdk proto file available

### ISSUE THREAD

**Issue by mikeleonard** [actions-on-google/actions-on-google-nodejs#107]
Hi

Please can someone from Google commit the actionssdk protocol buffers proto file to this repository. 

Specifically I mean the protobuf file that is use to generate this:

https://github.com/actions-on-google/actions-on-google-nodejs/blob/v2.0.0-alpha/src/service/actionssdk/api/v2.ts

This would make it easier for users of the actionssdk library to store a history of received and sent messages in binary protobuf format instead of json, and would allow the community to more easily build client libraries in other languages.

I personally would be happy with just a copy of the protobuf file. I don't think this repository needs to contain the canonical protobuf file and entire build chain to produce the v2.ts file - just the protobuf file copied next to that file would be a great help.

Thanks

**Comment by Canain** [comment]
Hey, thanks for the feedback!

I filed a request to do this internally with your use cases and comments.

I will let you know of any updates on this.

**Comment by mikeleonard** [comment]
Thanks a lot.

**Comment by mikeleonard** [comment]
Hi @Canain. Been thinking about this more. Can you please tell me - if you know or can find out - how (ie what tool) is used to autogenerate the typescript interface definitions for the actionssdk/dialogflow api from the proto file?

Basically: how do you generate this:
https://github.com/actions-on-google/actions-on-google-nodejs/blob/v2.0.0-alpha/src/service/dialogflow/api/v2.ts
from this:
https://github.com/dialogflow/dialogflow-nodejs-client-v2/blob/c3bca0fa8f1f3a8f2af0175d10caf581a9e4e035/protos/google/cloud/dialogflow/v2beta1/intent.proto

I've come across a couple of open source ways of doing this and want to know if internally you are using something I can use or something that's internal to google.

I could try to generate the .ts file myself from the above .proto file and see if things match - but I thought I'd try asking first as that's frankly much easier!

Thanks a lot

**Comment by Canain** [comment]
Hi, we used an internal tool to generate the interfaces.

I'm not sure of the best open source tool of doing this for TypeScript. Keep in mind using protobufs is very language dependent especially since this is a pure JSON api and does not use gRPC which has official libraries.

You can look at [protobuf.js's pbts for TypeScript section](https://github.com/dcodeIO/ProtoBuf.js/#pbts-for-typescript) which might be what you want.

We haven't used it before or are super familiar with it, but it looks like it generate some sort of class or interfaces which then you can take and clean up using a script and regex to get what you want.

**Comment by mikeleonard** [comment]
Thanks @Canain that's really helpful. Good to know you're using an internal too, saves me failing to replicate it with an open source tool. Request: open source the tool?!

It would still be great to have the actionssdk .proto file committed to the repo or made available somewhere else. Would save me from trying to work backwards from the typescript interfaces to recreate it. The dialogflow .proto is available so I'm sure there's no reason not to make the actionssdk proto file available. Thanks for making this request internally for me. I'll keep this issue open in the hope that you hear back. Thanks again for the help.

**Comment by lucaswadedavis** [comment]
Due to more than 6 months of inactivity, this issue is being closed. 

If you think the resolution is in error, please re-open the issue with fresh information.
