### ISSUE TITLE
Be more defensive with invalid payloads

### ISSUE THREAD

**Issue by dblock** [actions-on-google/actions-on-google-nodejs#11]
From https://github.com/actions-on-google/actions-on-google-nodejs/commit/6e44302f12f4e093c36122c725497cf1790ad44c

Is type required in the payloads? This broke some of my tests in an app upgrading from 1.0.5 to 1.0.6. Also if you send an app some garbage it's just going to respond with "Cannot read property 'type' of undefined" instead of "Action Error: Missing inputs from request body", so it feels like this needs to check for presence of conversation.type or produce a better error.

I am happy to PR either.

**Comment by smishra2** [comment]
Hi @dblock, sorry for the inconvenience. We've updated the library to handle this better.
