### ISSUE TITLE
V2 Alpha SSML util: text not escaped properly in TSX

### ISSUE THREAD

**Issue by mikeleonard** [actions-on-google/actions-on-google-nodejs#112]
Hi

If you use the ssml tagged litteral, things like " and > are properly escaped:
```javascript
const { ssml } = require('actions-on-google/util/ssml');
const equation = '"1 + 1 > 1"';
const ssmlString = ssml`<speak>${equation}</speak>`;
console.log(ssmlString);
// "<speak>&quot;1 + 1 &gt; 1&quot;</speak>"
```

However I was expecting the escaping to work in TSX as well but it doesn't: 
```javascript
const { ssml } = require('actions-on-google/util/ssml');
const equation = '"1 + 1 > 1"';
const ssmlString = <speak>{equation}</speak>;
console.log(ssmlString);

// Expected: "<speak>&quot;1 + 1 &gt; 1&quot;</speak>"
// Got this:  <speak>"1 + 1 > 1"</speak>
```

Either this is a bug or I'm doing something wrong.

## Attempted fix
I tried adding `children = children.map(sanitize);` in the ssml.create function:

```javascript
const create = (tag: string, props: Props | null, ...children: string[]) => {
  const expanded = props ? expand(props) : "";
  children = children.map(sanitize);

  return children.length
    ? `<${tag}${expanded.length ? ` ${expanded}` : expanded}>${children.join(
        ""
      )}</${tag}>`
    : `<${tag}${expanded.length ? ` ${expanded}` : expanded}/>`;
};
```

But then realised this approach won't work: when a child is an SSML string that has come from ssml.create(), this approach will escape that entire string which you definitely don't want as you get things that look like `<speak>Hello<break time=&quot;1s&quot; strength=&quot;strong&quot;/&gt;<say-as interpret-as=&quot;characters&quot;&gt;Hello`

To my mind, you would need ssml.create() to know which children are raw text strings and which are already ssml strings output by a nested ssml.create() - so that you run sanitize on the raw text strings.

**Comment by Canain** [comment]
Thanks for the report!

Yeah, the jsx utility is very experimental, and we were experimenting with just rendering as strings so more advanced string based modifications can be used.

It looks like from this that the approach doesn't work in order to allow sanitization of children.

The solution might be just have JSX.Element be just an object rather than a string that will contain the element information. Then either have a render function, have the object decomposable into a SimpleResponse, or make it be a custom object and make it a plugin to allow you to use it directly in `conv.ask`.

We'll explore the best solution but thanks so much for investigating and opening this issue to us!

**Comment by mikeleonard** [comment]
No problem, happy to help. 

I came to similar conclusions yesterday while playing around with this: I made create() return a JSX.Element and then wrote a simple renderToSSMLString() function.

One huge benefit of this approach I somewhat got working yesterday: you can write custom components like in React! To do that you need to follow React JSX conventions... lower-case first letter for ssml tags (ie intrinsic elements in the JSX namespace), and upper-case for custom components that are implemented as functions (stateless or stateful, although I'm not sure there's a usecase for stateful but who knows).

Regarding your comment on the possible approaching being 'render function vs object decomposable into a SimpleResponse versus custom object as a plugin'... I'd worry that decomposing into SimpleResponse or writing it as a plugin sounds like it's quite tied to the rest of the framework. To my mind, having a render() would let users use this util elsewhere, and perhaps conv.ask could call render if it's passed a JSX.Element.

Another quick thought: 
Typescript 2.8 ([release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html)) lets you locally instead of globally scope the JSX namespace. Might be worth looking at.

**Comment by mikeleonard** [comment]
Here's a copy-paste of my bookmarks from yesterday on this in case they're helpful:

https://reactjs.org/docs/implementation-notes.html
https://reactjs.org/docs/jsx-in-depth.html
http://www.typescriptlang.org/docs/handbook/jsx.html
https://github.com/cameronhunter/alexa/blob/master/packages/ssml-jsx/src/renderToString.js
https://github.com/nickclaw/alexa-ssml/blob/master/src/renderToString.js
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2219
http://www.talkingtocomputers.com/actions-on-google-sdk-alpha-preview-ssml

**Comment by Canain** [comment]
Closing this for now since the general availability library no longer has the ssml utility.

We are looking to release more utility/plugin material for the library and developers but that probably will be separate from this repo.
