### ISSUE TITLE
How to use the new v2 library ?

### ISSUE THREAD

**Issue by sonlexqt** [actions-on-google/actions-on-google-nodejs#118]
At first, I'm sorry if the question seems silly.
I'm getting used to Actions on Google + DialogFlow in the last couple of days. I found out this node package (v2) yesterday and I'm planning to use it for my DialogFlow webhook. One problem for me is the package just recently get updated to v2 and it seems like there's no tutorial / instructions on how to use the new v2 library.
Like, from the README file I can see:
```
const { dialogflow } = require('actions-on-google')
const app = dialogflow()
```
But what to do next with the `app` variable ? Given I'm using express.js to build my webhook.

**Comment by silvolu** [comment]
We have a guide on how to build fulfillment for dialogflow [here](https://developers.google.com/actions/dialogflow/fulfillment), and you can find a bunch of examples in [our github org](https://github.com/actions-on-google/): all the repos prefixed with "dialogflow" show usage of dialogflow.

Hope that helps!

**Comment by Iridio** [comment]
I think the OP would like an example with express:

I do the following inside the router class (in typescript)

```
import * as express from 'express'
import { dialogflow } from 'actions-on-google'

const app = dialogflow({ debug: true })

const router = express.Router()
router.use(app)

app.intent('The intent name not the action name!!!!', (conv, params) => {
    //Do something 
    conv.ask("my question")
or
    conv.close("my answer")
})
export = router
```

**Comment by sonlexqt** [comment]
Thanks @Iridio that's exactly what I want ! I'm closing the issue now.

**Comment by Canain** [comment]
We also have a small snippet of a very basic self hosted express server in our [v1 migration guide](https://developers.google.com/actions/reference/nodejs/lib-v1-migration#new_frameworks_system).

Here's the snippet in case it's helpful too:
```javascript
const express = require('express');
const bodyParser = require('body-parser');
const { dialogflow } = require('actions-on-google');

const app = dialogflow();

// fulfillment code here

express().use(bodyParser.json(), app).listen(3000);
```

**Comment by stiller-leser** [comment]
This doesn't do the trick for me. I simply get the answer that my dialogflow app isn't answering. Below is an excerpt of code that I am using:

```javascript
const { dialogflow, List } = require('actions-on-google');
import * as r from 'request-promise-native'
import * as express from 'express'
const bodyParser = require('body-parser');

process.env.DEBUG = 'dialogflow:debug'; // enables lib debugging statements

const app = dialogflow({ debug: true });

app.intent('welcome_intent', (conv) => {
  sayWelcome(conv)
});

express().use(bodyParser.json(), app).listen(8080);

```

Is there any way to determine which webhook is trying to be reached? The webhook url I am using looks similar to `https://my-app-ok-google.some-domain.com`. I only get the message that an empty response was received. If I open the url in my browser, I see `error : "Cannot read property 'payload' of undefined"`

Any debugging hint is appreciated.
