### ISSUE TITLE
How to send carousel with > 10 items ?

### ISSUE THREAD

**Issue by sonlexqt** [actions-on-google/actions-on-google-nodejs#121]
Hi, I'm using version 2 of the library. I want to send a [carousel](https://developers.google.com/actions/assistant/responses#carousel) with more than 10 (the maximum allowed) items. How can I do that ? I can think of two ways:
1. Send many carousel at once (I'm not sure this is possible). I tried `conv.ask(array of carousels)` but it didn't work.
2. Paginate the carousel items, which means sending the first carousel with 10 items, then show a 'View more' button so that user can fetch the next items. In this case, I don't know how to send the 'View more' button.
Thanks for your help !

**Comment by Edo78** [comment]
The "view more" button should be a suggestion chip that must trigger an intent for another carousel

**Comment by sonlexqt** [comment]
Thanks @Edo78, I tried using Suggestion Chip but don't know how to use a Suggestion Chip to trigger an intent for another carousel.
**Summary of what I want to do:** let's say I have a list of 25 items.
* When user choose 'Show carousel', the bot send the first 10 items and a 'View more' button.
* When user click on that 'View more' button, the bot send the next 10 items, and another 'View more' button.
* When user click on this 'View more' button, the bot send the last 5 items.

**Comment by Edo78** [comment]
You have to create an intent triggered by the same text you put in the suggestion chip.
In your backend you have to initialize a counter to paginate the results for the carousel and every time the suggestion chip is selected the fullfilment of the triggered intent should have to increment the counter and then reply with a carousel with the next set of results.
