### ISSUE TITLE
How to send list ?

### ISSUE THREAD

**Issue by kwizfreak** [actions-on-google/actions-on-google-nodejs#122]
Hello, 

I want to know how to send list ? 

I can send card but i don't see example for list 

i get an error **"UnhandledPromiseRejectionWarning: ReferenceError: List is not defined"** with : 

      agent.ask(new List({
    title: 'List Title',
    items: {
      // Add the first item to the list
      [SELECTION_KEY_ONE]: {
        synonyms: [
          'synonym of title 1',
          'synonym of title 2',
          'synonym of title 3',
        ],
        title: 'Title of First List Item',
        description: 'This is a description of a list item.'
      },
      // Add the second item to the list
      [SELECTION_KEY_GOOGLE_HOME]: {
        synonyms: [
          'Google Home Assistant',
          'Assistant on the Google Home',
      ],
        title: 'Google Home',
        description: 'Google Home is a voice-activated speaker powered by ' +
          'the Google Assistant.'
      },
      // Add the third item to the list
      [SELECTION_KEY_GOOGLE_PIXEL]: {
        synonyms: [
          'Google Pixel XL',
          'Pixel',
          'Pixel XL',
        ],
        title: 'Google Pixel',
        description: 'Pixel. Phone by Google.'
      },
      // Add the last item to the list
      [SELECTION_KEY_GOOGLE_ALLO]: {
        title: 'Google Allo',
        synonyms: [
          'Allo',
        ],
        description: 'Introducing Google Allo, a smart messaging app that ' +
          'helps you say more and do more.'
      },
    },
  }));

Thanks :)

**Comment by kwizfreak** [comment]
Yes but i have an error : 

(node:9339) UnhandledPromiseRejectionWarning: Error: unknown response type
    at WebhookClient.add (/var/www/rjweb.xyz/dialogflow/expressions_webhook/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:217:13)
    at request.get.then.result (/var/www/rjweb.xyz/dialogflow/expressions_webhook/me.js:87:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
(node:9339) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

This is my code : 


"use strict";

const express = require("express");
const bodyParser = require("body-parser");
const { actionssdk } = require('actions-on-google');
const {WebhookClient} = require('dialogflow-fulfillment');

const restService = express();
const request = require('request-promise-native');

const {
  dialogflow,
  BasicCard,
  BrowseCarousel,
  BrowseCarouselItem,
  Button,
  Carousel,
  Image,
  LinkOutSuggestion,
  List,
  MediaObject,
  Suggestions,
  SimpleResponse,
 } = require('actions-on-google');

restService.use(
  bodyParser.urlencoded({
    extended: true
  })
);

restService.use(bodyParser.json());

restService.post("/echo", function(req, res) {
  //console.log('nouvelle requete');
  //console.log(req.body);
	const app = actionssdk();
	const agent = new WebhookClient({ request: req, response: res });
	const WELCOME_INTENT = 'input.welcome';

	let intentMap = new Map();
  intentMap.set('Default Welcome Intent', welcome);
  intentMap.set('Default Fallback Intent', fallback);
  intentMap.set('Echo', echo);
  // intentMap.set('<INTENT_NAME_HERE>', yourFunctionHandler);
  // intentMap.set('<INTENT_NAME_HERE>', googleAssistantHandler);
  agent.handleRequest(intentMap);

});




function echo (agent) {



console.log('je fais un log ici');
console.log(agent.query);
var speech = agent.query;

var options = {
    uri: 'https://www.rjweb.xyz/restbot/public/expression/' + speech,
    json: true
};


return request.get(options)
      .then( result => {
        console.log(result);
        if (result.length == 1) {


            console.log('1 resultat');
              //agent.add('Super, J\'ai trouvé un résultat pour cette expression : ');
              agent.add('Voici la signification de l\'expression '+result[0].title+' : \n \n '+result[0].signification);
              if (result[0].exemple) {
                        agent.add('Voici un exemple :');
                        agent.add(result[0].exemple);

                      }

        } else if (result.length > 1) {
          console.log(' multiple resultat');
            agent.add('multiple');

            agent.add(new List({
             items: {
                ['SELECTION_KEY_ONE']: {
                  title: 'Number one',
                  synonyms: ['synonym of KEY_ONE 1', 'synonym of KEY_ONE 2'],
                },
                ['SELECTION_KEY_TWO']: {
                  title: 'Number two',
                  synonyms: ['synonym of KEY_TWO 1', 'synonym of KEY_TWO 2'],
                }
              }
            }))

            agent.add(new Suggestion(`Quick Reply`));
            agent.add(new Suggestion(`Suggestion`));
            agent.setContext({ name: 'weather', lifespan: 2, parameters: { city: 'Rome' }});

        }
        else {
          console.log('aucun resultat');
          //message.addReply({ type: 'text', content: 'Désolé mais je n\'ai trouvé aucun résultat, tu peux réessayer avec un autre mot, phrase ou expression.' });
          agent.add(`Désolé mais je n\'ai trouvé aucun résultat, tu peux réessayer avec un autre mot, phrase ou expression.`);
        }
        return Promise.resolve( agent );
      });

console.log('hey')

}

function welcome (agent) {

agent.add(`Bonjour ou Welcome agent`);
agent.add(new Card({
title: `Title: this is a card title`,
imageUrl: 'https://dialogflow.com/images/api_home_laptop.svg',
text: `This is the body text of a card.  You can even use line\n  breaks and emoji! 💁`,
buttonText: 'This is a button',
buttonUrl: 'https://docs.dialogflow.com/'
})
);
agent.add(new Suggestion(`Quick Reply`));
agent.add(new Suggestion(`Suggestion`));

}

function fallback (agent) {
agent.add(`I didn't understand`);
agent.add(`I'm sorry, can you try again?`);
}

restService.listen(process.env.PORT || 5001, function() {
  console.log("Server up and listening");
});

**Comment by Fleker** [comment]
Which version of the Actions on Google library are you using? It looks like you're using an odd mix of Dialogflow's webhook fulfillment and the AoG client library v1 and v2.

**Comment by kwizfreak** [comment]
i don't know :( is the last of each

**Comment by Fleker** [comment]
I recommend you start out by running [one of our samples](https://github.com/actions-on-google) in order to have a better understanding of how the Actions on Google library works. Then you can use that as a starting point for adding you own intents.

**Comment by kwizfreak** [comment]
Thanks, but i can use only firebase with this script and i want to use express js 

**restService.post("/echo", function(req, res) {**
  //console.log('nouvelle requete');
  //console.log(req.body);
	const app = actionssdk();
	**const agent = new WebhookClient({ request: req, response: res });**

but i can't with 

**const app = dialogflow({debug: true});**

app.middleware((conv) => {
  conv.hasScreen =
    conv.surface.capabilities.has('actions.capability.SCREEN_OUTPUT');
  conv.hasAudioPlayback =
    conv.surface.capabilities.has('actions.capability.AUDIO_OUTPUT');
});

**Comment by Fleker** [comment]
You can [very easily use Express](https://developers.google.com/actions/reference/nodejs/lib-v1-migration) with the Actions on Google library.

```javascript
// v2
const express = require('express');
const bodyParser = require('body-parser');
const { dialogflow } = require('actions-on-google');

const app = dialogflow();

// This is where you put your code

express().use(bodyParser.json(), app).listen(3000);
```

**Comment by bhamde** [comment]
But how to use WebhookClient with Actions on Google v2? It is good to have the option to use the function from different sources

**Comment by Canain** [comment]
Please take a look at the [samples for the Dialogflow fulfillment library](https://github.com/dialogflow/dialogflow-fulfillment-nodejs/blob/d8396faab7ebaed4b4aeb7b39dd45f19f8e5c9a3/samples/actions-on-google/functions/index.js#L37) which is where `WebhookClient` is from.

Feel free to open an issue on Stackoverflow if you have any questions or open a [issue on there](https://github.com/dialogflow/dialogflow-fulfillment-nodejs/issues) if you think there's a problem with the Dialogflow fulfillment library.
