### ISSUE TITLE
V2 Verification Error With Authorization Header

### ISSUE THREAD

**Issue by scottwestover** [actions-on-google/actions-on-google-nodejs#124]
Hi there,

I am trying to verify requests through Dialogflow, but I keep getting the following error:
```
{
    "error": "A verification header key was not found"
}
```

For my Google Action, I am using v2 of the API, v2.0.1 of this sdk, and I am trying to run this function on Lambda.

When I log the `conv.headers` object, I can see the `Authorization` header coming through the request, but I still get the error above. I believe the issue is tied to this line here: https://github.com/actions-on-google/actions-on-google-nodejs/blob/master/src/service/dialogflow/dialogflow.ts#L340

The check is changing the header value I pass to lower case, however the actual header value that is stored in the `conv.headers` object is not, so it is not finding the match. If I remove the `.toLowerCase()`, then the request goes through fine.

Here is the code I am running:
```
'use strict';

const { dialogflow } = require('actions-on-google');

const app = dialogflow({
  verification: {
    Authorization: 'Basic QWxsb3k6YXBwbGU='
  }
});

app.intent('Default Fallback Intent', conv => {
  console.log(conv.headers);
  conv.ask('default fallback intent');
});

app.intent('Default Welcome Intent', conv => {
  console.log(conv.headers);
  conv.ask('hi there');
});

module.exports.handler = app;
```

Also, here is the action I setup in Dialogflow:
[Test2.zip](https://github.com/actions-on-google/actions-on-google-nodejs/files/1933384/Test2.zip)

Is there anything else I need to pass `verification` object to get this request to work?

**Comment by Canain** [comment]
Thanks for reporting this!

Yeah, it looks like a bug. The reason why it does `.toLowerCase()` is because HTTP header keys are case insensitive so it expects the headers map keys to already be `.toLowerCase()` in order to match correctly which happens in Firebase Functions' express interface.

The fix would need to be either in the lambda framework handler code to convert to lowercase or in the verification code to convert the keys there.

For now, you can write your own custom framework handler for lambda and use that:
```javascript
'use strict';

const { dialogflow } = require('actions-on-google');

class CustomLambda {
  handle(standard) {
    return async (event, context, callback) => {
      const headers = {}
      for (const key in event.headers) {
        headers[key.toLowerCase()] = event.headers[key]
      }
      const result = await standard(JSON.parse(event.body), headers).catch(e => {
        error(e.stack || e)
        callback(e)
      })
      if (!result) {
        return
      }
      const { status, body } = result
      callback(null, {
        statusCode: status,
        body: JSON.stringify(body),
      })
    }
  }

  isContext(second) {
    return typeof second.succeed === 'function'
  }

  isCallback(third) {
    return typeof third === 'function'
  }

  check(first, second, third) {
    return this.isContext(second) && this.isCallback(third)
  }
}

const app = dialogflow({
  verification: {
    Authorization: 'Basic QWxsb3k6YXBwbGU='
  }
});

app.frameworks.lambda = new CustomLambda()

app.intent('Default Fallback Intent', conv => {
  console.log(conv.headers);
  conv.ask('default fallback intent');
});

app.intent('Default Welcome Intent', conv => {
  console.log(conv.headers);
  conv.ask('hi there');
});

module.exports.handler = app;
```

Let me know if this works or if you have any issues.

**Comment by scottwestover** [comment]
@Canain Thanks for the quick response, detailed explanation, and quick solution. I implemented the the custom framework handler, and it worked perfectly.

Thanks again!
