### ISSUE TITLE
Also like how to make use of app.data to store some data until end of conversation. Before we used to do app.data.<variablename> = <value> so that on next request we can access the value of it and modify it and pass it again

### ISSUE THREAD

**Issue by Mrinnaal** [actions-on-google/actions-on-google-nodejs#129]

**Comment by Fleker** [comment]
Instead of using `app.data`, you can use `conv.data`.

**Comment by Mrinnaal** [comment]
Thanks a ton fleker :) i should have checked the updated samples! Without checking that I just posted the query. Sorry bro. I would love to know one more thing. Is it possible to still use the actionMap?

**Comment by Fleker** [comment]
The idea of the action map is not available in v2. Instead, the recommendation is to use map your intents to functions as noted in [the migration guide](https://developers.google.com/actions/reference/nodejs/lib-v1-migration).

**Comment by Mrinnaal** [comment]
@Fleker  hey fleker! Is there any sample provided for sign-in provided intent? I tried integrating with outlook and i was successfully getting accessToken for further operations. But everytime i try on actions on google simulator, i need to go to debug console, get the URL, authenticate and then again speak to the app! If there is any sample like outlook mail fetching which is like easy way, please share it! (I made default welcome intent as sign-in intent)

**Comment by Fleker** [comment]
I do not believe there is a sample for sign-in in this [GitHub org](https://github.com/actions-on-google/).
