### ISSUE TITLE
Dialogflow IntentHandler not found for intent: myIntent

### ISSUE THREAD

**Issue by theunreal** [actions-on-google/actions-on-google-nodejs#130]
Since I upgraded my Dialogflow to use v2 API, I get the following error:

    `Dialogflow IntentHandler not found for intent: myIntent`

For some reasons, my intent is no longer recognized although the action name is identical - myIntent.

This is how I'm using my NodeJS (express V4) app to return a response:

```
dialogflowApp.intent('myIntent', (conv, {version}) => {
        conv.close('test');
    });

```

What could have gone wrong?

**Comment by sriprabha** [comment]
I am seeing a similar issue with Action SDK `Actions SDK IntentHandler not found for intent` after upgrading to v2 using the steps here https://developers.google.com/actions/reference/nodejs/lib-v1-migration

**Comment by sriprabha** [comment]
Worked for me based on the code snippet here https://github.com/actions-on-google/actions-on-google-nodejs/issues/118#issuecomment-382662904
