### ISSUE TITLE
Carousel only displays items with images when some have images

### ISSUE THREAD

**Issue by teddis** [actions-on-google/actions-on-google-nodejs#131]
When constructing a carousel with some items with images and some without, GA will only display those with images specified. The only workaround if images are to be displayed at all is to supply every item with an image even if not available.

**Comment by Canain** [comment]
This is a limitation by the platform as I don't think there's a way to display image items and non image items consistently without having placeholder images which is what you basically have done.

On the simulator, does it throw any validation errors when this happens?

**Comment by Canain** [comment]
Closing since there hasn't been more discussion.
