### ISSUE TITLE
Migrate code V1 to V2

### ISSUE THREAD

**Issue by feeh27** [actions-on-google/actions-on-google-nodejs#136]
Hello,

I'm not able to migrate this code to V2:

```node.js
const functions = require('firebase-functions');

const admin = require('firebase-admin');
admin.initializeApp();

const DialogflowApp = require('actions-on-google').DialogflowApp;

exports.receiveAssistantRequests = functions.https.onRequest((request, response) => {

    const app = new DialogflowApp({request: request, response: response});

    function handlerRequest(app) {

        const device = app.getArgument('devices');
        const status = app.getArgument('status');

        return admin.database().ref(`/automation/${device}/value`).set(status)
            .then(snapshot => {
                app.ask(`Ok, switching ${device} ${status}. Do you want to control anything else?`);
            });

    }
    app.handleRequest(handlerRequest);
});
```

At best I came up with this code:

```node.js
const functions = require('firebase-functions');

const admin = require('firebase-admin');
admin.initializeApp();

const { dialogflow } = require('actions-on-google');
const app = dialogflow();

function handlerRequest(app) {
	const device = app.getArgument('devices');
	const status = app.getArgument('status');

	return admin.database().ref(`/iotday/${device}/value`).set(status)
		.then(snapshot => {
			app.ask(`Ok, switching ${device} ${status}. Do you want to control anything else?`);
		});
}

app.handleRequest(handlerRequest);

exports.receiveAssistantRequests = functions.https.onRequest(app);
```

Can someone help me?

**Comment by Canain** [comment]
There's no handle request anymore. If you want a generic fallback to work with any intent, then you need to use `app.fallback`. I'm assuming you are using parameters from Dialogflow, so then you need to extract that accordingly.

```javascript
const functions = require('firebase-functions');

const admin = require('firebase-admin');
admin.initializeApp();

const { dialogflow } = require('actions-on-google');
const app = dialogflow();

app.fallback((conv, { devices, status }) => {
	return admin.database().ref(`/iotday/${devices}/value`).set(status)
		.then(snapshot => {
			app.ask(`Ok, switching ${devices} ${status}. Do you want to control anything else?`);
		});
});

exports.receiveAssistantRequests = functions.https.onRequest(app);
```

**Comment by trungnt262** [comment]
when I update " Update available 5.0.1 → 6.1.1       │
   │   Run npm i -g firebase-tools to update"
and I have an error here:
TypeError: dialogflow is not a function
    at Object.<anonymous> (C:\Users\Pisces\functions\index.js:7:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at C:\Users\Pisces\AppData\Roaming\npm\node_modules\firebase-tools\lib\triggerParser.js:15:15
    at Object.<anonymous> (C:\Users\Pisces\AppData\Roaming\npm\node_modules\firebase-tools\lib\triggerParser.js:53:3)
-------------------------------------
How can I fix? thank you all!

**Comment by prateekdhillon** [comment]
> There's no `app.handleRequest` anymore. If you want a generic fallback to work with any intent, then you need to use `app.fallback`. I'm assuming you are using parameters from Dialogflow, so then you need to extract that accordingly.
> 
> ```js
> const functions = require('firebase-functions');
> 
> const admin = require('firebase-admin');
> admin.initializeApp();
> 
> const { dialogflow } = require('actions-on-google');
> const app = dialogflow();
> 
> app.fallback((conv, { devices, status }) => {
> 	return admin.database().ref(`/iotday/${devices}/value`).set(status)
> 		.then(snapshot => {
> 			conv.ask(`Ok, switching ${devices} ${status}. Do you want to control anything else?`);
> 		});
> });
> 
> exports.receiveAssistantRequests = functions.https.onRequest(app);
> it says then() should return a value or throw

**Comment by prateekdhillon** [comment]
> There's no `app.handleRequest` anymore. If you want a generic fallback to work with any intent, then you need to use `app.fallback`. I'm assuming you are using parameters from Dialogflow, so then you need to extract that accordingly.
> 
> ```js
> const functions = require('firebase-functions');
> 
> const admin = require('firebase-admin');
> admin.initializeApp();
> 
> const { dialogflow } = require('actions-on-google');
> const app = dialogflow();
> 
> app.fallback((conv, { devices, status }) => {
> 	return admin.database().ref(`/iotday/${devices}/value`).set(status)
> 		.then(snapshot => {
> 			conv.ask(`Ok, switching ${devices} ${status}. Do you want to control anything else?`);
> 		});
> });
> 
> exports.receiveAssistantRequests = functions.https.onRequest(app);
> ```



> this say error -Each then() should return a value or throw promise/always-return
> 
> > There's no `app.handleRequest` anymore. If you want a generic fallback to work with any intent, then you need to use `app.fallback`. I'm assuming you are using parameters from Dialogflow, so then you need to extract that accordingly.
> > ```js
> > const functions = require('firebase-functions');
> > 
> > const admin = require('firebase-admin');
> > admin.initializeApp();
> > 
> > const { dialogflow } = require('actions-on-google');
> > const app = dialogflow();
> > 
> > app.fallback((conv, { devices, status }) => {
> > 	return admin.database().ref(`/iotday/${devices}/value`).set(status)
> > 		.then(snapshot => {
> > 			conv.ask(`Ok, switching ${devices} ${status}. Do you want to control anything else?`);
> > 		});
> > });
> > 
> > exports.receiveAssistantRequests = functions.https.onRequest(app);
> > ```
i

i finally reached this code that is working


const functions = require('firebase-functions');

const admin = require('firebase-admin');
admin.initializeApp();

const { dialogflow } = require('actions-on-google');
const app = dialogflow();

app.fallback((conv, { devices, status }) => {
	return admin.database().ref(`/automation/${devices}/value`).set(status)
		.then(snapshot => {
			return conv.ask(`Ok, switching ${devices} ${status}. Do you want to control anything else?`);
		});
});

exports.receiveAssistantRequests = functions.https.onRequest(app);
