### ISSUE TITLE
How to use action for fulfillment?

### ISSUE THREAD

**Issue by jhohlfeld-otto** [actions-on-google/actions-on-google-nodejs#137]
Hey,

I'd like to know your intentions for the current and future Node-API. We're using `actions-on-google/dialogflow@2.0.1` to fulfill an action built with DialogFlow. We're mostly using _intent names_ to map some of our user interactions to a lambda function.

At one point though, we thought, _actions_ would be a better way to hand down fulfillment from DialogFlow. The idea behind this being: _intent names_ are tailored relatively closely towards user interaction flow, whereas _actions_ could be more flexibly attached to intents as entry points to our API as needed. intent names would be able to change over time, whereas actions could be hold static.

With the version 1 API, we did manage our intent handling with our own library and thus could very easily detect _actions_. We even started to refactor our code to solely use _actions_ instead of _intents_ in the future.

Now with version 2 of the Node-API, _actions_ seem to get pushed aside as _intent_/handler mapping is done by the dialogflow/app singleton.

Can you give a perspective on how plans are regarding supporting _actions_ to be handled by the app-singleton in the future and whether actions are at all intended to play a role in the Node-API? If they should play a major role, how would this role look like?

cheers
Jakob

**Comment by lucaswadedavis** [comment]
Regarding the future: no comment.

But regarding the current implementation of the node client library: yeah it's pretty intent focused. Your observations are astute. Best practice right now is to use the **app.intent()** method to do your mapping, rather than using actions like in v1 of the client library.

Sorry I can't be more revealing. Hope this helps.

**Comment by jhohlfeld-otto** [comment]
Hey @lucaswadedavis, thanks, at least now we know a little better. Astute, really? Thanks a lot ☺️
