### ISSUE TITLE
Add optional parameter 'app' to middleware.

### ISSUE THREAD

**Issue by jhohlfeld-otto** [actions-on-google/actions-on-google-nodejs#138]
I would like to propose an additional parameter being introduced to middlewares:

_src/service/dialogflow/dialogflow.ts:384_

```typescript
    for (const middleware of this._middlewares) {
      conv = (middleware(conv, this) as DialogflowConversation<TConvData, TUserStorage, TContexts> | void)
        || conv
    }
```

The new parameter is `this` (referencing `app`) and will give middleware developers more power over their plugins/middlewares implementation, since it grants access to the `app` context from within the middleware.

---

**Example:**

_bootstrap.js_
```javascript
// myPlugin adds changes to intent handlers
const app.use(myPlugin);

// myMiddleware makes conv recognize changes coming from myPlugin
app.middleware(myMiddleware)

// now we can use additional ways to handle request (i.e. via actions rather than intents)
app.action('my-action', actionHandler)
```

_my-plugin.js_
```javascript
// add additional functionality to register actions handlers
module.exports = (app) => Object.assign(app, {
  _handlers: Object.assign(app._handlers, {
    actions: {}
  }),
  action: (action, handler) => (app._handlers.actions[action] = handler)
})
```

_my-middleware.js_
```javascript
module.exports = (conv, app) => {
  let { intent, action } = conv
  if (action in app._handlers.actions) {
    intent = action
  }
  return Object.assign(conv, { intent })
}
```

**Comment by Canain** [comment]
The original design of plugins and middlewares was intended to use plugins as the way to export modifications and have middlewares as a helper for plugins to modify the `Conversation` instance.

So if you need the app instance for a middleware, you should use an plugin instead:
```javascript
// create a plugin
module.exports = app => {
  app.middleware(conv => {
    // use app here
    return Object.assign(conv, { /* extra functionality here */})
  })
}
```

Then any importing of functionality are always just `app.use(plugin)`.

I'm worried that if we add `app` as a parameter to middlewares too then there will be possibly two ways to distribute functionality so developers would have to remember to use either `app.use` or `app.middleware`.

For internal usage of middleware, there should be only one `app` instance so you shouldn't need an extra parameter for `app` as it would be the same Object every time. Maybe you can pass it through some other way or just create a plugin for internal use.

**Comment by jhohlfeld-otto** [comment]
Thanks @Canain , I totally overlooked this option. Closing issue for my part.
