### ISSUE TITLE
Async operation support?

### ISSUE THREAD

**Issue by dblock** [actions-on-google/actions-on-google-nodejs#14]
I couldn't find anything about async operation support. Can this work? 

Try to use https://github.com/manekinekko/google-actions-starter and ideally would like to return a Promise from an intent handler.

**Comment by smishra2** [comment]
When calling handleRequest, you can pass in a [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map), where the key is the "action" from an API.AI intent or the intent name from your Action Package, and the value is a function which can return a Promise.

**Comment by dblock** [comment]
Perfect, thanks.
