### ISSUE TITLE
List construction with ActionsSDK 2.0

### ISSUE THREAD

**Issue by sriprabha** [actions-on-google/actions-on-google-nodejs#142]
I am trying to construct a list response type using the snippet of code posted on the website as a reference - https://developers.google.com/actions/assistant/responses#list.
There seems to be a mismatch between the node JS example and the JSON example for `Image`. Is the expected key in the Image() supposed to be `alt` or `accessibilityText` ? 

JSON - 
<img width="790" alt="screen shot 2018-05-02 at 6 02 32 pm" src="https://user-images.githubusercontent.com/5651564/39556157-16a1ef56-4e33-11e8-8882-78a78c15d66a.png">

Node js SDK - 
<img width="802" alt="screen shot 2018-05-02 at 6 02 10 pm" src="https://user-images.githubusercontent.com/5651564/39556158-16badc5a-4e33-11e8-9050-94700fa1b8ff.png">

SDK version - actions-on-google@2.0.1

**Comment by Canain** [comment]
Hi, the `Image` class here is a wrapper for the raw image JSON.

The wrappers have a separate API and sometimes simplify naming to be easier for development purposes but still result in the underlying JSON to be the same as the raw API.

For the complete list of options for the `Image` wrapper, you can check the reference docs for the library for [`ImageOptions`](https://actions-on-google.github.io/actions-on-google-nodejs/interfaces/conversation_response.imageoptions.html).

Any time you see `new Class({` besides transactions related APIs, it's probably a wrapper and you can search for the corresponding wrapper options like `ClassOptions` in the [reference docs](https://actions-on-google.github.io/actions-on-google-nodejs/index.html).

**Comment by sriprabha** [comment]
Thanks, When I use the key `alt` instead of `accessibilityText` when using `Image`  , I get the following error - 
```API Version 2: Failed to parse JSON response string with 'INVALID_ARGUMENT' error: "(list_select.items[2].image) alt: Cannot find field.".``` 
Changing it to `accessibilityText` seems to solve the problem. 
I think it was because I was not invoking `new Image()`, instead constructing the JSON directly. Switching to `new Image` has resolved the issue
