### ISSUE TITLE
[Question] Updated docs to verify incoming requests

### ISSUE THREAD

**Issue by sriprabha** [actions-on-google/actions-on-google-nodejs#144]
The docs to verify incoming requests does not look updated - https://developers.google.com/actions/reference/rest/verify-requests. How does request validation work in the v2 SDK?

<img width="875" alt="screen shot 2018-05-07 at 9 11 17 am" src="https://user-images.githubusercontent.com/5651564/39712089-a19967d2-51d6-11e8-9a69-0809cd6cf6a4.png">

**Comment by sriprabha** [comment]
@smishra2 Can you please take a look at this? Thanks

**Comment by Canain** [comment]
In v2 for verification, you pass in a option to the `dialogflow` or `actionssdk` function called `verification` either [`DialogflowOptions.verification`](https://actions-on-google.github.io/actions-on-google-nodejs/interfaces/dialogflow.dialogflowoptions.html#verification) or [`ActionsSdkOptions.verification`](https://actions-on-google.github.io/actions-on-google-nodejs/interfaces/actionssdk.actionssdkoptions.html#verification).

Using that, you can provide a header to check for Dialogflow or a project id to verify for Actions SDK.

# Dialogflow
```javascript
const app = dialogflow({
  verification: {
    HEADER_KEY: HEADER_VALUE
  },
})
// by default will return 403 status code

// customize verification errors
const app = dialogflow({
  verification: {
    error: 'some string',
    status: 123,
    headers: {
      HEADER_KEY: HEADER_VALUE
    },
  }
})
```

# Actions SDK
```javascript
const app = actionssdk({
  verification: PROJECT_ID,
})
// by default will return 403 status code

// customize verification errors
const app = actionssdk({
  verification: {
    error: 'some string',
    status: 123,
    project: PROJECT_ID,
  }
})
```

**Comment by Canain** [comment]
Docs should be updated now. We will look to add it to the migration guide too.
