### ISSUE TITLE
Programmatically building a list

### ISSUE THREAD

**Issue by mmenti** [actions-on-google/actions-on-google-nodejs#145]
I'm migrating from v1 to v2, and can't for the life of me figure out how to programmatically/dynamically build a list.
In other words, I'm looking to migrate the app.buildList and list.addItems functionality of v1 - below is my example code that used to work.
Very grateful for any help or pointers!

```
var rList = app.buildList("Please select one option:");
for (var r =0; r < resp_text.length; r++) {
  rList.addItems(app.buildOptionItem(resp_value[r], resp_matches[r]).setTitle(resp_text[r]));
}
app.askWithList(question_str, rList);
```

**Comment by JonathanOrozcoIrvineCompany** [comment]
Since v2 is taking a more Object based approach to building responses lists have this design
```
conv.ask(new List({
    items: [
        {
            title: ,
            description: ,
            image: new Image({
                url: ,
                alt: ,
            })
        },
        ...
    ]
}))
```
Thus you can dynamically build your list by constructing an array of items and using that as the value for the list constructor.

**Comment by mmenti** [comment]
Ah that makes sense, will give this a go! Thanks for pointing me in the right direction!
