### ISSUE TITLE
Latest version doesn't support V2?

### ISSUE THREAD

**Issue by Mrinnaal** [actions-on-google/actions-on-google-nodejs#147]
@Fleker 
I was using 2.0.1 version of this npm few days back which takes dialogflow instance and supports V2 things. Now again when i try to create new app it is telling updated version is 1.11.0 which doesn't have dialogflow instead it has the old one dialogFlowApp and in doc it had mentioned again V2 is not supported! Which one should i go with so that it will be stable? Please respond to this

**Comment by Petter17** [comment]
Same issue... Actual version doesn't match with docs .

**Comment by Fleker** [comment]
Can you post your `package.json`, at least the line where you add the library? You should probably make sure you're pinned to `^2.0.0`, which will only get versions of the client library with the major version 2.

We did just [release version `2.1.0` and `1.11.0`](https://github.com/actions-on-google/actions-on-google-nodejs/releases), with compatibility for developers using either version.

**Comment by Mrinnaal** [comment]
@Fleker  even after pinning when u add that require it is just showing any! Not as a instance from package. Is it fine even if it shows as any?

**Comment by Mrinnaal** [comment]
Thank you bro :) issue is fixed @Fleker
