### ISSUE TITLE
Can't receive dialogflow's @sys.date

### ISSUE THREAD

**Issue by jeffersontpadua** [actions-on-google/actions-on-google-nodejs#148]
Hey Guys!

I'm experiencing a really buggy issue when I add any parameter with dialogflow's @sys.date.

Every single request containing this type breaks my webhook with a " Uncaught SyntaxError: Unexpected number in JSON at position 4". By the way, my webhook is hosted within Firebase Functions. 

It always break at line 252 of this file src/service/dialogflow/conv.ts as it tries to JSON.parse the string. which is a date ("2018-04-06T12:00:00-06:00") in  ISO-8601 format.

Maybe we should check if the string is formatted as date first? 

Hope it is as simple as that.

Anyways, thank you guys for the amazing library!

**Comment by lucaswadedavis** [comment]
It's been... a while... You still having problems with this Jefferson?

**Comment by maaaaaaaax** [comment]
Please reopen this issue if you have new information!
