### ISSUE TITLE
Async middleware

### ISSUE THREAD

**Issue by joelhegg** [actions-on-google/actions-on-google-nodejs#151]
I have a use case to make an internal service call before all intents. One enhancement to this library I'd like to see to support this is for ActionsSdkApp.middleware to take async functions. I've had to hack around this in the time being in an Express middleware.

**Comment by joelhegg** [comment]
Yes, I would expect `app.middleware` to behave similarly to `app.intent` and support `async`. I'd be surprised if you couldn't make this enhancement to `app.middleware` in a backwards compatible way.

**Comment by Canain** [comment]
It's added now in `2.2.0`

Try it and let me know us know of any feedback.

**Comment by joelhegg** [comment]
Thanks @Canain. I've already made the switch and rolled it out. Looking good.
