### ISSUE TITLE
Non-trivial modifications to Conversation resulting in circular structure error

### ISSUE THREAD

**Issue by joelhegg** [actions-on-google/actions-on-google-nodejs#152]
https://developers.google.com/actions/reference/nodejs/lib-v1-migration#scaling_with_plugins_and_middleware says:
> Using a middleware layer lets you modify the Conversation instance and add additional functionality.

I want to have my middleware add some additional request context to `conv` that I can later reference in my intents like this:
```
import * as bunyan from 'bunyan';
import * as uuid from 'uuid';

const logger = bunyan.createLogger({name: 'default'});

app.middleware(conv => {
  const requestId = uuid.v4();
  const ctx = {
    requestId,
    logger: logger.child({requestId})
  };
  (conv as any).ctx = ctx;
});

app.intent('actions.intent.MAIN', conv => {
  const ctx = (conv as any).ctx;
  ctx.logger.info('In MAIN intent');
  conv.close('Hello world!');
});
```
When I run this though I get this error:
```
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Object.exports.clone (./node_modules/actions-on-google/dist/common.js:33:40)
    at Object.exports.stringify (./node_modules/actions-on-google/dist/common.js:35:75)
```
I pinpointed the problem to having the `logger` object in my `conv` when this `stringify` call happens: https://github.com/actions-on-google/actions-on-google-nodejs/blob/7e838e37e1e5f7499d228dad1782589886ab64db/src/service/actionssdk/actionssdk.ts#L337-L341

So this overly ambitious `stringify` calls seems to be getting in the way of allowing middleware to add non-trivial objects to `conv`. My work around for now is to make `ctx` a function instead, which stringify will skip:
```
  ...
  (conv as any).ctx = () => ctx;
  ...
  const ctx = (conv as any).ctx();
  ...
```
So should the `stringify` call be changed or should middleware be given a specific place in `conv` to add custom objects that can be ignored by `stringify`?

**Comment by Canain** [comment]
Yeah, this was a bug introduced in 2.1.0 where the debug log was [moved](https://github.com/actions-on-google/actions-on-google-nodejs/commit/ba8d5cf75b37a81e77bb3cdf7414f40510def2dd#diff-5f6ac3ba1e3bdd7d9ebf3ae0ea97c164R381) to after the middleware calls.

This also caused [one of our samples to break](https://github.com/actions-on-google/dialogflow-number-genie-nodejs/issues/10).

We are working on a fix right now to make stringify more error tolerant and also detect basic circular references.

**Comment by Canain** [comment]
Should be fixed now, try using the new version: `npm install actions-on-google@^2.1.2`

**Comment by ninhxuanluu** [comment]
Im using actions-on-google v2.3.0 and expressjs, this error appearance again, here is my logs : 
`TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at stringify (/opt/gactions-custom/node_modules/express/lib/response.js:1119:12)
    at ServerResponse.json (/opt/gactions-custom/node_modules/express/lib/response.js:260:14)
    at ServerResponse.send (/opt/gactions-custom/node_modules/express/lib/response.js:158:21)
    at standard.then (/opt/gactions-custom/node_modules/actions-on-google/dist/framework/express.js:34:41)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)`
