### ISSUE TITLE
Access original request object

### ISSUE THREAD

**Issue by avadhpatel** [actions-on-google/actions-on-google-nodejs#156]
I am looking at new v2.1.1 library and its API and I am trying to find a way to access the original 'request' object in an intent handler. My app uses various middlewares to populate user object and other meta-data which is used by intent handler.

After looking at the code and API of new library, it seems that there is no way to access the original request object via the 'conversation' object. If there is a way to access it please can someone give me an example code?

**Comment by Canain** [comment]
You can use `conv.body` for the raw request JSON, and `conv.request` for the extracted Actions SDK JSON data.

**Comment by avadhpatel** [comment]
That doesn't help as I want to access the 'request' object passed from express to 'app', not the body or extracted JSON.

There are custom middlewares used in my application that parses the request and modify the 'request' object to add local user information and also determines if the request is originated from Google device or Web-plugin, as DialogFlow allows only one webhook endpoint for the agent.

**Comment by Canain** [comment]
Ah, I see, yeah this would be a feature request to allow metadata to be available for frameworks.

Since the library supports not just express but also other web frameworks, it needs to be designed to for all frameworks.

I'm thinking it might look something like `conv.metadata.express.request` in the future.

**Comment by avadhpatel** [comment]
This sounds good. Any idea how long will it take?

If you can suggest some design then I can patch and submit the pull request.

**Comment by Canain** [comment]
It turns out this is a bit more complex to implement because it's not exactly a property that makes sense to put in the `Conversation` object but we have been working on a proper solution.

In the meanwhile, you use a hacky solution with a ES6 `Map` and a Custom Framework for Express:

```javascript
const bodyMap = new Map()

class CustomExpress {
  handle(standard) {
    return (request, response) => {
      bodyMap.set(request.body, request)
      standard(request.body, request.headers)
      .then(({ status, body, headers }) => {
        if (headers) {
          for (const key in headers) {
            response.setHeader(key, headers[key])
          }
        }
        response.status(status).send(body)
        bodyMap.delete(request.body)
      })
      .catch(e => {
        console.error(e.stack || e)
        response.status(500).send({ error: e.message })
        bodyMap.delete(request.body)
      })
    }
  }

  isResponse(second) {
    return typeof second.send === 'function'
  }
  isRequest(first) {
    return typeof first.get === 'function'
  }

  check(first, second) {
    return this.isRequest(first) && this.isResponse(second)
  }
}

app.frameworks.express = new CustomExpress()

app.middleware(conv => {
  conv.expressRequest = bodyMap.get(conv.body)
})
```

Then, you can retrieve the express request object using `conv.expressRequest`.

**Comment by avadhpatel** [comment]
Thanks for this hack. I will test it out and will let you know how well it worked.

Also on the side note, why can't I return a promise on a middleware?

**Comment by Canain** [comment]
Middlewares were added later on in the library development as a helper for plugins so they haven't been completely fleshed out yet.

We're keeping track already of a feature request to add Promise support for middleware: https://github.com/actions-on-google/actions-on-google-nodejs/issues/151

**Comment by Canain** [comment]
Both async middlewares and ability to access metadata are now added in `2.2.0`.

An object containing framework metadata is now present as the 2nd parameter in middleware (instead of inside Conversation as it's not really a conversation value).

```javascript
app.middleware((conv, framework) => {
  return new Promise(resolve => {
    if (framework.express) {
      conv.requestMethod = framework.express.request.method
    }
  })
})

app.intent('some intent', conv => {
  conv.ask(`Method sent was ${conv.requestMethod}`)
})
```

Try it out and let us know of any feedback.

**Comment by ayushsharma82** [comment]
@Canain  We need something similar for smarthome intents too. Because in express we pass along the user data in request object. Please let me know how can we access 'request.user' object in Sync Intents etc.

**Comment by Fleker** [comment]
@ayushsharma82 in smart home intents, the user object doesn't exist. Instead, you get an access token in the request header. If you have a more specific question, you can file a new issue.
