### ISSUE TITLE
Proposal: Support Action Name Matching with app.action()

### ISSUE THREAD

**Issue by yoichiro** [actions-on-google/actions-on-google-nodejs#164]
# My Proposal: Introduce an action matching mechanism

In the latest version, we need to use the intent-name-based matching mechanism as like the following:

```js
const app = dialogflow();
app.intent('Default Welcome Intent', conv => {
  ...
});
```

My proposal is that we can handle an action name as like the following, if an intent name is not matched for all registered intent handlers:

```js
const app = dialogflow();
app.action('input.welcome', conv => {
  ...
});
```

As an important thing, Introducing the `app.action()` function never encumber the current intent name routing behavior. That is, I think that I can continue to keep current compatibility if the `app.action()` function is added.

In the previous version, there was the routing mechanism using an action name. However, in current version 2, we must use the routing mechanism using an intent name only. I would like to come back the action name routing mechanism, and I think that we should provide the action name routing as well for many developers.

The reasons are follows:

# 1st Reason: Fulfillment becomes complex

If there is an action in the architecture of an intent and a fulfillment, we can use one action from multiple intents. This brings the architecture flexibility. For example, if we define two intents and they refer one action from both, we can get each analysis of the intents separately in Dialogflow. At the same time, we also can keep the fulfillment logic simplify, because we only need to imlement one action logic.

However, in the latest version, I think that we lost the benefit. We always must define handlers for all intents in the fulfillment. I think that this is redundant. We had both felxibility and simplify brought by the action name. The intent mapping looks simple, but I think there is no flexibility and the fulfillment logic becomes complex.

Also, we can specify an array of intent names as 1st argument of `app.intent()` function, but I think that we should not resolve a mapping between multiple intents and one action behavior in fulfillment side. Because I recognize that essentially a fulfillment is to provide business logics based on each action name.

# 2nd Reason: Migration cost

As the 1st reason above, in v2, we need to change our recognition from action name matching to intent name matching. That is, it is necessary to change our fulfillment codes drastically. All developers who have some apps written using v1 must pay the big cost.

At least, we should provide something of APIs to migrate the v1 apps in low cost. I believe that we can achieve the migration in low cost by the `app.action` function, because developers don't need to change the architecture and structure of v1 apps.

# 3rd Reason: Intent Name as Identifier

Until the previous version, we could use the intent name as explanation. Especially in the multibyte language environment, most intent names might have some multibyte characters and some whitespaces. That is, the intent name was not an identifier, and all intent names were not refered from anywhere. As the result, we could change all intent names at anytime. However, in the latest version, we cannot change all intent name easily because there is a possibility to be referred from a fulfillment code.

Also, generally, we don't use some multibyte characters and whitespaces for an identifier. In the latest version, the intent name is an identifier. That is, we must think that we cannot use multibyte characters and whitespaces for intent names. This means that a purpose of the intent name changes largely from explanation to identifier.

I think that all intent names should be clear and useful. That is, we should use multibyte characters and whitespaces for the purpose.

In addition, if using multibyte character, we might face a possibility regarding a character code problem in our fulfillment.

**Comment by urish** [comment]
Same here - our [Spanish Lesson action](https://assistant.google.com/services/a/uid/0000003c827f19d5) was built with v1, and are holding back migration to v2 as we have some complicated flows and migrating would be very high risk for us and would require some delicate refactoring both in DialogFlow and our code and rigorous testing to make sure we don't break anything.

Please consider merging the pr @yoichiro sent, this is the only thing holding us back from migrating to v2. We already have a `v2` branch in our project, and if this lands, we will be able to merge it and complete the migration.

**Comment by yoichiro** [comment]
It has already been past enough time after the sdk v2 released. I guess that many developers have already familiar with the intent name based routing. Therefore, I think that the action name based routing may be unnecessary.

@Canain Could you confirm about that with the sdk team members? If they have a same opinion, I intend to drop this issue and pull request #166.

**Comment by yoichiro** [comment]
I close this issue because I could not get any responses here.
