### ISSUE TITLE
Error in actions_intent_TRANSACTION_DECISION event

### ISSUE THREAD

**Issue by vebester** [actions-on-google/actions-on-google-nodejs#167]
Error in actions_intent_TRANSACTION_DECISION event.
textPayload:  "SyntaxError: Unexpected token # in JSON at position 0
    at Object.parse (native)
    at createStrictSyntaxError (/var/tmp/worker/node_modules/body-parser/lib/types/json.js:157:10)
    at parse (/var/tmp/worker/node_modules/body-parser/lib/types/json.js:83:15)
    at /var/tmp/worker/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (/var/tmp/worker/node_modules/raw-body/index.js:224:16)
    at done (/var/tmp/worker/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/var/tmp/worker/node_modules/raw-body/index.js:273:7)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)"

After invoking new TransactionDecision(valueSpec) with valueSpec:
{"paymentOptions":{"googleProvidedOptions":{"prepaidCardDisallowed":false,"supportedCardNetworks":["VISA","MASTERCARD","AMEX"],"tokenizationParameters":{"tokenizationType":"PAYMENT_GATEWAY","parameters":{"gateway":"stripe","stripe:publishableKey":"pk_test_1234","stripe:version":"2018-05-21"}}}},"orderOptions":{"requestDeliveryAddress":false},"proposedOrder":{"id":"21","cart":{"merchant":{"id":"lenka_store_1","name":"Lenka Store"},"lineItems":[{"name":"Adding balance to your account","id":"product_1","price":{"amount":{"currencyCode":"USD","units":1},"type":"ACTUAL"},"quantity":1,"type":"REGULAR"}],"notes":"Your order #21 in Lenka Store","otherItems":[]},"otherItems":[],"totalPrice":{"amount":{"currencyCode":"USD","units":1},"type":"ESTIMATE"}}}

and pressing Place order in Google Assistant we have got in the our intent with actions_intent_TRANSACTION_DECISION event this error,
and webhook in that intent is not called and we cannot receive and handle userDecision === 'ORDER_ACCEPTED'

project: lenka-ai
sandbox mode

**Comment by nareshjiva** [comment]
@vebester  did you find any solution am also getting the same issue

**Comment by vebester** [comment]
@nareshjiva 
i did not find the solution
my app and the example app  https://github.com/actions-on-google/dialogflow-transactions-nodejs
are getting the same error no matter with actionProvidedOptions or googleProvidedOptions

actions-on-google did not receive proper response from GA after placing the order or did not handle it properly

**Comment by Canain** [comment]
This looks like a bug with Dialogflow v2 and Transaction Decision. Try switching to Dialogflow v1 in the Dialogflow Console and try again.

If it doesn't work, can you provide more logs?

**Comment by nareshjiva** [comment]
Hi Canain,

I changed the v2 to v1 in dialog flow its working but with v2 it's not working I sent a mail to support also 

Please review the logs 

 

Thanks,

Naresh.Sangana

**Comment by vebester** [comment]
Yes, it works with Dialogflow v1

**Comment by lamer-x11** [comment]
Disable body-parser, handle the request manually and try running `JSON.parse` on the incoming request twice.

**Comment by nareshjiva** [comment]
@lamer 

can you explain me the steps how disable body-parser and where to keep JSON.parse

here is my order confirmation code and transaction.complete is my intent name 

module.exports = {
    'transaction.complete': (conv,params) => {	      
      const arg = conv.arguments.get('TRANSACTION_DECISION_VALUE');
      if (arg && arg.userDecision ==='ORDER_ACCEPTED') {        
        const finalOrderId = arg.order.finalOrder.id;
      }
   }
};

Thanks

**Comment by Canain** [comment]
Hi all, the issue should be fixed now.

Can you verify if it works now with Dialogflow v2?

**Comment by vebester** [comment]
Yes, fixed! It works with Dialogflow v2.

**Comment by Canain** [comment]
Thanks for verifying! Closing the bug since it's resolved
