### ISSUE TITLE
Trying to deploy to google functions but failed to find modules actions-on-google

### ISSUE THREAD

**Issue by chantrea999** [actions-on-google/actions-on-google-nodejs#171]
Cd /googlecloud/functions
then
npm install actions-on-google
I got this
+ actions-on-google@2.1.3
updated 1 package in 5.395s
And glcoud compents update  is already latest updated.

then I tried to deploy the code
gcloud beta functions deploy myfunctionname --stage-bucket myfunctionapibucket.appspot.com --trigger-http
Then It is response like this
Deploying function (may take a while - up to 2 minutes)...failed.              
ERROR: (gcloud.beta.functions.deploy) OperationError: code=3, message=Function load error: Code in file index.js can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module 'actions-on-google'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/index.js:20:6)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)

in the index.js code
I just did simple 
const {
	  dialogflow,
	  Image,
	} = require('actions-on-google')

	// Create an app instance
	const app = dialogflow()
if I remove those line esp require('actions-on-google') then my function work correctly.

Please let me know what is the exactly issues?

Thank

**Comment by Fleker** [comment]
If you just type `npm install`, it will go to the `package.json` file and install the dependencies and save them in a local directory.

**Comment by chantrea999** [comment]
I did exactly like you said but when I deployed it is giving me the same errors
gcloud beta functions deploy myfunction --stage-bucket mybucket.appspot.com --trigger-http
Deploying function (may take a while - up to 2 minutes)...failed.                                                             
ERROR: (gcloud.beta.functions.deploy) OperationError: code=3, message=Function load error: Code in file index.js can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module 'actions-on-google'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/index.js:20:6)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)

And here is my package.json
{
  "private": true,
  "repository": {
    "private": true
  },
  "dependencies": {
    "actions-on-google": "^2.1.3",
    "update": "^0.7.4"
  }
}
but it is locate in /my/project/package.json
and my index.js is located in /my/project/DialogFlowNodeJS/dev/index.js

Thank you

**Comment by Fleker** [comment]
While you are in `/my/project/` you should run `npm install` and then it should install everything. You should then see a `/my/project/node_modules` directory which will contain the downloaded code.

**Comment by chantrea999** [comment]
Yes I saw that node_modules so should I looking into actions-on-google folders inside node_modules?

**Comment by chantrea999** [comment]
more over I can cd node_modules/actions-on-google and do ls and show me all this packages.
LICENSE		README.md	dist		package.json	src		typedoc.json	yarn.lock

**Comment by Fleker** [comment]
Do you need your index.js file to be nested within `/my/project/DialogFlowNodeJS/dev/`? If you keep everything in the top-level directory you should be able to deploy the index.js without issue.

**Comment by chantrea999** [comment]
Ok thank flex let me try to keep it in the same level and I will get back to you
Thanks

**Comment by chantrea999** [comment]
Yes it is working thank you.

**Comment by chantrea999** [comment]
Looking into account linking I just want to get user information from google assistant and I used this code but It never work

const {dialogflow} = require('actions-on-google');
            const app = dialogflow({debug: true, clientId: "xxxxx"});
          app.intent('ask_for_sign_in', (conv) => {
            conv.ask(new SignIn());
          });
            // Create a Dialogflow intent with the `actions_intent_SIGN_IN` event
            app.intent('ask_for_sign_in_confirmation', (conv, params, signin) => {
              if (signin.status !== 'OK') {
                return conv.ask('You need to sign in before using the app.');
              }
              return conv.ask('Great! Thanks for signing in.');
            });

I already created ask_for_sign_in Intent and Action it as Signed In Required? Can you explain? and give me some full example?

**Comment by Fleker** [comment]
You may want to make a new issue or ask your question on StackOverflow. I'm going to close this issue as the original issue has been resolved. Thanks.

**Comment by kirantpatil** [comment]
Dear @chantrea999,

Have you resolved this issue ?

Please let us know how did you resolve it.

We are getting "[TypeError: smarthome is not a function](https://github.com/actions-on-google/actions-on-google-nodejs/issues/317)" error while accessing smarthome.
