### ISSUE TITLE
Missing export of OptionItems

### ISSUE THREAD

**Issue by zwade** [actions-on-google/actions-on-google-nodejs#172]
In `actions-on-google/src/index.ts`, the `OptionItems` class is not being exported from `./service/actionssdk`. This is problematic when trying to create a new `ListOptions` because it makes building the list items programmatically more difficult.

Currently the only (typesafe) ways to construct a `ListOptions` is to duplicate the definition of `OptionItems` (annoying) or construct the whole `ListOptions` statically (impractical). Furthermore, the `items` can take either a `ListOptions` or a `GoogleActionsV2UiElementsListSelectListItem` which index differently (the former by strings and the latter by numbers) so you can't modify the `items` field of an already constructed `ListOptions`. In addition, it seems that the second item type is not meant to be used externally given it's unwieldy name and the fact that it makes `optionInfo` an optional parameter which is not permitted by the server.

This all seems to suggest that not exporting `ListOptions` was a bug. However, its possible that I'm misunderstanding the intent of a list and that it was designed to be constructed only statically. If this is the case, perhaps a comment or two to this end would be helpful.

**Comment by Canain** [comment]
Yeah, the TypeScript developer experience can be improved.

We'll keep track of this to improve in the future.

**Comment by lucaswadedavis** [comment]
Due to more than 3 months of inactivity, this issue is being closed. 

If you think the resolution is in error, please re-open the request with fresh information.
