### ISSUE TITLE
AWS Lambda Response throwing error in dialogflow when using v2

### ISSUE THREAD

**Issue by rahul71** [actions-on-google/actions-on-google-nodejs#173]
I am returning what looks like the correct response from the AWS lambda to dialogflow but its throwing an error in dialogflow. The FULFILLMENT RESPONSE tab shows the following

```{
  "statusCode": 200,
  "body": {
    "payload": {
      "google": {
        "expectUserResponse": true,
        "richResponse": {
          "items": [
            {
              "simpleResponse": {
                "textToSpeech": "AWS LAMBDA says hi"
              }
            }
          ]
        },
        "userStorage": "{\"data\":{}}"
      }
    },
    "outputContexts": [
      {
        "name": "projects/<someid>/agent/sessions/<someId>/contexts/_actions_on_google",
        "lifespanCount": 99,
        "parameters": {
          "data": "{}"
        }
      }
    ]
  }
}
```

but it shows an error in the FULFILLMENT STATUS tab

`Webhook call failed. Error: Failed to parse webhook JSON response: Cannot find field: statusCode in message google.cloud.dialogflow.v2.WebhookResponse.`

**Comment by Canain** [comment]
Hi, how are you exposing your lambda function?

The client library currently expects lambda to be used by API Gateway which expects a `statusCode` and `body` field to convert into a HTTP response.

**Comment by rahul71** [comment]
@Canain the lambda function is exposed using an api gateway. Do I need to do something special in the API gateway to return data correctly?

**Comment by hoklai1997** [comment]
I'm getting a similar problem which I suspect is actions-on-google is not exposing my lambda function. From what I can tell based on the documentation all I should need to add is
`exports.fulfillment = app;`
but with a very minimal test app:
``` javascript
const {
    dialogflow,
    BasicCard,
    BrowseCarousel,
    BrowseCarouselItem,
    Button,
    Carousel,
    Image,
    LinkOutSuggestion,
    List,
    MediaObject,
    Suggestions,
    SimpleResponse,
    Table,
   } = require('actions-on-google');
const app = dialogflow();
app.intent('example', (conv) => {
    conv.ask(new SimpleResponse({
        speech:"Working",
        text:"Working"
    }));
});

exports.fulfillment = app;
```

I am getting the following response:
Webhook call failed. Error: Failed to parse webhook JSON response: Cannot find field: errorMessage in message google.cloud.dialogflow.v2.WebhookResponse.

**Comment by rahul71** [comment]
@hoklai1997 if you use my code above it almost works...as in runs the code but does not return correctly. I did have to add the following body mapping template in the Integration Request of the API gateway. The response seems to be sent back except dialogflow does not recognize it. 

Request Body Passthrough:  When there are no templates defined (recommended) 
Content-Type: application/json
and when you click on the application/json I have the following template
```##  See http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html
##  This template will pass through all parameters including path, querystring, header, stage variables, and context through to the integration endpoint via the body/payload
#set($allParams = $input.params())
{
"body" : $input.json('$'),
 "headers": {
        #foreach($param in $input.params().header.keySet())
        "$param": "$util.escapeJavaScript($input.params().header.get($param))"
        #if($foreach.hasNext),#end
        #end
    },
"params" : {
#foreach($type in $allParams.keySet())
    #set($params = $allParams.get($type))
"$type" : {
    #foreach($paramName in $params.keySet())
    "$paramName" : "$util.escapeJavaScript($params.get($paramName))"
        #if($foreach.hasNext),#end
    #end
}
    #if($foreach.hasNext),#end
#end
},
"stage-variables" : {
#foreach($key in $stageVariables.keySet())
"$key" : "$util.escapeJavaScript($stageVariables.get($key))"
    #if($foreach.hasNext),#end
#end
},
"context" : {
    "account-id" : "$context.identity.accountId",
    "api-id" : "$context.apiId",
    "api-key" : "$context.identity.apiKey",
    "authorizer-principal-id" : "$context.authorizer.principalId",
    "caller" : "$context.identity.caller",
    "cognito-authentication-provider" : "$context.identity.cognitoAuthenticationProvider",
    "cognito-authentication-type" : "$context.identity.cognitoAuthenticationType",
    "cognito-identity-id" : "$context.identity.cognitoIdentityId",
    "cognito-identity-pool-id" : "$context.identity.cognitoIdentityPoolId",
    "http-method" : "$context.httpMethod",
    "stage" : "$context.stage",
    "source-ip" : "$context.identity.sourceIp",
    "user" : "$context.identity.user",
    "user-agent" : "$context.identity.userAgent",
    "user-arn" : "$context.identity.userArn",
    "request-id" : "$context.requestId",
    "resource-id" : "$context.resourceId",
    "resource-path" : "$context.resourcePath"
    }
}
```

**Comment by hoklai1997** [comment]
@rahul71 Thanks for the guidance, I actually started wiring up something similar, but the documentation literally describes the actions on google-lambda interaction as plug and play, so I thought I must be doing something wrong

**Comment by rahul71** [comment]
@hoklai1997 please let me know if you get the whole thing working since I am still stuck.

**Comment by hoklai1997** [comment]
I got it working:
```javascript
const {
    dialogflow,
    BasicCard,
    BrowseCarousel,
    BrowseCarouselItem,
    Button,
    Carousel,
    Image,
    LinkOutSuggestion,
    List,
    MediaObject,
    Suggestions,
    SimpleResponse,
    Table,
} = require('actions-on-google');
 
const app = dialogflow() 
 
app.intent('test', (conv, params) => {
    conv.ask(new SimpleResponse({
        speech: "WORKING!!!",
        text: "GOT IT WORKING YOU HANDSOME BASTARD"
    }))
});
 
app.fallback((conv) => {
    conv.ask(new SimpleResponse({
        speech: "I'm sorry, I didn't catch that",
        text: "I'm sorry, I didn't catch that"
    }));
}); 
 
exports.handler = function(event, context, callback) {
    app.handler(event, undefined).then((res) => {
        if (res.status != 200) {
            callback(null, {"fulfillmentText": `I got status code: ${res.status}`});
        } else {
            callback(null, {"fulfillmentText": res.body});
        }
    }).catch((e) => {
    callback(null, {"fulfillmentText": `There was an error\n${e}`});
    });
}; 
```
Just so you know, since I'm using SimpleResponse, the dialogflow test window doesn't display anything when it runs succesfully. You can either go into the Diagnostic Info to take a look, or open up the simulator and it should be working. Good Luck!

**Comment by rahul71** [comment]
hoklai1997  This is great, thanks. Will test it

**Comment by rahul71** [comment]
@hoklai1997 got it working as well. Thanks a lot for your help. Wonder if there is a way to make it show up in the dialog flow test window. I tried using convo.close('some text') but that did not fly for dialog flow testing. As you said it works fine from actions simulator

**Comment by CoreyCole** [comment]
@Canain the conclusion reached in this thread is not consistent with [the documentation](https://developers.google.com/actions/reference/nodejs/lib-v1-migration#new_frameworks_system). I was having trouble following the documentation, but this explicit handler function with fufillmentText got it working for me in aws lambda. Is the documentation out of date?

**Comment by CoreyCole** [comment]
@hoklai1997 any idea how to get a line number for the error? This prints the error but it really hard to track down where it's being thrown from.
```
callback(null, {"fulfillmentText": `There was an error\n${e}`});
```
```
{
  "fulfillmentText": "There was an error\nTypeError: Cannot read property 'status' of undefined"
}
```

**Comment by thehellmaker** [comment]
For smarthome intents I used the following mapping template to trigger app.sync, app.query and app.execute intents

##  This template will pass through all parameters including path, querystring, header, stage variables, and context through to the integration endpoint via the body/payload
#set($allParams = $input.params())
{
 "inputs": $input.json('inputs'),
 "requestId": $input.json('requestId'),
 "headers": {
        #foreach($param in $input.params().header.keySet())
        "$param": "$util.escapeJavaScript($input.params().header.get($param))"
        #if($foreach.hasNext),#end
        #end
    },
"params" : {
#foreach($type in $allParams.keySet())
    #set($params = $allParams.get($type))
"$type" : {
    #foreach($paramName in $params.keySet())
    "$paramName" : "$util.escapeJavaScript($params.get($paramName))"
        #if($foreach.hasNext),#end
    #end
}
    #if($foreach.hasNext),#end
#end
},
"stage-variables" : {
#foreach($key in $stageVariables.keySet())
"$key" : "$util.escapeJavaScript($stageVariables.get($key))"
    #if($foreach.hasNext),#end
#end
},
"context" : {
    "account-id" : "$context.identity.accountId",
    "api-id" : "$context.apiId",
    "api-key" : "$context.identity.apiKey",
    "authorizer-principal-id" : "$context.authorizer.principalId",
    "caller" : "$context.identity.caller",
    "cognito-authentication-provider" : "$context.identity.cognitoAuthenticationProvider",
    "cognito-authentication-type" : "$context.identity.cognitoAuthenticationType",
    "cognito-identity-id" : "$context.identity.cognitoIdentityId",
    "cognito-identity-pool-id" : "$context.identity.cognitoIdentityPoolId",
    "http-method" : "$context.httpMethod",
    "stage" : "$context.stage",
    "source-ip" : "$context.identity.sourceIp",
    "user" : "$context.identity.user",
    "user-agent" : "$context.identity.userAgent",
    "user-arn" : "$context.identity.userArn",
    "request-id" : "$context.requestId",
    "resource-id" : "$context.resourceId",
    "resource-path" : "$context.resourcePath"
    }
}

**Comment by priyanshonivart** [comment]
can anyone help me in retrieving the intent value from dialogflow. 
const {
    dialogflow,
    BasicCard,
    BrowseCarousel,
    BrowseCarouselItem,
    Button,
    Carousel,
    Image,
    LinkOutSuggestion,
    List,
    MediaObject,
    Suggestions,
    SimpleResponse,
    Table,
} = require('actions-on-google');
 
const app = dialogflow() 
 
app.intent('devicecontrol', (conv,{devicename,devicestatus}) => {
    let device_name = devicename;
    let device_status = devicestatus;
    
    if(device_name == "fan" && device_status == "on"){
    
    conv.ask(new SimpleResponse({
        speech: "WORKING!!!",
        text: "turned fan on"
    }))
    
    }
    else{
        
        conv.ask(new SimpleResponse({
        speech: "WORKING!!!",
        text: "GOT IT WORKING"
        }))
        
    }
    
});
 
app.fallback((conv) => {
    conv.ask(new SimpleResponse({
        speech: "I'm sorry, I didn't catch that",
        text: "I'm sorry, I didn't catch that"
    }));
}); 
 
exports.handler = function(event, context, callback) {
    app.handler(event, {}).then((res) => {
        if (res.status != 200) {
            callback(null, {"fulfillmentText": `I got status code: ${res.status}`});
        } else {
            callback(null, res.body);
        }
    }).catch((e) => {
    callback(null, {"fulfillmentText": `There was an error\n${e}`});
    });
}; 


this above is not working for me
