### ISSUE TITLE
promise is not working in  actions on google v2 - firebase function - dialogflow v2 

### ISSUE THREAD

**Issue by malikasinger1** [actions-on-google/actions-on-google-nodejs#174]
I wanted to get some data from mongodb (using mongoose framework) but unable to get the data, 

previously i was using callback method as described [here][1] to getting data which was working well for me in "[action on google][2] v1" but not working in v2, 

then i read [here][3] that we must need to use promise in order to make async call in "[action on google][2] v2", then i refactored my code according to the instruction of Mr. @prisoner in the question above 

you can see my code here: 

    import * as functions from 'firebase-functions';

    import {
        dialogflow, 
        SimpleResponse,
        Suggestions, 
        DialogflowConversation, 
        DialogflowApp
    } from 'actions-on-google'

    import { Model } from './db'

    const app = dialogflow({ debug: false })

    app.middleware((conv) => {
        conv["hasScreen"] =
            conv.surface.capabilities.has('actions.capability.SCREEN_OUTPUT');
        conv["hasAudioPlayback"] =
            conv.surface.capabilities.has('actions.capability.AUDIO_OUTPUT');
    });

    app.intent('Get Some Data', (conv) => {    
    
            console.log("Get Some Data Intent triggered")
    
            return new Promise(function (resolve, reject) {
    
                Model.find({}, (err, result: any) => {
                    if (!err) {
    
                        if (!result.length) {
    
                            console.log("no data found")
                            conv.ask(new SimpleResponse({
                                speech: "no data found"
                            }))
                            resolve();
    
                        } else {
    
                            console.log("lots of data found")
                            conv.ask(new SimpleResponse({
                                speech: "lots of data found"
                            }));
                            resolve();
    
                        }
                    } else {
                        console.log("Error in getting data: ", err);
                        conv.ask(new SimpleResponse({
                            speech: "Error in getting data"
                        }))
                        resolve();
                    }
                })
            })
    });
    
    exports.webhook = functions.https.onRequest(app);

it is still not working for me, and function is ending with timeout

Actually i have my app up and running properly in v1, and now I'm trying to migrate from v1 to v2 since i need to use some latest features which are not available in v1 like voice authentication and other new features.
any help will be warmly welcomed

also asked on stackoverflow https://stackoverflow.com/questions/9022099/how-to-use-mongoose-promise-mongo

  [1]: http://mongoosejs.com/docs/queries.html
  [2]: https://github.com/actions-on-google/actions-on-google-nodejs
  [3]: https://stackoverflow.com/questions/49909455/error-no-response-has-been-set-cloud-functions-for-actions-on-google-assistant

**Comment by jayinc** [comment]
+1

**Comment by Fleker** [comment]
What logs are printed out?

**Comment by Canain** [comment]
Since you are using TypeScript, you can use `async await` to simplify the code, just make sure the target is es6.

Via the stackoverflow post you linked, mongoose already has promise support built in using `.exec()`.

So the code can be simplified to:
```typescript
app.intent('Get Some Data', async (conv) => {
  console.log('Get Some Data Intent triggered')
  const query = {} // your query for model here
  try {
    const result = await Model.find(query).exec()
    if (!result.length) {
      console.log('no data found')
      conv.ask(new SimpleResponse({
        speech: 'no data found',
      }))
    } else {
      console.log('lots of data found')
      conv.ask(new SimpleResponse({
        speech: 'lots of data found',
      }))
    }
  } catch (e) {
    console.log('Error in getting data: ', e)
    conv.ask(new SimpleResponse({
      speech: 'Error in getting data',
    }))
  }
})
```

**Comment by malikasinger1** [comment]
@canain your solution sounds like a plan, thanks i will try it out today

**Comment by akirpalaniAGL** [comment]
@Canain @malikasinger1 Any update on this issue?

**Comment by Canain** [comment]
Closing this since there hasn't been more comments.
