### ISSUE TITLE
Issue with the simulator displaying Directory Name instead of Invocation Name

### ISSUE THREAD

**Issue by LakshayNagpal** [actions-on-google/actions-on-google-nodejs#175]
Hi Team,

I was testing my app and I observed an error in which simulator on AoG was displaying the Directory Title that I have given to my app but is working with Invocation Name. You can see the attachments for more reference. This is a bug which I feel needs to be resolved as it may mislead the users of AoG.

<img width="1183" alt="screen shot 2018-06-12 at 7 00 35 pm" src="https://user-images.githubusercontent.com/9516787/41293644-7e43e14a-6e73-11e8-912c-f6eb5528b6fc.png">
<img width="1181" alt="screen shot 2018-06-12 at 7 00 45 pm" src="https://user-images.githubusercontent.com/9516787/41293646-7e870042-6e73-11e8-8946-84566b6bf61b.png">

Not working with the directory title

<img width="1183" alt="screen shot 2018-06-12 at 7 01 35 pm" src="https://user-images.githubusercontent.com/9516787/41293650-7f13d9ae-6e73-11e8-9072-4c63d4dd0db0.png">

Working with the Invocation Name

<img width="1184" alt="screen shot 2018-06-12 at 7 01 20 pm" src="https://user-images.githubusercontent.com/9516787/41293648-7eccba88-6e73-11e8-9c54-de9e85a46a36.png">

Please have a look at this issue and if you need any help from my end, do reply to this thread.

Thanks :)

**Comment by Canain** [comment]
Do you still see this issue?

**Comment by LakshayNagpal** [comment]
I was told by the Actions on Google Support that Invocation Name and Directory Title should be similar. I hope this create doubt and hence should be mentioned on the portal as a note.

Thanks
