### ISSUE TITLE
Permissions does not continue from confirmation dialogue

### ISSUE THREAD

**Issue by gnuhc** [actions-on-google/actions-on-google-nodejs#176]
I've been trying to make the updated version of Permissions to work properly in my app but I'm running into some trouble.
 
I am using the example code in this section of the documentation: [Calling the Helper](https://developers.google.com/actions/assistant/helpers#calling_the_helper)
 
When I run the app in the simulator, and invoke 'ask_for_permissions_detailed', it asks me for my confirmation to access name and location info. However, when I say 'ok', it does not understand what I am saying. I've tried setting the proper contexts and set the event section of the intent correctly with action_intent_PERMISSIONS. It worked in my v1 version of dialogflow but it does not seem to work in v2. 
I also tried to use this actions on google example project to replicate the permissions: [Name Psychic](https://github.com/actions-on-google/dialogflow-name-psychic-nodejs)

Is this a bug?

Example dialogue in simulator:
<img width="407" alt="screen shot 2018-06-08 at 4 18 09 pm" src="https://user-images.githubusercontent.com/7096160/41370627-028dd83c-6efd-11e8-9abb-df4efbbb6be6.png">

**Comment by Canain** [comment]
The event should be `action_intent_PERMISSION` without a `S` instead of `action_intent_PERMISSIONS`.

Check out the [reference docs on the Permission class](https://actions-on-google.github.io/actions-on-google-nodejs/classes/conversation_question.permission.html) for more information.
