### ISSUE TITLE
TypeError: Cannot read property 'payload' of undefined due to POST with empty body

### ISSUE THREAD

**Issue by orcema** [actions-on-google/actions-on-google-nodejs#177]
I'm running both "actionssdk-smart-home-nodejs" [(https://github.com/actions-on-google/smart-home-nodejs)] and this "actions-on-google-nodejs" within the same express instance.

All works fine except account linking for the dialogflow application, but strangely the account linking for the smarthome works flawless.
According to error below it seems that the "assistant.ts" triggers the dialogflow.ts with an empty payload and this leads in the "conv.ts" to this exception:

> express.ts:44
    at getRequest (d:\DefaultInstall\UserData\nodejs\actionssdk-smart-home-nodejs\smart-home-provider\node_modules\actions-on-google\src\service\dialogflow\conv.ts:70:44)
    at new DialogflowConversation (d:\DefaultInstall\UserData\nodejs\actionssdk-smart-home-nodejs\smart-home-provider\node_modules\actions-on-google\src\service\dialogflow\conv.ts:187:16)
    at Function.<anonymous> (d:\DefaultInstall\UserData\nodejs\actionssdk-smart-home-nodejs\smart-home-provider\node_modules\actions-on-google\src\service\dialogflow\dialogflow.ts:409:16)
    at Generator.next (<anonymous>)
    at D:\DefaultInstall\UserData\nodejs\actionssdk-smart-home-nodejs\smart-home-provider\node_modules\actions-on-google\dist\service\dialogflow\dialogflow.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (D:\DefaultInstall\UserData\nodejs\actionssdk-smart-home-nodejs\smart-home-provider\node_modules\actions-on-google\dist\service\dialogflow\dialogflow.js:18:12)
    at Function.handler (D:\DefaultInstall\UserData\nodejs\actionssdk-smart-home-nodejs\smart-home-provider\node_modules\actions-on-google\dist\service\dialogflow\dialogflow.js:84:16)
    at Object.<anonymous> (d:\DefaultInstall\UserData\nodejs\actionssdk-smart-home-nodejs\smart-home-provider\node_modules\actions-on-google\src\assistant.ts:86:28)
    at Generator.next (<anonymous>)

My temporary workaround is to cancel the call to "dialogflow.ts" on line 82 in "assistant.ts" if the payload is empty.

> const standard: StandardHandler = async (body, headers) => {
    **if(body.responseId===undefined){
      return {} as StandardResponse
    }**
    const log = app.debug ? common.info : common.debug
    log('Request', common.stringify(body))
    log('Headers', common.stringify(headers))
    const response = await handler(body, headers)
    if (!response.headers) {
      response.headers = {}
    }
    response.headers['content-type'] = 'application/json; charset=utf-8'
    log('Response', common.stringify(response))
    return response
  }

Is this the correct way to avoid this error ?

**Comment by Canain** [comment]
Can you provide a code snippet of how you setup your express server listeners?

You should be able to intercept this before it hits the client library.

**Comment by orcema** [comment]
Within "smart-home-provider-cloud.js"

> function registerActionsOnGoogle(app) {
  actionsOnGoogleC.register(app,datastore);
}
registerGoogleHa(app);
registerAuth(app);
registerMqtt(app);
registerActionsOnGoogle(app);

Then a created a new module "actionsOnGoogle.js" with the content

> const actionsOnGoogle = {};
const bodyParser = require('body-parser');
const { dialogflow,actionssdk,Permission } = require('actions-on-google');

> actionsOnGoogle.register = function (gApp,dataStore) {
    const app = dialogflow();
    // add dialogflow app to express server on gApp
    gApp.use(app);

.....

> exports.register = actionsOnGoogle.register;

**Comment by Canain** [comment]
You should be able to change the line in `gApp.use(app)` to intercept the express request before it hits the library.

Something like
```
// add dialogflow app to express server on gApp
gApp.use((request, response) => {
  if (!request.body.responseId) { // check if the Actions on Google library should handle this
    return; // either pass to the next express handler or send a custom response with response.send
  }
  app(request, response); // if request is valid, just let the library handle it
});
```

**Comment by orcema** [comment]
Thanks for your suggestion.

I'm just wondering if this conditional handling of incoming express data stream wouldn't be more suitable to be handled inside the module itself ?
This would keep it's integration more simple.

If you agree i can setup a pull request  for "assistant.ts" file ?

**Comment by Canain** [comment]
Such a change can't be made just in `assistant.ts` as that's for a generic web framework not just express.

A possible feature request could be to adjust the express framework in `express.ts` so that if it can detect a invalid JSON body for a specific service, you can set an option to make it ignore and pass it on to the next handler. This will require a change to the service <-> web framework internal library API to have the service detect a invalid request body for the web framework handlers.

But as of now, there's no guaranteed generic way to have a way to detect if a response is valid for a specific service like Dialogflow, Actions SDK, or Smart Home. JSON body formats for services can change so detection based on existence of a property is not very stable. As far as the library is concerned with, a empty JSON object could be a valid request as there are defaults for all parts of the request data.

It's probably better to leave more advanced stuff like this to a case by case basis written by individual developers as everyone's use case is different.
