### ISSUE TITLE
Handle touch don't support multi Language such Thailand

### ISSUE THREAD

**Issue by t4eng** [actions-on-google/actions-on-google-nodejs#180]
I set items in Carousel, and set Event actions_intent_OPTION in dialogflow.
I want select items by handle touch, in simulator action on google use Language(Thailand) I try handle touch items not working for Thailand Language but good working when use English Language
I learn from https://developers.google.com/actions/assistant/responses#carousel
Is this a bug?
help me please.

**Comment by entertailion** [comment]
Please contact our support team with your issue: https://developers.google.com/actions/support/
