### ISSUE TITLE
No accessToken even after successful account linking

### ISSUE THREAD

**Issue by nishch** [actions-on-google/actions-on-google-nodejs#184]
I am using version 2.1.2 and Authorization code flow for account linking as specified in https://developers.google.com/actions/identity/oauth2-code-flow.

The entire flow works where my service does issue a valid accessToken and refreshToken to the google and I also get a confirmation in the assistant stating, "Great Nishant, your <bot name> account has been successfully linked with google". All fine so far.

Now the expectation is that after this point onward whenever I do invoke the bot again, I should get the same accessToken back in `conv.user.access.token` property, however this field remains empty. I have no idea what am I missing. I have setup dialogFlow integration with "Sign In required" during the invocation time.

Please help.

**Comment by nqd** [comment]
I am having the same problem with the request from Google Home.
```
{"user":{"userId":"xxx","locale":"en-US"},"conversation":{"conversationId":"xxx","type":"NEW"},"inputs": ...}]}
```

While the request from Web Simulator has accessToken as expected.

I am using Actions SDK.

Any suggestion would be highly appreciated.

Thanks.

**Comment by nqd** [comment]
@nishch have you find solution for this yet?

**Comment by Fleker** [comment]
Have you set up voice match on your Home?

**Comment by nqd** [comment]
Could you please elaborate on your comment? What is the voice match and where could I find it?

**Comment by Fleker** [comment]
In the settings for your Google Home, in the Google Assistant mobile app, there is going to be an option to identify yourself by voice. By default the user is considered anonymous.

**Comment by nqd** [comment]
Yes, it works now. The document should highlight this somewhere on the developer note :).

**Comment by lucaswadedavis** [comment]
Due to more than 3 months of inactivity, this issue is being closed. 

If you think the resolution is in error, please re-open the request with fresh information.
