### ISSUE TITLE
How to revoke access token in Action on Google SDK

### ISSUE THREAD

**Issue by JomaV** [actions-on-google/actions-on-google-nodejs#187]
Hi,
I want to revoke a token in a specific action returning a 401 error to the request (https://developers.google.com/actions/identity/oauth2-implicit-flow#revoke_tokens).
I have not found how to do it with the "action-on-google" SDK and I have tried to do it by adding a middleware in my app, checking if the action of the request is the expected action and finally sending a response with status 401 and the payload JSON. My code:

```
const app = express();
const assistant = dialogflow();     // Integration with dialogflow
...
app.use((req, res, next) => {
	console.log('Middleware!');
	if(req.body.queryResult.action === EXPECTED_ACTION) {
		const response = {
			"payload": {
				"google": {
					"expectUserResponse": false,
					"richResponse": {
						"items": [
							{
								"simpleResponse": {
									"textToSpeech": "Good bye and have a nice day!"
								}
							}
						]
					},
					"userStorage": "{\"data\":{}}"
				}
			}
		};
		res.status(401).send(response);
		return;
	}
	next();
});

app.use(bodyParser.json(), assistant);
```

Doing the `res.status(401).send(response);` the Google Assistant revokes the token but the app crashes and it does not show the SimpleResponse. If I change the status to 200 (success) the Google Assistant shows the SimpleResponse but it does not revokes the token.

Is there any method in "actions-on-google-nodejs" SDK to revoke the token or send a 401 error with a message?

Thanks

**Comment by kofeetokode** [comment]
Hello JomaV,
do you have a way to send a request to your token server to invalidate the refresh token?
[https://www.oauth.com/oauth2-servers/listing-authorizations/revoking-access/](url)

In the OAUTH 2.0 documentation, you should have a way for the users to invalidate their refresh token. Doing so, the access token will be invalidated after his lifespan and could not be refreshed.

I haven't found a way yet to ask google to revoke a token from an intent.

**Comment by anmolagar** [comment]
Any updates on this?
I am also looking for a way to revoke token from an intent.

**Comment by Canain** [comment]
Currently, there's not a way to send a 401 status in the library which right now is the way you can invalidate the token.

If you are using express, you can write a Express middleware to intercept cases where you want to invalidate the token and send a 401 status code before it gets to the library.

**Comment by florent33700** [comment]
I have the same problem, the application crashes when I return code 401. Would anyone have a solution to post a message before leaving?

**Comment by virajvg** [comment]
Hi,
Any updates on this issue, we are looking to send unauthorized from the library. 
Also as mentioned above the app crashes when we return it from the middleware.

**Comment by Canain** [comment]
Now with [`2.6.0`](https://github.com/actions-on-google/actions-on-google-nodejs/releases/tag/v2.6.0) in 7fb220d6c5d7e5ce3b61c7bccbeccbc2d73915d2, we added support for returning a HTTP 401 status code by throwing a customized error:

```javascript
const { dialogflow, UnauthorizedError } = require('actions-on-google')

const app = dialogflow()

// If using Actions SDK:
// const app = actionssdk()

app.intent('intent', conv => {
  // ...

  // given a function to check if a user auth is still valid
  const valid = checkUserAuthValid(conv)
  if (!valid) {
    throw new UnauthorizedError()
  }

  // ...
})
```

This should allow you to respond with this and invalidate the token.

Let us know if you have any issues.

**Comment by florent33700** [comment]
The UnauthorizedError exception does not seem to clear the access token anymore. However, It worked however.

**Comment by florent33700** [comment]
I contacted the support who refuses to fix their UnauthorizedError exception implementation !
Here is the solution they propose and that I do not understand:

> As you have implemented Implicit Flow OAuth account linking, what you can do is send a request to the authorization URL with a state parameter that has a different value. Since it cannot be verified by the authorization server, it will ask the user to sign in again. Please note that your OAuth implement must handle the error accordingly.
