### ISSUE TITLE
TransactionDecision does not seem to continue conversation on device

### ISSUE THREAD

**Issue by gla5001** [actions-on-google/actions-on-google-nodejs#189]
Im trying to create a assistant app using transactions with a Google provided payment instrument and dialogflow. The transaction and app successfully completes when using both the sandbox payment key (in sandbox mode) and live payment (in non-sandboxed mode) on simulator and assistant app on phone, but fails to complete on a an actual device (google home or google home mini). Once the cloud function sends off the TransactionDecision conversation ask, the app just seems to fall over. It shows the order card in the assistant app but then the device stops the action. It like is looses the session when trying to  'place order' with the transaction decision. There are no errors in the logs. The last thing in the logs is the response to send the TransactionDecision intent.

```
"Response {
  "status": 200,
  "headers": {
    "content-type": "application/json; charset=utf-8"
  },
  "body": {
    "payload": {
      "google": {
        "expectUserResponse": true,
        "richResponse": {
          "items": [
            {
              "simpleResponse": {
                "textToSpeech": "PLACEHOLDER"
              }
            }
          ]
        },
        "userStorage": "{\"data\":{}}",
        "systemIntent": {
          "intent": "actions.intent.TRANSACTION_DECISION",
          "data": {
            "@type": "type.googleapis.com/google.actions.v2.TransactionDecisionValueSpec",
            "orderOptions": {
              "requestDeliveryAddress": false
            },
            "paymentOptions": {
              "googleProvidedOptions": {
                "prepaidCardDisallowed": false,
                "supportedCardNetworks": [
                  "AMEX",
                  "DISCOVER",
                  "MASTERCARD",
                  "VISA"
                ],
                "tokenizationParameters": {
                  "parameters": {
                    "gateway": "stripe",
                    "stripe:publishableKey": "******* stripe test key ******",
                    "stripe:version": "******* stripe version ******"
                  },
                  "tokenizationType": "PAYMENT_GATEWAY"
                }
              }
            },
            "proposedOrder": {
              "id": "generated unique id"
              "cart": {
                "merchant": {
                  "id": "merchant id",
                  "name": "merchant name"
                },
                "lineItems": [
                  {
                    "name": "item 1",
                    "id": "item id",
                    "price": {
                      "amount": {
                        "currencyCode": "USD",
                        "nanos": 0,
                        "units": 12
                      },
                      "type": "ACTUAL"
                    },
                    "quantity": 1,
                    "subLines": [
                      {
                        "note": "foo bar"
                      }
                    ],
                    "type": "REGULAR"
                  }
                ],
                "notes": "2018-06-23T17:20:23-05:00",
                "otherItems": [
                  {
                    "name": "Subtotal",
                    "id": "subtotal",
                    "price": {
                      "amount": {
                        "currencyCode": "USD",
                        "nanos": 0,
                        "units": 12
                      },
                      "type": "ESTIMATE"
                    },
                    "type": "SUBTOTAL"
                  },
                  {
                    "name": "Fee",
                    "id": "fee",
                    "price": {
                      "amount": {
                        "currencyCode": "USD",
                        "nanos": 0,
                        "units": 1
                      },
                      "type": "ESTIMATE"
                    },
                    "type": "FEE"
                  },
                  {
                    "name": "Tax",
                    "id": "tax",
                    "price": {
                      "amount": {
                        "currencyCode": "USD",
                        "nanos": 0,
                        "units": 0
                      },
                      "type": "ESTIMATE"
                    },
                    "type": "TAX"
                  }
                ]
              },
              "otherItems": [],
              "totalPrice": {
                "amount": {
                  "currencyCode": "USD",
                  "nanos": 0,
                  "units": 13
                },
                "type": "ESTIMATE"
              }
            }
          }
        }
      }
    },
    "outputContexts": [
      {
        "name": "projects/project-id/agent/sessions/*************/contexts/_actions_on_google",
        "lifespanCount": 99,
        "parameters": {
          "data": "{}"
        }
      }
    ]
  }
}" 
```

Has anybody else experienced this or know how to handle it? Is this a bug?

**Comment by cwdcwd** [comment]
@Fleker I saw your comment on #213 and I believe that should be the case here right and on #202 ? the conversation should switch to the mobile device? Any idea why the conversation dies off? 
We're working on an an app that makes purchases but currently blocked since it dies off once the order summary shows up on the phone.

**Comment by Fleker** [comment]
I don't know why the conversation dies off. I'd suggest filling out the [support form](https://developers.google.com/actions/support/).

**Comment by cwdcwd** [comment]
Hey @Fleker I did in fact fill one out but no one responded to me. I don't seem to be the only person having this and similar issues. 
Is there an example app out there that performs transactions that one could emulate?

**Comment by Fleker** [comment]
There is the [dialogflow-transactions-nodejs](https://github.com/actions-on-google/dialogflow-transactions-nodejs) sample that you can consult for additional guidance.

**Comment by cwdcwd** [comment]
hey @Fleker so I've set up that sample app and I'm actually seeing the same behavior there. Works great on the phone but just stops on the mini. It never seems to get a `transaction_decision_complete`  and just stops dead. Any ideas?

**Comment by Fleker** [comment]
I don't think transactions work on smart speakers right now, just things with displays

**Comment by cwdcwd** [comment]
That's unfortunate if that's the case. What's odd is that in our app we were able to send the order summary out to the phone from the speaker device for the user to confirm there but then it died there. 
Any reason why speakers are not supported currently?

**Comment by Fleker** [comment]
I'm not really sure either way. I think your best bet is to look at the [troubleshooting doc](https://developers.google.com/actions/transactions/troubleshooting or reach out [to support](https://developers.google.com/actions/support/) again.

**Comment by cwdcwd** [comment]
Thanks @Fleker !! That "No response during purchase authorization" seems to help move the ball forward. Posting a SimpleResponse along with the order seems to have transferred the conversation flow properly to the phone from the device. 
Facing some SignIn issues where it silently fails the first time but works the next time now but that's not related to this ticket I think. Many thanks again!

**Comment by Canain** [comment]
This seems to be resolve, if not, feel free to reopen the issue.

It seems like from the original issue that there is an issue on the platform side, but only logs for the library have been shared. In the future, make sure to check logs on the platform side too from the simulator tabs.
