### ISSUE TITLE
Sign in experience on speaker device

### ISSUE THREAD

**Issue by sriprabha** [actions-on-google/actions-on-google-nodejs#190]
I have enabled account linking using OAuth for my action using the sign in helper - `conv.ask(new SignIn());`
It works as expected when I use the simulator, that is, on the simulator I enable speaker device mode, and it presents a msg that I provided in the handler for `actions.intent.SIGN_IN`, to direct the user to the phone to complete account linking.
And when I enable the phone mode on simulator, the account linking process works perfectly as expected.

When I try the same flows on an actual google home device, I have been seeing different kinds of responses over the last week. Initially, it presented a reply "Sorry, something went wrong" followed by my custom msg asking the user to complete the process on the phone", and starting today I see that it reaches the line of code - `conv.ask(new SignIn());`, and then fails internally and presents a response to the user "Sorry, I can't help with that". It does not reach my handler for `actions.intent.SIGN_IN` anymore where I have setup the custom response  if `signin.status` is not OK.

What is the expected behavior of sign in using OAuth on Google home devices? The docs here https://developers.google.com/actions/identity/account-linking does not provide the details around how to handle the support for speaker devices.

**Comment by kofeetokode** [comment]
Hello sriprabha,
When you configured your google home, have you enabled localization for the assistant?

Which version of the Action on google library are you using & what is the payload that is returned once the `conv.ask(new SignIn())` is reached?

**Comment by cwdcwd** [comment]
I've experienced that as well as #189 on device. my stuff works great in sim and on phone but when it comes to the device I'm having issues like these

**Comment by sriprabha** [comment]
@kofeetokode Running 2.1.3 version, and the sign-in status in the payload is set to ERROR

**Comment by smishra2** [comment]
Hi @sriprabha, the `actions.intent.SIGN_IN` intent doesn't work on speaker devices if using traditional OAuth (you can check your Linking type in the [Actions Console](console.actions.google.com) Account linking page for your project). You have a couple options here:

1) Use [Google Sign-in for the Assistant](https://developers.google.com/actions/identity/google-sign-in). This will allow the `actions.intent.SIGN_IN` intent to work on both speaker and screen devices.

2) If you want to keep using traditional OAuth with your own server, then before invoking the `actions.intent.SIGN_IN` intent, [first check whether the user is on a screen device](https://developers.google.com/actions/assistant/surface-capabilities#multi-surface_conversations). If not, use the `actions.intent.NEW_SURFACE` intent to request them to move to a screen device, where you can have them sign in as you are doing above.

Note: If you're Action Package (or Dialogflow/Google Assistant Integration settings) requires sign in for some intent, I believe that will work on any device as well. This is different from the `actions.intent.SIGN_IN` intent, as it requires the user to sign in before even starting the dialog with your Action.

**Comment by sriprabha** [comment]
Thanks @smishra2 , Regarding 
> `If you're Action Package (or Dialogflow/Google Assistant Integration settings) requires sign in for some intent, I believe that will work on any device as well.`

How do we specify `sign in` required for an intent using Actions package (without Dialog Flow) ? I don't see this option available on the Actions console. 
It will be great to find all of the above information on the online documentation.

**Comment by sriprabha** [comment]
@smishra2 Are you referring to the flag `signInRequired` in the actions package - https://developers.google.com/actions/reference/rest/Shared.Types/Action to identify what intents require sign in? And this is different from using the sign in helper `new SignIn()`

**Comment by smishra2** [comment]
Hey there, sorry for the delayed response. Yes I am referring to the [`signInRequired`](https://developers.google.com/actions/reference/rest/Shared.Types/Action) flag in the Action Package. 

The difference between that and the `new SignIn()` helper is that the first one ([`signInRequired`](https://developers.google.com/actions/reference/rest/Shared.Types/Action)) requires that the user sign in BEFORE being able to engage in a dialog with the Action. In other words, when they say, "Hey Google, talk to X", Google will first check if they've signed in before even making a request to the webhook of the Action. If they have not signed in, they will be given an opportunity to do so. On the other hand, the `new SignIn()` helper allows the user to engage with the Action, and then sign in during the dialog (whenever the user calls the helper). In this case, the developer would not have specified `signInRequired: true` for the intent used to invoke the Action.

**Comment by sriprabha** [comment]
Thanks for the clarification @smishra2

**Comment by OpenDog** [comment]
@smishra2 Something's wrong with the ``conv.ask(new SignIn())``

I have put together a [little test here](https://github.com/OpenDog/aog-sign-in-test) to show you what I'm doing. I have also included the log. 

The project is setup with account linking to my oauth page (implicit oauth). I believe I'm doing exactly what you recommended above in option 2. I send the user to the phone and when the OK comes (surface change) I send out the SignIn. I expect at this point the account linking card to show up with my oath link in it. Instead I get an immediate OK for (sign in status). It behaves like I'm linked already (but no token in the payload).

By the way I also tried the sigInRequired flag in the action.json (with the BeerLinks action) and nothing happened. The intent came down without G showing me the link card.

**Comment by ekeitho** [comment]
I too was going through my authentication flow and thinking it worked, but kept getting "Sorry, something went wrong..." However, I found a small workaround in which I have to do **every time** I redeploy to my functions.

Instead of going through the flow on the phone, I used this https://gala-demo.appspot.com/app to authenticate my flow. Then, I launch my actions again and I have the access token I want.

**Comment by Canain** [comment]
@OpenDog Are you sure you don't get a token? Because it should mean it is already signed in then which then it'll have the token.

Can you provide more logs for that?

**Comment by Canain** [comment]
Closing since there hasn't been more discussion.

**Comment by sedhalgetstartedspace** [comment]
new Signin() not working on speaker(google home mini)
