### ISSUE TITLE
Output Context not working when using Rich Responses

### ISSUE THREAD

**Issue by HoklaiSung** [actions-on-google/actions-on-google-nodejs#191]
So I got my basic intents setup with the actions on google client library on AWS lambda. My app does some basic order inquiry and allows followup questions on resulting orders through the use of contexts. All of this was working fine. I recently added several rich response elements to the app, namely the basic card and the list, and they are also working, however, my output contexts aren't being received anymore. (The responses received by the simulator and other devices lack the output context section)

## Steps Taken
* I've taken a look at the responses from the actions on google simulator and they did not receive output context
* Checked the logs from Google Cloud Platform and they also have not received output contexts
* However, when I send in a test query to my Lambda expression or API Gateway, I receive the full response, simple responses, rich responses, output context and all.
* Not surprisingly, my own mocha test cases also get the full contexts.

## Thoughts
So it seems clear to me that something on the dialogflow end is cutting out my output contexts since I know for sure that all components of my intents work separately. I am wondering if this is intended behavior, that webhook responses cant provide both output contexts and rich responses. If this is intended behavior, then I can probably work around it using the user storage, but if it is not, I'd appreciate any help I can get looking into the issue.

**Comment by lucaswadedavis** [comment]
I'm sorry HoklaiSung, I'm not exactly sure what the issue you're reporting is. It sounds like maybe the responses in the Web Simulator don't have the context included, but that your webhook always gets it. In that case, what's the actual problem?

**Comment by HoklaiSung** [comment]
I was able to fix a seperate problem that got the intents that used output contexts working again. 

My problem originally was that these intents that rely on output contexts were not working, and I didn't see any output contexts in Actions on Google's Simulator's request or response logs, so I assumed that was where the problem lay. I will say, it does look like the simulator does not show that information regardless(the recieved output context nor the output context being sent to followup intents), and that would be useful to see.

**Comment by lucaswadedavis** [comment]
Thanks for surfacing this.
