### ISSUE TITLE
Conversation.user.storage does not update across conversations

### ISSUE THREAD

**Issue by hliejun** [actions-on-google/actions-on-google-nodejs#192]
Following the [Actions on Google documentation](https://developers.google.com/actions/assistant/save-data) regarding saving and clearing data across conversations, I tried to update the values set at `Conversation.user.storage` to persist a set of parameters for future use:

```node
const app = dialogflow({debug: true});

var myIntentHandler = (conv, params) => {
  conv.user.storage.myKey = params;
  conv.ask(`Ok. I have bookmarked your query so you can access it via "favourite".`);
};

app.intent('dialogflow_intent_name', myIntentHandler);
```

My implementation seems similar to the example given in the [nodejs guide](https://actions-on-google.github.io/actions-on-google-nodejs/classes/conversation.user.html#storage). Doing so changes the `user.storage.myKey` value within the conversation, but in my case the change did not persist after leaving for a new conversation session (saying 'cancel' after the response and re-invoking my assistant app). I have also tried to set it to an empty object as proposed in the documentation, but it didn't clear the storage across conversation too:

```node
const app = dialogflow({debug: true});

var myIntentHandler = (conv, params) => {
  conv.user.storage = {};
  conv.ask(`Ok. I have cleared your query from favourite.`);
};

app.intent('dialogflow_intent_name', myIntentHandler);
```

Is this expected or have I missed out something in my approach? Thanks.

**Comment by Canain** [comment]
Hi, take a look at the section on that doc about [User storage expiration](https://developers.google.com/actions/assistant/save-data#user_storage_expiration).

There are cases when userStorage cannot be persisted across conversations like
* When voice match is set up and there is no match.
* When the user disabled personal data.

For a more permanent and reliable storage of user data, you should perform [account linking](https://developers.google.com/actions/identity/) which has been made easy with [Google Sign-In for the Google Assistant](https://developers.google.com/actions/identity/google-sign-in) (currently in developer preview). This way, you can store user data in a database you control and associate it with a user on the Google Assistant.

**Comment by hliejun** [comment]
@canain Thanks for pointing to account linking and Google Sign-In. Will try that out instead!

**Comment by bruriah1999** [comment]
i am having the same problem the account linking isn't working for me. doe's anybody know another way to solve it?
