### ISSUE TITLE
Location helper - DEVICE_PRECISE_LOCATION

### ISSUE THREAD

**Issue by kofeetokode** [actions-on-google/actions-on-google-nodejs#193]
Hello,
When I ask the permission for DEVICE_PRECISE_LOCATION, actions on google tell the user 
> I'll just need to get your street address from Google. Is that ok?

When a user is on a cellphone/tablet device with localization enabled, is there a way for AOG to ask the user something like :
> I'll just need to get your GPS position from your device. Is that ok?

I believe that this would be more accurate. I have the same need for the French language.
Thanks!

**Comment by Fleker** [comment]
There is no way to customize this message.

**Comment by kofeetokode** [comment]
Is there a way to have the message changed since it doesn't really get the GPS position from Google.

The permission that I asked for is for "**DEVICE**_PRECISE_LOCATION", I would expect it to get it from the device and not from Google. Am I missing something?

Thanks!

**Comment by kofeetokode** [comment]
Hello,
Is there a way to ask for a text change directly to AOG cooncerning my request?

Thanks!

**Comment by Fleker** [comment]
I've filed a feature request for this internally.

**Comment by kofeetokode** [comment]
Thanks!
