### ISSUE TITLE
asking for permission with UpdatePermission

### ISSUE THREAD

**Issue by MatthewLo** [actions-on-google/actions-on-google-nodejs#194]
conv.ask(new UpdatePermission({intent: 'send_notifs'})); I am trying to use UpdatePermission to ask the user for permission to send push notifications.
The very first time I triggered the Update Permission, it worked fine and I was able to give it permission. 
However, I want to be able to test the flow. Is there any way to revoke permissions? It seems like every time I trigger the intent, it skips asking for permissions.
I've tried setting conv.user.permissions value to null, but it doesn't seem to be resolving the issue.

**Comment by martenhc** [comment]
Hello Matthew, did you figure out how to remove the update permission? Could you kindly share your findings?

**Comment by ekeitho** [comment]
i also have this problem with regular Permissions vs UpdatePermissions. say for example, a user denies giving us their device_course_location on accident and would like to grant it the next time.

**Comment by Canain** [comment]
On the user side, if they visit the Action on the [Actions directory](https://developers.google.com/actions/distribute/directory) using a phone, there should be a button to `Reset app`.

That should clear any user data. I'm not sure if it works with permission denial, but you can try it and see if it works.

**Comment by MatthewLo** [comment]
Hey marten, if the user goes into their Assistant app and says “stop sending updates from <your-action-name>, their updates permission will be removed.

**Comment by martenhc** [comment]
Thanks guys, I was able to remove the permissions from a Google Home device as Matthew suggested. I asked "Hey Google, stop sending updates from {app display name}". 
So, for now we aren't able to remove permissions from the AoG web simulator, right? since, as stated in the error it logs when you try to do so, "In the simulator, you are only able to invoke actions that you have added to your app."
