### ISSUE TITLE
Response from dialogflow does not come to google assistant

### ISSUE THREAD

**Issue by Mindtraveller** [actions-on-google/actions-on-google-nodejs#195]
Hi,

Sometimes google assistant does not answer me even though I receive correct response from the fulfillment. That happens only when I use voice command, by using keyboard it always works fine.

What I receive instead of the response:
![issue](https://user-images.githubusercontent.com/11229620/42380106-73138a8a-8135-11e8-96d4-aabce98bba7e.gif)
It's just 'thinking'.

After using `conv.close('You've punched-in into demo as Jack');`, in DialogFlow history I can see following response:
```
{
  "queryText": "Jack",
  "fulfillmentMessages": [
    {
      "text": {
        "text": [
          "[{\"type\":0,\"speech\":\"\"}]"
        ]
      }
    }
  ],
  "webhookPayload": {
    "google": {
      "userStorage": "{\"data\":{}}",
      "richResponse": {
        "items": [
          {
            "simpleResponse": {
              "textToSpeech": "You've punched-in into demo as Jack"
            }
          }
        ]
      },
      "expectUserResponse": false
    }
  },
  "outputContexts": [
    {
      "name": "_actions_on_google",
      "lifespanCount": 99,
      "parameters": {
        "data": "{\"company\":\"demo\",\"username\":\"Jack\"}"
      }
    },
    {
      "name": "punch-in-followup",
      "lifespanCount": 2,
      "parameters": {
        "company.original": "demo",
        "company": "demo",
        "username.original": "Jack",
        "username": "Jack"
      }
    },
    {
      "name": "company",
      "lifespanCount": 5,
      "parameters": {
        "data": {
          "value": "demo"
        }
      }
    },
    {
      "name": "username",
      "lifespanCount": 5,
      "parameters": {
        "data": {
          "value": "Jack"
        }
      }
    }
  ],
  "intent": {
    "id": "96f93154-0ae4-4bb4-91c3-c1b796d7cda3",
    "displayName": "punch-in"
  },
  "intentDetectionConfidence": 1,
  "languageCode": "en"
}
```
The response seems to be correct. 
Perhaps only `fulfillmentText` property is missing and `speech` is empty in `fulfillmentMessages`:
```
"fulfillmentMessages": [
    {
      "text": {
        "text": [
          "[{\"type\":0,\"speech\":\"\"}]"
        ]
      }
    }
  ],
```
Does any one experienced such issue?

Noticed on Galaxy S7, Android 6.0.1. 
actions-on-google v.2.2.0

**Comment by Canain** [comment]
Can you still reproduce this issue?

**Comment by Mindtraveller** [comment]
> Can you still reproduce this issue?

Yes, I can. 
I contacted AoG support, but still have not received final outcome.
Do you also experience such issue?

**Comment by ruudschuurmans** [comment]
We're facing the same issue. I've noticed it only happens in the assistant on Android. It does always work on the Google Home.

**Comment by Mindtraveller** [comment]
Just received a reply from Support team and verified on my device -- it seems to be working fine now. 
Closing the issue.
