### ISSUE TITLE
App working on web simulator but not on google home device

### ISSUE THREAD

**Issue by gargdevesh6** [actions-on-google/actions-on-google-nodejs#197]
Created a custom google application on google actions console(using Dialogflow). Working perfectly fine on the web simulator and google assistant application on my phone but not responding on the google home device. I have signed in the google home device with the same Gmail ID as in the actions console and Dialogflow.

Any Ideas?

**Comment by cwdcwd** [comment]
I've had this problem before myself. I had to log out all my accounts from the app and factory reset the device to get it to work.

**Comment by gargdevesh6** [comment]
Thanks, It worked for me also.
The reason is Google home device and the android phone which is used to configure the device were not connected with the same wifi which is a precondition to get it work. I suggest if the Google home device is configured by someone else before, then you should factory reset it by pressing the voice mute button on the google home device for sometime and then reconfigure it again from the mobile.
Thanks
