### ISSUE TITLE
TypeScript declarations

### ISSUE THREAD

**Issue by MattJeanes** [actions-on-google/actions-on-google-nodejs#2]
Would you guys be willing to either create/accept via pull req a TypeScript declarations file? It would involve creating a TypeScript declaration file and then adding a 'types' reference to it in package.json.

https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

Thanks!

**Comment by gustavo-moreira** [comment]
This is definitely an option, but for now we will keep it as it is since we will have to validate the library with TypeScript as well, to make sure things are working correctly.
I will leave this open until we add a feature request on our side.
Tks.

**Comment by anandnimkar** [comment]
Hello. Is there any update on this? What would be the impact if someone else just submitted the type definitions to DefinitelyTyped?

**Comment by pilwon** [comment]
Check out my TypeScript fork (latest version, v1.1.1) of this library: [npm](https://www.npmjs.com/package/actions-on-google-ts), [src](https://github.com/pilwon/node-actions-on-google-ts/tree/ts/ts)

    $ npm install actions-on-google-ts

    import { ApiAiApp, RequestHandler } from 'actions-on-google-ts';

    const app = new ApiAiApp({request, response});
    const actionMap = new Map<string, RequestHandler>();
    ...
    app.handleRequest(actionMap);

**Comment by pilwon** [comment]
Updated package to support v1.2.1: `npm install actions-on-google-ts`

@smishra2 @entertailion @Canain @silvolu The TypeScript declarations files are complete and they cover 100% of exported modules. Would you guys be interested in brining these into this repo if I submit a PR?

**Comment by silvolu** [comment]
@pilwon thanks for the job you've done to allow developers to use our client library with TypeScript!
Thanks for your offer, but we still can't commit to maintaining TypeScript as well.
Keeping this open to track the request.

**Comment by joelhegg** [comment]
@pilwon Rather than continuing to maintain a fork, have you thought about contributing just the type definition to http://definitelytyped.org/? Typescript developers expect to be able to do `npm install @types/actions-on-google`.

**Comment by joelhegg** [comment]
I ran into some issues with @pilwon's fork not being up to date with this package. To make this more maintainable I went ahead submitted it as DefinitelyTyped/DefinitelyTyped#20303. This is updated to the 1.4 version of this package and aligns with DefinitelyTyped's standards.

**Comment by Thomas-P** [comment]
@joelhegg @pilwon Nice work. Hopefully it will merge soon.

**Comment by joelhegg** [comment]
Can somebody from Google comment on DefinitelyTyped/DefinitelyTyped#20303. They have concerns because their package is under the MIT license and this one is under the Apache v2 license. They're both permissive and should be compatible. 80% what's in there is the jsdoc from this package though, so they're being cautious about proceeding without sign off.

**Comment by silvolu** [comment]
@joelhegg from what I've seen the pull request that you have submitted doesn't contain any files authored by us, so we have no claims on them. You can strip the headers and change the license, although you should probably check with @pilwon as it looks like your work is based off what he's done. For the jsdoc comments, as you mentioned you can attribute them to our docs released under CC, adding a NOTICE similar to the one you point to in your comments.

As @Thomas-P commented on the DefinitelyTyped pull request, in a repo like @pilwon's fork where you have some files authored by us and some not, you can change the license for the files you authored, you'd only need to keep our headers in the file authored by us, a copy of the apache license in the repo (as per point 4a of the license), notices for files authored by us that you have changed.

Hope this helps!

**Comment by silvolu** [comment]
And when I said "our docs released under CC" I meant https://developers.google.com/actions/reference/nodejs/AssistantApp :)

**Comment by joelhegg** [comment]
Thanks @silvolu I'll update DefinitelyTyped/DefinitelyTyped#20303 accordingly.

**Comment by malikasinger1** [comment]
1+

**Comment by joelhegg** [comment]
DefinitelyType merged this contribution. You can use it by doing either `yarn add @types/actions-on-google -D` or `npm install @types/actions-on-google -D`.

**Comment by entertailion** [comment]
Based on your feedback, we have just launched a new version of the AoG client library: https://medium.com/@silvano.luciani/actions-on-google-client-library-for-node-js-v2-0-0-alpha-c92361167f15

**Comment by pilwon** [comment]
@entertailion This is great update. Thanks for natively supporting TypeScript!

**Comment by Canain** [comment]
Thank you guys so much for the support and work on this for our library!

Since the original issue has been resolved which is [TypeScript definitions](https://www.npmjs.com/package/@types/actions-on-google) for v1 of the library submitted by you guys, we're going to close this issue for now.

Since the [v2 of the library](medium.com/@silvano.luciani/actions-on-google-client-library-for-node-js-v2-0-0-alpha-c92361167f15) is written in TypeScript and is currently in the alpha phase, please feel free to open any issues about TypeScript for that so we can polish it during the alpha.

We want to create the best experience for both JavaScript and now TypeScript developers using our library!
