### ISSUE TITLE
Yes intents with permission requests

### ISSUE THREAD

**Issue by OpenDog** [actions-on-google/actions-on-google-nodejs#20]
If I have a legit "Yes" intent, API.AI will mistake the "Yes" for the permission grant's "yes" and send a "Yes" intent to me when it sends the permission result back. But when you don't have a "Yes" intent, you can use a fallback intent and a context to send yourself a "PERMISSION" intent. Wouldn't it be simpler if we exposed the original intent (assistant.intent.action.PERMISSION in this case) or just a boolean function, that says it's a permission grant response?

**Comment by smishra2** [comment]
Hi @OpenDog! That's a fair point. Right now the API is limited so we can't do that, but you can try using contexts to ensure that your legit "Yes" intent is not triggered during the permission fallback. That is, make sure your permission fallback intent and your legit "Yes" intent accept different input contexts.
