### ISSUE TITLE
No user response

### ISSUE THREAD

**Issue by KoffeeToKode** [actions-on-google/actions-on-google-nodejs#200]
Hello,
If I add 2 simple responses
```
'Response X.';
'Question X?';
```

and the user doesn't provide any input, the built-in reprompt will say something like :

> I didn't get that.
> Response X.

Instead of :
> I didn't get that.
> Response X.
> Question X ?

As soon as I create an intent with the **actions_intent_NO_INPUT** event in Dialogflow for a **specific** input context, I will have the following response for all of my intents no matter the input context :
> I didn't get that.

Any ideas on how I could have this when the user doesn't provide any input :
> I didn't get that.
> Question X ?

or this : 
> I didn't get that.
> Response X.
> Question X ?

**Comment by Canain** [comment]
You might not have had the Dialogflow contexts set up correctly.

Can you provide more details about how the contexts and fulfillment is set up?

This question might be better suited for StackOverflow unless you find a issue with the library.

**Comment by Canain** [comment]
Closing since there hasn't been more discussion.
