### ISSUE TITLE
Actions SDK - How to trigger custom intents and multiple conversation fulfillments from conversation

### ISSUE THREAD

**Issue by 5amuraix** [actions-on-google/actions-on-google-nodejs#201]
Hello,

As I understand it, when using the Actions SDK, you can specify custom intents and multiple conversation fulfillments in the Action Package JSON.   However, these custom intents are only used at first explicit invocation (e.g. "Ok google talk to myaction and do something")  and are not triggered at all if a user is in conversation with the action (i.e. whereby all incoming requests will be of the actions.intents.TEXT built-in intent).

If I have the following Actions Package JSON snippet:

` "actions": [
    {
      "description": "Default main start intent",
      "name": "MAIN",
      "fulfillment": {
        "conversationName": "someServer"
      },
      "intent": {
        "name": "actions.intent.MAIN",
        "trigger": {
          "queryPatterns": [
            "talk to myaction"
          ]
        }
      }
    },
	{
      "name": "do_something",
      "intent": {
        "name": "do_something",
        "trigger": {
          "queryPatterns": [
            "open something",
            "run something",
	    "start something"
          ]
        }
      },
      "fulfillment": {
        "conversationName": "someServer"
      }
    },
	{
      "name": "do_something_else",
      "intent": {
        "name": "do_something_else",
        "trigger": {
          "queryPatterns": [
            "launch something else"
          ]
        }
      },
      "fulfillment": {
        "conversationName": "differentServer"
      }
    }
  ],
  "conversations": {
    "someServer": {
      "name": "someServer",
      "url": "https://someServer.some.url",
	  "fulfillmentApiVersion": 2
    }, 
	"differentServer": {
      "name": "differentServer",
      "url": "https://anotherserver.url",
	  "fulfillmentApiVersion": 2
    }
  }`

1)  Is there a way to trigger the custom intents (do_something,  do_something_else) other than from first invocation?

2)  If not, am I expected to route to differentServer/someServer from the fulfillment server side?  

3) What fulfillment is chosen by default for action.intent.Text and can I specify a default?

Example scenario:  
     - User entered into conversation with myaction ("Ok google, talk to myaction").  Actions sends to someServer fulfillment.
     - User says "launch something else".  From my someServer fulfillment, I process this request as connection to differentServer fulfillment to handle.  
    - User says "open something".   Will this request start at the someServer fulfillment server?

Thank you

**Comment by montanaflynn** [comment]
I have the same questions.
