### ISSUE TITLE
Does context parameter for Permission() support SSML?

### ISSUE THREAD

**Issue by codeledger** [actions-on-google/actions-on-google-nodejs#204]
I'm using the provided Permission mechanism show in the examples like:

> const {
>   dialogflow,
>   Permission,
> } = require('actions-on-google');
> ...
>   conv.ask(new Permission({
>     context: responses.permissionReason,
>     permissions: conv.data.requestedPermission,
>   }));
> ...

where response.permissionReason is the text that would explain why the app needs permissions and I noticed that the string used for `context` doesn't support SSML.

Attempts at the string containing `Reason for permission<break time='500ms'/> more text` will result in text showing/read out in online simulator.

Not sure if this is a SDK limitation or something deeper.

**Comment by Canain** [comment]
Hi, the library just generates the JSON object for [`PermissionValueSpec`](https://developers.google.com/actions/reference/rest/Shared.Types/PermissionValueSpec) putting the `context` parameter into `optContext` directly.

If it doesn't work on the simulator or on an actual device, then it might not be supported by the platform.

**Comment by codeledger** [comment]
Just tried `permission <break time='500ms'/>request` and `<speak>permission <break time='500ms'/>request</speak>` and on device the `<speak>` markup characters were printed in the speech bubble and read aloud. So this feature doesn't appear supported. 

Thanks for reply, I'll put in a feature request here:
https://developers.google.com/actions/support/

**Comment by theGirrafish** [comment]
Any update on this? I'm trying to use SSML to interpret a date but instead it speaks out the tags. It works in the simulator though. Seems like any Action using `context` doesn't support SSML.
I setup my action like so:
```javascript
conv.ask(new NewSurface({
  context: `<speak>Perfect, you're all set! I created your appointment for<say-as interpret-as="time" format="hm12">9:00:00 PM</say-as> on <say-as interpret-as="date" format="mdy">03/20/2019</say-as>.`,
  notification: "New event",
  capabilities: ["actions.capability.SCREEN_OUTPUT"]
}));

It'd be a really useful feature to have!
