### ISSUE TITLE
'final_response' must be set. 

### ISSUE THREAD

**Issue by vaibhavkumar049** [actions-on-google/actions-on-google-nodejs#205]
I am making one simple application but it is saying 'final_response' must be set. I am giving you the webhook code and tell me if you find any error 
`'use strict'

const {dialogflow}=require('actions-on-google');
const functions = require('firebase-functions');
const d=require('date-and-time');
const app=dialogflow({debug : true });
let date = new Date();

app.intent('what should',(conv,{Work})=>{
  console.log(Work);
  //if(Work ==== 'do'){
 if(d.format(date,'ddd')==='Mon' && d.format(date,'hh:mm')==='09:00'){
   conv.close("You have a class of Microprocessor in ICT 308 ,You can go a bit late.");
 }
 if(d.format(date,'ddd')==='Thu' && d.format(date,'hh:mm')==='09:00'){
   conv.close("You have a class of Microprocessor in ICT 308 ,You can go a bit late.");
 }
 else {
   conv.close("You should be sleeping now");

 }
// }
//  else{
//    conv.close("i could not understood");
//  }

conv.close('good night');

});

exports.dialogflowFirebaseFulfillment = functions.https.onRequest(app); `

**Comment by Fleker** [comment]
Have you enabled fulfillment in your Dialogflow intent?

**Comment by vaibhavkumar049** [comment]
I finally solved this issue thanks

**Comment by edWAR6** [comment]
> I finally solved this issue thanks

How? Come on...
