### ISSUE TITLE
account linking flow issue

### ISSUE THREAD

**Issue by ekeitho** [actions-on-google/actions-on-google-nodejs#208]
Expected: Go through auth flow on a device and get back signin.status 'OK'.
Actual: Go through entire auth flow and get "Sorry, something went wrong..." each time.

I went through the auth flow on the device thinking everything worked, but I just kept getting this error. However, I found a small workaround in which I have to do **every time** I redeploy to my functions.

Instead of going through the flow on the phone, I use this https://gala-demo.appspot.com/app to authenticate my flow. Then, I launch my actions again and I have the access token I want.

I am using SignIn() and the correct intents, so not sure what I am doing wrong.

**Comment by Canain** [comment]
Can you provide more code and debugging information? StackOverflow would be a better place to ask this unless you find a bug with the library or have a feature request as account linking is complicated.

**Comment by Canain** [comment]
Closing since there hasn't been more discussion.
