### ISSUE TITLE
Response from `conv.followup` does not include other data on the conv object

### ISSUE THREAD

**Issue by erikvdplas** [actions-on-google/actions-on-google-nodejs#210]
`conv.followup` rewrites the entire raw json for the final response. Therefore, something like this is not possible:
```
conv.data.property = value;
conv.followup('[event_name]');
```
The expected behavior would be that response data like session data (stored in the _actions_on_google output context) is also retained when setting a followup event.

**Comment by Canain** [comment]
Closing this since the PR Is merged.

**Comment by grctest** [comment]
I'm actively debugging a new aog bot, the ability to have conv.data persist during a conv.followup is great, but is conv.user.storage.data treated the same if declared prior to the followup in the same intent? Thanks 👍
