### ISSUE TITLE
largeImage property mediaObject class not working?

### ISSUE THREAD

**Issue by stopsatgreen** [actions-on-google/actions-on-google-nodejs#215]
I’m trying to add a `largeImage` property to a media response through the `mediaObject` constructor, like this:

```
conv.ask(new MediaObject({
    name: 'A File',
    url: 'song.mp3',
    largeImage: new Image({
        url: 'image.jpg',
        alt: 'Alt text'
    }),
}));
```

But the response simply ignores the image. No error is given, and the title and audio file play as expected.

The issue doesn’t seem to be with my image, because I can use the `icon` property instead and it works without problems:

```
conv.ask(new MediaObject({
    name: 'A File',
    url: 'song.mp3',
    icon: new Image({
        url: 'image.jpg',
        alt: 'Alt text'
    }),
}));
```

I’ve tried not using the `Image` constructor, as below, without any result.

```
conv.ask(new MediaObject({
    name: 'A File',
    url: 'song.mp3',
    largeImage: {
        url: 'image.jpg'
    },
}));
```

**Comment by Fleker** [comment]
As you're using the client library and the `MediaObject` constructor, you should use the property name [`image`](https://actions-on-google.github.io/actions-on-google-nodejs/interfaces/conversation_response.mediaobjectoptions.html).

**Comment by stopsatgreen** [comment]
Ugh, I was looking in the wrong place in the documentation. Thanks!
