### ISSUE TITLE
Sentry monitoring is not possible

### ISSUE THREAD

**Issue by sergio1990** [actions-on-google/actions-on-google-nodejs#218]
As a developer, I want to integrate the [Sentry service](https://sentry.io/welcome/) to be able to see all the available information about the exception in the app. But using the [installation instructions](https://docs.sentry.io/clients/node/integrations/express/) for the expressjs the integration does not work - no exceptions are sent in the Sentry. I can suppose that all errors are caught inside the [express integration code](https://github.com/actions-on-google/actions-on-google-nodejs/blob/v2.2.0/src/framework/express.ts#L55-L58) and that catching suppresses the further error propagation. Considering, that Sentry error handler is set up as a middleware at the end of the expressjs stack it could be true.

Sentry has the possibility to capture exceptions manually, but it would be very nice and convenient to have some global place to do that.

### Libraries versions

- `express => 4.16.3`
- `actions-on-google => 2.2.0`
- `@sentry/node => 4.0.0-beta.12`

**Comment by Canain** [comment]
You should be able to use the global [`app.catch`](https://actions-on-google.github.io/actions-on-google-nodejs/interfaces/dialogflow.dialogflowapp.html#catch) method to capture and handle all errors from the intent handlers.

See the Name Psychic sample for an [example](https://github.com/actions-on-google/dialogflow-name-psychic-nodejs/blob/a66a39eadcc5fa192608b2df0b73d0ea173d2552/functions/index.js#L223) of how this can be used.

```javascript
app.catch((conv, e) => {
  console.error(e);
  conv.close(responses.readMindError);
});
```

**Comment by Canain** [comment]
Closing this as there hasn't been more discussion.

Please reopen if you still hit this issue.
