### ISSUE TITLE
AWS Lambda with API Gateway throwing response error

### ISSUE THREAD

**Issue by tommyokeefe** [actions-on-google/actions-on-google-nodejs#219]
I'm experiencing the same issue outlined in [this closed issue](https://github.com/actions-on-google/actions-on-google-nodejs/issues/173). 
I'm connecting to the lambda via API Gateway and it works fine if I do something like this:
```
exports.fulfillment = function (event: any, context: any, callback: any) {
    app.handler(event, {}).then((res) => {
        if (res.status !== 200) {
            callback(null, { fulfillmentText: `I got status code: ${res.status}` });
        } else {
            callback(null, res.body);
        }
    }).catch((e) => {
        callback(null, { fulfillmentText: `There was an error\n${e}` });
    });
};
```
I would love to be able to do it the way your documentation outlines, but if I do I get a TypeError:
```
{
    "errorMessage": "Cannot convert undefined or null to object",
    "errorType": "TypeError",
    "stackTrace": [
        "Function.keys (<anonymous>)",
        "Lambda.<anonymous> (/var/task/node_modules/actions-on-google/dist/framework/lambda.js:36:36)",
        "Generator.next (<anonymous>)",
        "/var/task/node_modules/actions-on-google/dist/framework/lambda.js:22:71",
        "new Promise (<anonymous>)",
        "__awaiter (/var/task/node_modules/actions-on-google/dist/framework/lambda.js:18:12)",
        "/var/task/node_modules/actions-on-google/dist/framework/lambda.js:30:46",
        "omni (/var/task/node_modules/actions-on-google/dist/assistant.js:44:53)"
    ]
}
```
I guess the ask in this issue is either: 
* get this working the way it is outlined in the docs `exports.fulfillment = app;`.
* Update the docs to match the need for a lmbda wrapping function like I have above. 

If I'm missing something in my Lambda or API Gateway config I'd be fine with changing/updating it. Just let me know! 

Thanks,
Tommy

**Comment by Canain** [comment]
Can you log the entire `event` Object? I'm suspecting that the event object is unexpected somehow and thus it's throwing an error parsing it.

Something like
```javascript
console.log(event);
console.log(JSON.stringify(event, null, 2));
```
would help a lot.

**Comment by hingyeung** [comment]
I had similar problem and it was because I didn't have **Lambda Proxy integration** enabled and as a result, the headers were not passed to the Lambda function as part of the event object.

I think the error was caused by `const headers = Object.keys(event.headers).reduce((o, k) => {...` in [lambda.ts](https://github.com/actions-on-google/actions-on-google-nodejs/blob/1e8c3eb1dc025b52962fac5ff4f23ce72940782c/src/framework/lambda.ts) when event.headers doesn't exist.

**Comment by igilham** [comment]
I'm seeing the same issue but haven't had time to look into a fix yet. I'll have to check the proxy integration setting.

Ultimately, I think we just need better documentation for how to run Actions on Google projects on AWS Lambda correctly.

**Comment by Canain** [comment]
I think not having Lambda Proxy integration is the problem here as the library expected lambda to be in that format in order to process header information into and out of the library.

Possibly, the library could be changed so that it still works with non Lambda Proxy integration by detecting if the headers field is there to determine how it should respond. It could also be done via configuration.

For lambda users, what would be the best way to support lambda in these cases? Is it fine to only support Lambda Proxy integration or should it support both? Supporting both might lose the extra information that are outside of the JSON body when not using Lambda Proxy integration.

**Comment by igilham** [comment]
I'd like to be able to say `exports.handler = app` and for it to magically work whether the object passed in is a raw Lambda event (e.g. when running BST proxy) or an HTTP request event passed via API Gateway. That would be a good test of the value of the frameworks system in the V2 SDK.

I don't personally mind losing the headers etc. that may be in the event object, as I would write my own wrapper function anyway if I wanted to handle those.

**Comment by tommyokeefe** [comment]
Here is a log of the event:
```
{
    "resource": "/",
    "path": "/",
    "httpMethod": "POST",
    "headers": {
        "Accept": "text/plain, */*",
        "Accept-Charset": "big5, big5-hkscs, cesu-8, euc-jp, euc-kr, gb18030, gb2312, gbk, ibm-thai, ibm00858, ibm01140, ibm01141, ibm01142, ibm01143, ibm01144, ibm01145, ibm01146, ibm01147, ibm01148, ibm01149, ibm037, ibm1026, ibm1047, ibm273, ibm277, ibm278, ibm280, ibm284, ibm285, ibm290, ibm297, ibm420, ibm424, ibm437, ibm500, ibm775, ibm850, ibm852, ibm855, ibm857, ibm860, ibm861, ibm862, ibm863, ibm864, ibm865, ibm866, ibm868, ibm869, ibm870, ibm871, ibm918, iso-2022-cn, iso-2022-jp, iso-2022-jp-2, iso-2022-kr, iso-8859-1, iso-8859-13, iso-8859-15, iso-8859-2, iso-8859-3, iso-8859-4, iso-8859-5, iso-8859-6, iso-8859-7, iso-8859-8, iso-8859-9, jis_x0201, jis_x0212-1990, koi8-r, koi8-u, shift_jis, tis-620, us-ascii, utf-16, utf-16be, utf-16le, utf-32, utf-32be, utf-32le, utf-8, windows-1250, windows-1251, windows-1252, windows-1253, windows-1254, windows-1255, windows-1256, windows-1257, windows-1258, windows-31j, x-big5-hkscs-2001, x-big5-solaris, x-compound_text, x-euc-jp-linux, x-euc-tw, x-eucjp-open, x-ibm1006, x-ibm1025, x-ibm1046, x-ibm1097, x-ibm1098, x-ibm1112, x-ibm1122, x-ibm1123, x-ibm1124, x-ibm1166, x-ibm1364, x-ibm1381, x-ibm1383, x-ibm300, x-ibm33722, x-ibm737, x-ibm833, x-ibm834, x-ibm856, x-ibm874, x-ibm875, x-ibm921, x-ibm922, x-ibm930, x-ibm933, x-ibm935, x-ibm937, x-ibm939, x-ibm942, x-ibm942c, x-ibm943, x-ibm943c, x-ibm948, x-ibm949, x-ibm949c, x-ibm950, x-ibm964, x-ibm970, x-iscii91, x-iso-2022-cn-cns, x-iso-2022-cn-gb, x-iso-8859-11, x-jis0208, x-jisautodetect, x-johab, x-macarabic, x-maccentraleurope, x-maccroatian, x-maccyrillic, x-macdingbat, x-macgreek, x-machebrew, x-maciceland, x-macroman, x-macromania, x-macsymbol, x-macthai, x-macturkish, x-macukraine, x-ms932_0213, x-ms950-hkscs, x-ms950-hkscs-xp, x-mswin-936, x-pck, x-sjis_0213, x-utf-16le-bom, x-utf-32be-bom, x-utf-32le-bom, x-windows-50220, x-windows-50221, x-windows-874, x-windows-949, x-windows-950, x-windows-iso2022jp",
        "Accept-Encoding": "gzip,deflate",
        "CloudFront-Forwarded-Proto": "https",
        "CloudFront-Is-Desktop-Viewer": "true",
        "CloudFront-Is-Mobile-Viewer": "false",
        "CloudFront-Is-SmartTV-Viewer": "false",
        "CloudFront-Is-Tablet-Viewer": "false",
        "CloudFront-Viewer-Country": "US",
        "Content-Type": "application/json; charset=UTF-8",
        "Host": "6c2zblioi4.execute-api.us-east-1.amazonaws.com",
        "User-Agent": "Apache-HttpClient/4.5.4 (Java/1.8.0_181)",
        "Via": "1.1 f67b851ee5081b3091a26e4dc87cc6c4.cloudfront.net (CloudFront)",
        "X-Amz-Cf-Id": "jVzTFpl9gLsquJ3Qf1Hy81L-atULY3bojavRtEUees9tdDedw1wc8A==",
        "X-Amzn-Trace-Id": "Root=1-5b998122-fff9f83cfb9d70a4295b7210",
        "X-Forwarded-For": "35.232.167.147, 52.46.22.51",
        "X-Forwarded-Port": "443",
        "X-Forwarded-Proto": "https"
    },
    "multiValueHeaders": {
        "Accept": [
            "text/plain, */*"
        ],
        "Accept-Charset": [
            "big5, big5-hkscs, cesu-8, euc-jp, euc-kr, gb18030, gb2312, gbk, ibm-thai, ibm00858, ibm01140, ibm01141, ibm01142, ibm01143, ibm01144, ibm01145, ibm01146, ibm01147, ibm01148, ibm01149, ibm037, ibm1026, ibm1047, ibm273, ibm277, ibm278, ibm280, ibm284, ibm285, ibm290, ibm297, ibm420, ibm424, ibm437, ibm500, ibm775, ibm850, ibm852, ibm855, ibm857, ibm860, ibm861, ibm862, ibm863, ibm864, ibm865, ibm866, ibm868, ibm869, ibm870, ibm871, ibm918, iso-2022-cn, iso-2022-jp, iso-2022-jp-2, iso-2022-kr, iso-8859-1, iso-8859-13, iso-8859-15, iso-8859-2, iso-8859-3, iso-8859-4, iso-8859-5, iso-8859-6, iso-8859-7, iso-8859-8, iso-8859-9, jis_x0201, jis_x0212-1990, koi8-r, koi8-u, shift_jis, tis-620, us-ascii, utf-16, utf-16be, utf-16le, utf-32, utf-32be, utf-32le, utf-8, windows-1250, windows-1251, windows-1252, windows-1253, windows-1254, windows-1255, windows-1256, windows-1257, windows-1258, windows-31j, x-big5-hkscs-2001, x-big5-solaris, x-compound_text, x-euc-jp-linux, x-euc-tw, x-eucjp-open, x-ibm1006, x-ibm1025, x-ibm1046, x-ibm1097, x-ibm1098, x-ibm1112, x-ibm1122, x-ibm1123, x-ibm1124, x-ibm1166, x-ibm1364, x-ibm1381, x-ibm1383, x-ibm300, x-ibm33722, x-ibm737, x-ibm833, x-ibm834, x-ibm856, x-ibm874, x-ibm875, x-ibm921, x-ibm922, x-ibm930, x-ibm933, x-ibm935, x-ibm937, x-ibm939, x-ibm942, x-ibm942c, x-ibm943, x-ibm943c, x-ibm948, x-ibm949, x-ibm949c, x-ibm950, x-ibm964, x-ibm970, x-iscii91, x-iso-2022-cn-cns, x-iso-2022-cn-gb, x-iso-8859-11, x-jis0208, x-jisautodetect, x-johab, x-macarabic, x-maccentraleurope, x-maccroatian, x-maccyrillic, x-macdingbat, x-macgreek, x-machebrew, x-maciceland, x-macroman, x-macromania, x-macsymbol, x-macthai, x-macturkish, x-macukraine, x-ms932_0213, x-ms950-hkscs, x-ms950-hkscs-xp, x-mswin-936, x-pck, x-sjis_0213, x-utf-16le-bom, x-utf-32be-bom, x-utf-32le-bom, x-windows-50220, x-windows-50221, x-windows-874, x-windows-949, x-windows-950, x-windows-iso2022jp"
        ],
        "Accept-Encoding": [
            "gzip,deflate"
        ],
        "CloudFront-Forwarded-Proto": [
            "https"
        ],
        "CloudFront-Is-Desktop-Viewer": [
            "true"
        ],
        "CloudFront-Is-Mobile-Viewer": [
            "false"
        ],
        "CloudFront-Is-SmartTV-Viewer": [
            "false"
        ],
        "CloudFront-Is-Tablet-Viewer": [
            "false"
        ],
        "CloudFront-Viewer-Country": [
            "US"
        ],
        "Content-Type": [
            "application/json; charset=UTF-8"
        ],
        "Host": [
            "6c2zblioi4.execute-api.us-east-1.amazonaws.com"
        ],
        "User-Agent": [
            "Apache-HttpClient/4.5.4 (Java/1.8.0_181)"
        ],
        "Via": [
            "1.1 f67b851ee5081b3091a26e4dc87cc6c4.cloudfront.net (CloudFront)"
        ],
        "X-Amz-Cf-Id": [
            "jVzTFpl9gLsquJ3Qf1Hy81L-atULY3bojavRtEUees9tdDedw1wc8A=="
        ],
        "X-Amzn-Trace-Id": [
            "Root=1-5b998122-fff9f83cfb9d70a4295b7210"
        ],
        "X-Forwarded-For": [
            "35.232.167.147, 52.46.22.51"
        ],
        "X-Forwarded-Port": [
            "443"
        ],
        "X-Forwarded-Proto": [
            "https"
        ]
    },
    "queryStringParameters": null,
    "multiValueQueryStringParameters": null,
    "pathParameters": null,
    "stageVariables": null,
    "requestContext": {
        "resourceId": "4x5ln6ey12",
        "resourcePath": "/",
        "httpMethod": "POST",
        "extendedRequestId": "NIEdVGdiIAMF4qw=",
        "requestTime": "12/Sep/2018:21:12:02 +0000",
        "path": "/dialogflow/",
        "accountId": "255990033474",
        "protocol": "HTTP/1.1",
        "stage": "dialogflow",
        "requestTimeEpoch": 1536786722100,
        "requestId": "7e2affd7-b6d0-11e8-b7a6-73e966c719ba",
        "identity": {
            "cognitoIdentityPoolId": null,
            "accountId": null,
            "cognitoIdentityId": null,
            "caller": null,
            "sourceIp": "35.232.167.147",
            "accessKey": null,
            "cognitoAuthenticationType": null,
            "cognitoAuthenticationProvider": null,
            "userArn": null,
            "userAgent": "Apache-HttpClient/4.5.4 (Java/1.8.0_181)",
            "user": null
        },
        "apiId": "6c2zblioi4"
    },
    "body": "{\n  \"responseId\": \"f84da642-492c-4826-b22e-9a8849ce26c8\",\n  \"queryResult\": {\n    \"queryText\": \"talk to NPR one test\",\n    \"action\": \"input.welcome\",\n    \"parameters\": {\n    },\n    \"allRequiredParamsPresent\": true,\n    \"fulfillmentText\": \"Good day! What can I do for you today?\",\n    \"fulfillmentMessages\": [{\n      \"text\": {\n        \"text\": [\"Hello! How I can help you?\"]\n      }\n    }],\n    \"outputContexts\": [{\n      \"name\": \"projects/npr-one-13863/agent/sessions/ABwppHFbXzACKQLdcM5pQ9hDo8ndCHSrYYuRzBjcMhbGJ1wV5K_mUwLUYQ_qh003M3Z7bQskZ1fOKm_Z_w/contexts/actions_capability_screen_output\"\n    }, {\n      \"name\": \"projects/npr-one-13863/agent/sessions/ABwppHFbXzACKQLdcM5pQ9hDo8ndCHSrYYuRzBjcMhbGJ1wV5K_mUwLUYQ_qh003M3Z7bQskZ1fOKm_Z_w/contexts/actions_capability_audio_output\"\n    }, {\n      \"name\": \"projects/npr-one-13863/agent/sessions/ABwppHFbXzACKQLdcM5pQ9hDo8ndCHSrYYuRzBjcMhbGJ1wV5K_mUwLUYQ_qh003M3Z7bQskZ1fOKm_Z_w/contexts/google_assistant_input_type_voice\"\n    }, {\n      \"name\": \"projects/npr-one-13863/agent/sessions/ABwppHFbXzACKQLdcM5pQ9hDo8ndCHSrYYuRzBjcMhbGJ1wV5K_mUwLUYQ_qh003M3Z7bQskZ1fOKm_Z_w/contexts/actions_capability_media_response_audio\"\n    }, {\n      \"name\": \"projects/npr-one-13863/agent/sessions/ABwppHFbXzACKQLdcM5pQ9hDo8ndCHSrYYuRzBjcMhbGJ1wV5K_mUwLUYQ_qh003M3Z7bQskZ1fOKm_Z_w/contexts/actions_capability_web_browser\"\n    }],\n    \"intent\": {\n      \"name\": \"projects/npr-one-13863/agent/intents/5acd2438-4840-4f18-8ddf-6752e1446a78\",\n      \"displayName\": \"Default Welcome Intent\"\n    },\n    \"intentDetectionConfidence\": 0.91,\n    \"languageCode\": \"en-us\"\n  },\n  \"originalDetectIntentRequest\": {\n    \"source\": \"google\",\n    \"version\": \"2\",\n    \"payload\": {\n      \"isInSandbox\": true,\n      \"surface\": {\n        \"capabilities\": [{\n          \"name\": \"actions.capability.MEDIA_RESPONSE_AUDIO\"\n        }, {\n          \"name\": \"actions.capability.AUDIO_OUTPUT\"\n        }, {\n          \"name\": \"actions.capability.SCREEN_OUTPUT\"\n        }, {\n          \"name\": \"actions.capability.WEB_BROWSER\"\n        }]\n      },\n      \"inputs\": [{\n        \"rawInputs\": [{\n          \"query\": \"talk to NPR one test\",\n          \"inputType\": \"VOICE\"\n        }],\n        \"arguments\": [{\n          \"rawText\": \"talk to NPR one test\",\n          \"textValue\": \"talk to NPR one test\",\n          \"name\": \"text\"\n        }],\n        \"intent\": \"actions.intent.TEXT\"\n      }],\n      \"user\": {\n        \"userStorage\": \"{\\\"data\\\":{}}\",\n        \"lastSeen\": \"2018-09-12T21:00:21Z\",\n        \"accessToken\": \"edcc7e3311b7510cd5241c65e1415a91340bcfc05a00c38cc84b8e3fb62ae63659c9843fcdb1aaae\",\n        \"locale\": \"en-US\",\n        \"userId\": \"ABwppHHUG9z0l4tnVSrPTwx1OiAzFjHzjkj4OFtVt3z-HaLqaGpLP_fsVaiNN36G_QdFF3sqj3kHVu28fQ\"\n      },\n      \"conversation\": {\n        \"conversationId\": \"ABwppHFbXzACKQLdcM5pQ9hDo8ndCHSrYYuRzBjcMhbGJ1wV5K_mUwLUYQ_qh003M3Z7bQskZ1fOKm_Z_w\",\n        \"type\": \"ACTIVE\",\n        \"conversationToken\": \"[]\"\n      },\n      \"availableSurfaces\": [{\n        \"capabilities\": [{\n          \"name\": \"actions.capability.AUDIO_OUTPUT\"\n        }, {\n          \"name\": \"actions.capability.SCREEN_OUTPUT\"\n        }, {\n          \"name\": \"actions.capability.WEB_BROWSER\"\n        }]\n      }]\n    }\n  },\n  \"session\": \"projects/npr-one-13863/agent/sessions/ABwppHFbXzACKQLdcM5pQ9hDo8ndCHSrYYuRzBjcMhbGJ1wV5K_mUwLUYQ_qh003M3Z7bQskZ1fOKm_Z_w\"\n}",
    "isBase64Encoded": false
}
```

I have the Lambda Proxy Integration turned on but I still seem to be getting the same error.

**Comment by danepowell** [comment]
I was also trying to customize the Lambda handler a bit, and had to call `app()` directly rather than `app.handler()`. `app.handler()` would produce all kinds of errors similar to the OP.

This is what worked in the end:

```js
exports.fulfillment = function(event, context, callback) {
  if (event && 'cron' === event) {
    logger.info('Cron request, existing early.');
    return;
  }
  else {
    logger.info('Google request received.');
    app(event, context, callback);
  }
};
```

**Comment by HamishSmartVoice** [comment]
We encountered the same issue.

The problem is that the API Gateway configuration passes into the Lambda runtime a parsed body as opposed to the expected strings.

The error you'll get for that is:
SyntaxError: Unexpected token o in JSON at position 1

If there was a type check added to the module to test if the input is a string or not that'd fix the issue.

**Comment by Canain** [comment]
It seems that Lambda has a lot of different possible event formats for HTTP webhooks:

* The `event` object contains `headers` as a JSON object map of keys to values and `body` as a string
   * This is how the library currently recognizes
   * Returns a `{ statusCode, body, headers}` object where `body` is a string
* The entire `event` object is the JSON body, completely parsed into a JSON object
   * Would this mean that the response should be just the `body` as a JSON object similarly to the event?

@HamishSmartVoice for that case, if it is not a string in the request `body` field but is a JSON object, would the return type for `body` also be a JSON object not a string?

**Comment by HamishSmartVoice** [comment]
@Canain I always return a stringified output to the API handler for consistencies sake. In theory we're immediately going from the return of the lambda to a HTTPS request so the type of the output isn't relevant because it has to be transmitted in text.

I had a quick fiddle over the weekend and found that you could modify the call to read:
```javascript
      const result = yield standard((typeof event.body === "object") ? event.body : JSON.parse(event.body), headers, {
```

**Comment by Canain** [comment]
@igilham For the case where the entire event object is the JSON body, would you expect the return also be just the response JSON body?

Or for consistency sake, should it be the same response format as before, `{ statusCode, body, headers}`?

**Comment by igilham** [comment]
@Canain Good question. I think it depends on what the Assistant service expects to get back. If it looks for headers, then the SDK needs to support it. If it doesn't care then maybe a simpler response would be sufficient. In my testing, I have found that calling `callback(null, result.body)` in the Lambda works just fine.

Ultimately it may not matter how the body and headers are mangled into and out of the function via API Gateway as long as there is a supported, documented usage example that is guaranteed to work correctly. There is not enough information in the documentation at the moment to make that guarantee.

**Comment by acucciniello** [comment]
Any solution to this error? I am also stuck as of now

**Comment by Canain** [comment]
@igilham Since there are some responses that use the HTTP status code and for consistency sake, the current pending implementation is to return the same response no matter what the input is which is:

```typescript
{
  statusCode: number
  body: string
  headers: Object<string, string>
}
```

Would that work for you? Although this seems to be the best approach for consistency, it might result in addition code to transform the output.

**Comment by igilham** [comment]
That would work, but it all depends on how API Gateway is configured. My team is currently using the below code to handle the eventuality of the `event` containing only the body, or containing the body and headers as you suggest.

On the response side, it would be nicer if the SDK could deal with the error handling and call the callback appropriately, but the format again depends on how API Gateway is configured. A fully documented example would be the most helpful thing for developers.

```javascript
exports.handler = async (event, context, callback) => {
    const body = event.body || event
    const headers = event.headers || context.request.headers || []
    const result = await action.handler(body, headers);
    if (result.status >= 200 && result.status < 300) {
        callback(null, result.body);
    } else {
        callback(JSON.stringify(result));
    }
}
```

**Comment by Canain** [comment]
Alternatively, maybe a custom function for generating the response format could work:

```javascript
const app = dialogflow()
app.frameworks.lambda.responder = (event, context, callback, result) => {
  if (result.status >= 200 && result.status < 300) {
    callback(null, result.body)
  } else {
    callback(JSON.stringify(result))
  }
}
// ...
exports.handler = app
```

But this doesn't really save much code the developer currently has to write anyways.

**Comment by igilham** [comment]
As long as the changes don't prevent people from writing their own wrapper code, I think the approach is fine. It might be neater to add a mechanism to insert new frameworks, similar to `app.middleware`, but as you say, this may not save much code. It's more important that it works and that it's clear how to use it.

Requirements will differ for apps hosted in different ways on different environments.

**Comment by Canain** [comment]
With the release of `2.6.0` through df48d7e1ac9a3172f2f7c3ec76c5767165c098a2, we added support to detect and parse different request formats from lambda.

```
Add support for other lambda formats

* Support for lambda entire body input format
* Support for lambda input body being an object
```

The response format is still the same as before. For now the way to perform custom response logic is still to manually call `app.handler` with your own code logic. But now the library will be able to handle most request formats on its own.

Let us know if there are any issues.

**Comment by shivalipawar** [comment]
@Canain I have used latest release i.e. 2.6.0. But still same error response of "Webhook call failed. Error: Failed to parse webhook JSON response: Cannot find field: statusCode in message google.cloud.dialogflow.v2.WebhookResponse." exists.

Below is my handler,
`module.exports.handler = function(event: any, context: any, callback: any) {
    if (!app) {
        app = createApp()
    }
    console.log("Event is "+JSON.stringify(event));
    app(event, context, callback).then((res:any)=>{
        if (res.status != 200) {
            callback(null, {"fulfillmentText": `I got status code: ${res.status}`});
        } else {
            callback(null, res.body);
        }
    }).catch((e:any) => {
        callback(null, {"fulfillmentText": `There was an error\n${e}`});
        });
}`

Also app.ts is as ,
`export function createApp() : OmniHandler {
    const app = dialogflow();
    
    interface Intent {
        names: string[],
        handler: DialogflowIntentHandler<{}, {}, Contexts, CustomConversation, Parameters, Argument>
    }
    const intents: Intent[] = [
        helpAction,
        getPrice
    ]
    intents.forEach(intent => 
        intent.names.forEach(name => {
            console.log("Name"+name)
            var value = app.intent(name, intent.handler)
            console.log("value in app.ts is"+value);
        })
        )
    return app
}`

Also GetPrice intent is as below,
`export function handler(conv:any) {
    var result;
    const text = "What company stock price do you want to know?"

     result = conv.ask(new RichResponse()
        .add(new SimpleResponse({
            speech: text,
            text: text,
        }))
        .add(new LinkOutSuggestion({
            name: "List of all company stock prices",
            url: "https://google.com"
        })))

        console.log("Result out is "+JSON.stringify(result));
        return result;
}`

Can you please check into this? Seems its not yet fixed.

**Comment by Canain** [comment]
@shivalipawar 

Hi, it looks like you want to just completely handle the response generation. For that, you need to call the `app.handler` function and customize your response generation.

It should look something like:

```typescript
module.exports.handler = (event: any, context: any, callback: any) => {
  const body = event.body || event;
  const headers = event.headers || context.request.headers || [];
  return action.handler(body, headers).then(res =>
    if (res.status != 200) {
        callback(null, {"fulfillmentText": `I got status code: ${res.status}`});
    } else {
        callback(null, res.body);
    }
  };
};
```

**Comment by shivalipawar** [comment]
@Canain Thank you for the suggestion it has now fixed the issue.

**Comment by shivalipawar** [comment]
We need to return this app.handler since aws lambda understands this format. Also its different for express, firebase and lambda right?

**Comment by Canain** [comment]
Returning the return value of `app.handler()` in this case is to propagate the promise to lambda.

For other frameworks, you can check the [examples in our docs](https://developers.google.com/actions/reference/nodejsv2/overview#example_cloud_functions_for_firebase).
