### ISSUE TITLE
unhandled null reference error on getArgument method

### ISSUE THREAD

**Issue by strttn** [actions-on-google/actions-on-google-nodejs#22]
I have been receiving the following error using node-js module actions-on-google v1.0.8.

```
/app/node_modules/actions-on-google/api-ai-assistant.js:280 
return this.body_.originalRequest.data.inputs[0].arguments[0][argName]; 
                                                              ^ 
TypeError: Cannot read property 'raw_text' of undefined 
at getArgument (/app/node_modules/actions-on-google/api-ai-assistant.js:280:68) 
```

It looks like the JSON can be returned from API.ai without any arguments in the input. This is then not handled by the assistant.getArgument() method call.

I would expect that in the event that the argument was not present, the method would return `undefined` rather than failing.

Thanks.

**Comment by smishra2** [comment]
Hey @strttn thanks for flagging this! We've included a fix in our latest update c65324ac91a16272b2f0e110b071f4405b6dc2f5
