### ISSUE TITLE
JSON Schema for action.json File

### ISSUE THREAD

**Issue by 0xcaff** [actions-on-google/actions-on-google-nodejs#220]
The v2 version of this library makes it much easier to build actions on google. One thing which would be nice to have is a json schema for the `action.json` file generated by the `gactions` tool so editors like VSCode and WebStorm can have intellisense.

It seems that you guys already have some sort of machine readable descriptor from which the documentation for the file is generated from. https://developers.google.com/actions/reference/rest/Shared.Types/ActionPackage

I'm not sure where there's a better place to request things like this.

**Comment by lucaswadedavis** [comment]
Due to more than 3 months of inactivity, this issue is being closed. 

If you think the resolution is in error, please re-open the request with fresh information.
