### ISSUE TITLE
Out-dated documentation page: How to Verify Requests

### ISSUE THREAD

**Issue by igilham** [actions-on-google/actions-on-google-nodejs#221]
It looks like the webhook documentation page that for [verifying that requests came from Google](https://developers.google.com/actions/reference/rest/verify-requests) has not been updated with version 2 of the SDK.

It includes a code snippet calling an API (`ActionSdkApp.isRequestFromAssistant`, renamed to `isRequestFromGoogle`) in the V1 SDK that has not survived in the move to V2.

It may be worth removing the code snippet and providing an example of JWT validation for completeness.

Alternatively, it may we worth supporting the lost feature again, depending on project priorities.

**Comment by Canain** [comment]
Should be fixed now for that page. We will work on adding it to the migration docs too.
