### ISSUE TITLE
TypeError: dialogflow is not a function

### ISSUE THREAD

**Issue by Kartik745** [actions-on-google/actions-on-google-nodejs#223]
TypeError: dialogflow is not a function
    at Object.<anonymous> (C:\Users\Admin\codelabs-nodejs1\functions\index.js:28:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\firebase-tools\lib\triggerParser.js:21:11
    at Object.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\firebase-tools\lib\triggerParser.js:75:3)

```
'use strict';

const {
  dialogflow,
  BasicCard,
  Permission,
} = require('actions-on-google');

const functions = require('firebase-functions');

const app = dialogflow({debug: true});

app.intent('Default Welcome Intent', (conv) => {
  conv.ask(new Permission({
    context: 'Hi there, to get to know you better',
    permissions: 'NAME',
  }));
});

app.intent('actions_intent_PERMISSION', (conv, params, permissionGranted) => {
  if (!permissionGranted) {
    conv.ask(`OK, no worries. where are you from ?`);
  } else {
    conv.data.userName = conv.user.name.display;
    conv.ask(`Thanks, ${conv.data.userName}. Where are you from ?`);
  }
});

app.intent('country', (conv, {country}) => {
const audioSound = 'https://actions.google.com/sounds/v1/cartoon/clang_and_wobble.ogg';
  if (conv.data.userName) {
    conv.ask(`<speak>${conv.data.userName}, okay fine <audio src="${audioSound}"></audio>` +
      `from which city are you belongs to?</speak>`);
  } else {
    conv.ask(`<speak>Your are from ${country}.` +
      `<audio src="${audioSound}"></audio>` +
      `from which city are you belongs to?</speak>`);
  }
});

exports.dialogflowFirebaseFulfillment = functions.https.onRequest(app);
```

**Comment by Fleker** [comment]
What version of the library are you using? You can check in the `package.json` file. Are you trying out [the codelab](https://github.com/actions-on-google/codelabs-nodejs)? Are you running into this error when trying to deploy your function, or when you actually try running it?

**Comment by Kartik745** [comment]
@Fleker 
"firebase-admin": "~6.0.0",
    "actions-on-google": "^1.8.0",
    "firebase-functions": "^2.0.3"
these are the dependencies
-yes this error comes when i am trying to deploy my function

**Comment by Kartik745** [comment]
thank you @Fleker 
just want to ask you one more quetion
what to do if getting error mesage while testing 'final response must be set' ?

**Comment by Fleker** [comment]
You can look at [this blog post](https://medium.com/google-developers/debugging-common-actions-on-google-errors-7c8527378d27) for common errors and how to resolve them.
