### ISSUE TITLE
User Entity is not working in Alpha Release

### ISSUE THREAD

**Issue by muhammadzumair** [actions-on-google/actions-on-google-nodejs#224]
I have developed an Action for google assistant using Dialogflow v1, everything is working perfectly in a developer version, but once I have submitted it for the Alpha release, the user entity not working for the alpha version or with the testers account. I have checked my logs and it shows me that user entity is created successfully but it didn't detect it in the slot filing. I have also tested it with the Get request from Postman with the same sessionId and successfully get the entities but I understand why it is not detecting in slot filing in Alpha version.

I have attached the video also about the issue, Please help me to resolve this. https://drive.google.com/file/d/1y2zSKqcZ3OTey_RGnRxHMZfFVhP5oSlh/view

StackOverflow link: https://stackoverflow.com/questions/52363882/user-entity-is-not-working-in-alpha-release

**Comment by mustafa786786** [comment]
We are facing the same issue. Everything is working fine in Development.
For alpha,Beta and Production we are facing this issue.
Even though entities are getting loaded, slot filling is done from Dialog Flow.

**Comment by muhammadzumair** [comment]
Hi,
Unfortunately the issue is not resolve yet, I contacted many times with
Actions on google support team, but they always said that they are working
on it to resolve the issue.
Its more than two months has gone but didn't receive any success from them.

The issue is probably because of updates in version 2 of Dialogflow.

Thanks,

Muhammad Zumair

**Comment by mustafa786786** [comment]
@muhammadzumair  Can you please share the reply which AOG  Technical team have shared with you.

**Comment by mustafa786786** [comment]
@Canain Is there any update for the above issue.

**Comment by muhammadzumair** [comment]
Hi Muhammad,

We apologize if you were inconvenienced by the delay in helping with your issue.

We understand the issue you've been experiencing hasn't been resolved. We want you to know we’re actively working it. You’ll get updates from us on the status of the issue until it’s resolved.

Note: This is a follow-up email. We require no action on your end unless you have any feedback or a follow-up question.

Thank you for your patience and understanding.


This is the reply, the actions on google team sends me since last two months, but not success.

**Comment by mustafa786786** [comment]
@muhammadzumair  Thanks for the information.

**Comment by lucaswadedavis** [comment]
Due to more than 3 months of inactivity, this issue is being closed. 

If you think the resolution is in error, please re-open the request with fresh information.
