### ISSUE TITLE
Question on access to internal logs

### ISSUE THREAD

**Issue by sriprabha** [actions-on-google/actions-on-google-nodejs#228]
Hello, we are building an action using Actions SDK (without the Dialog Flow integration). Is there anyway we can get access to the debug and error logs that shows up currently on the simulator's DEBUG/ERROR view? 

There are some errors that are thrown by the Assistant platform during rendering visual elements, and we are unable to catch those errors in our actions code flow. These errors are seen on the simulator debug/error UI. 

Example error msg```MalformedResponse
expected_inputs[0].possible_intents[0].input_value_data.option_value_spec.list_select: the number of ‘items’ must be between 2 and 30```

**Comment by Fleker** [comment]
Those errors come from the Actions on Google platform when you respond to a webhook. All of these errors are logged in [Stackdriver](https://cloud.google.com/stackdriver/), and you use Cloud Pub/Sub to send these error messages to a location of your choice, like on your server.

**Comment by 7laria** [comment]
same issue
