### ISSUE TITLE
get CONVERSATION_API_VERSION_HEADER fails

### ISSUE THREAD

**Issue by daverathbone** [actions-on-google/actions-on-google-nodejs#23]
**I am not using Express.js and code fails in assistant.js request_.get (line 241)**

Also I can not find version number (maybe its still in the HTTP header and I've just not found it?)

code:
`if (this.request_.get(CONVERSATION_API_VERSION_HEADER)) {`
 &nbsp; `this.apiVersion_ = this.request_.get(CONVERSATION_API_VERSION_HEADER);`
  &nbsp;    ` debug('Assistant API version: ' + this.apiVersion_);`
    `}`
my work around is to make a dummy  **req.get** function **before** "new Assistant({request: req, response: res})" 

code:
`req.get=(function (strName){`
&nbsp;&nbsp;	`if (strName=="Google-Assistant-API-Version") return "V1.0"; // Need real version`
&nbsp;&nbsp;	`//any others req.get functions here`
&nbsp;&nbsp;	`return "";`
			`});`

I have also had to do more work around's in the  "Utility method to send an HTTP response"  line 674
"this.response_.append","this.response_.status" and "send(response)"
in order to keep assistant.js un-touched.

Ideally assistant.js should have an option to export its HTTP responses, so that we are not locked into fixed Node server types, using  something like "req.http_callback=users HTTP response function" before "new Assistant({request: req, response: res})" 

This would then work for what ever your using and third party Node servers.

**Comment by Canain** [comment]
Hey, thanks for the feedback!

In [v2 of the library](medium.com/@silvano.luciani/actions-on-google-client-library-for-node-js-v2-0-0-alpha-c92361167f15), we added a better abstraction for request parsing and response generation which allows you to seamlessly use any web framework. It also include a generic handler [StandardHandler](https://github.com/actions-on-google/actions-on-google-nodejs/blob/c84ba000b6257b4d932e022658405e8661524625/src/framework/framework.ts#L74) which for now you can call using `app.handler` in v2. It takes a JSON object and Headers as inputs and outputs a JSON object and a status code in a Promise.

Please feel free to try it out and let us know what you think! Currently during the alpha phase, we want to get as much feedback as possible so we can polish it to create the best developer experience using the library.

**Comment by Canain** [comment]
closing this issue now that v2 is general availability
