### ISSUE TITLE
Custom events for Media events

### ISSUE THREAD

**Issue by prakashjais99** [actions-on-google/actions-on-google-nodejs#230]
We are writing media service web hook like spotify. But stuck with below issue.
How to create custom events for media events like Play started, paused, near finish etc for media object responses ? 
we are able to play music by media response object but not able to get any information weather play back started , paused or near finish. Only event we are getting is MEDIA_FINISHED from MEDIA status event

**Comment by igilham** [comment]
MEDIA_STATUS is the only event supported by the Assistant platform at present.

I would also appreciate it if the platform could be improved by adding more useful events to hook into. Alexa has a fairly rich events API for these features so it would be helpful to be able to do something similar on Google's platform.

**Comment by prakashjais99** [comment]
Any update on this google ?

**Comment by lucaswadedavis** [comment]
We're tracking it as a feature request. Thanks for the suggestion prakashjais99.
