### ISSUE TITLE
Cannot ready property "forEach" of undefined

### ISSUE THREAD

**Issue by csfeijo** [actions-on-google/actions-on-google-nodejs#233]
Hi, Im developer and Im using the version 2.3.0 from your package, but after update for the last version my code is returning the error:
```
Cannot ready property "forEach" of undefined
```
when I try to add the "conv" object for the assistant.:
Example:
```
const conv = assistant.conv();
conv.ask("Hello!");
assistant.add(conv);
```
My solution for now is lock the package.json to use only ~2.3.0 version.
The error example is displayed below:

![error_dialog-flow-lib](https://user-images.githubusercontent.com/25899/46693872-7cff8200-cbe1-11e8-9658-2a2237fc9e7d.PNG)

Thanks!

**Comment by Canain** [comment]
Hi, this is a known issue with the `dialogflow-fulfillment` library.

We are working on a fix. Please use the [issue](https://github.com/dialogflow/dialogflow-fulfillment-nodejs/issues/149) on the Dialogflow fulfillment GitHub to track this.
