### ISSUE TITLE
do actions-on-google-nodejs have this function : call google maps to navigation the place

### ISSUE THREAD

**Issue by Wolke** [actions-on-google/actions-on-google-nodejs#235]
like this solve in android 
https://stackoverflow.com/questions/2662531/launching-google-maps-directions-via-an-intent-on-android
but I would like to call in conversation
like:
talk to coffee-bot order a cappuccino at nearest Starbucks than navigation me to that store.
than google assistant open the google maps and navigation.

**Comment by Fleker** [comment]
You can present a Maps link to a user to click to open up Maps

**Comment by Wolke** [comment]
but when you drive you cannot do this.

**Comment by maaaaaaaax** [comment]
Due to more than 3 months of inactivity, this issue is being closed.

If you think the resolution is in error, please re-open the request with fresh information.
