### ISSUE TITLE
Encoding Issue when using DialogFlow v2 - AWS Lambda

### ISSUE THREAD

**Issue by jewkesy** [actions-on-google/actions-on-google-nodejs#238]
I'm just migrating from DialogFlow v1 to v2 and have an encoding issue.

As an example, I'm returning the following text :- 

`Is the name Beyoncé encoded correctly?`  but in DialogFlow  and Google Actions simulator it is displaying `Is the name BeyoncÃ© encoded correctly?`

This is the Lambda function to replicate: -

```
const {
    dialogflow,
    SimpleResponse,
} = require('actions-on-google');
 
const app = dialogflow();
 
app.intent('Default Welcome Intent', (conv, params) => {
    conv.ask(new SimpleResponse({
        speech: "Is the name Beyoncé encoded correctly?",
        text: "Is the name Beyoncé encoded correctly?"
    }));
});
 
app.fallback((conv) => {
    conv.ask(new SimpleResponse({
        speech: "I'm sorry, I didn't catch that",
        text: "I'm sorry, I didn't catch that"
    }));
}); 
 
exports.handler = function(event, context, callback) {
    app.handler(event, {}).then((res) => {
        if (res.status != 200) {
            callback(null, {"fulfillmentText": `I got status code: ${res.status}`});
        } else {
            callback(null, res.body);
        }
    }).catch((e) => {
    callback(null, {"fulfillmentText": `There was an error\n${e}`});
    });
}; 
```

I've set the Webhook header `{Content-Type: application/json;charset=UTF-8}` in my agent fulfilment configuration.

Am I missing anything else?

**Comment by beeme1mr** [comment]
Were you able to get this working? I'm running into a similar issue.

**Comment by jewkesy** [comment]
> Were you able to get this working? I'm running into a similar issue.

Yes I did!   My resolution was to add further configuration settings to my AWS API Gateway.  It appears that DialogFlow v2 no longer assumes (or defaults to?) the utf-8 charset for the web hook response.  Just add `content-type: application/json; charset=UTF-8` to your response header, rather than relying on this value being persisted from the request header.

I had been testing a combination of the DialogFlow Test UI, cURL and Postman, which under certain pretences, must have been interpreting the charset to UTF-8 as a default, so it was difficult to track.

Good luck!

**Comment by jewkesy** [comment]
Closing
