### ISSUE TITLE
Outdated tutorials for responses

### ISSUE THREAD

**Issue by Crackpack** [actions-on-google/actions-on-google-nodejs#239]
https://developers.google.com/actions/assistant/responses
 Tutorials on this page are outdated, cannot run any SimpleResponse, BasicCard, BrowseCarousel, BrowseCarouselItem. Hard to work with to learn

**Comment by tocie** [comment]
Hi,
You may need extra `conv.ask()` when you use that page.
For example:
`
conv.ask("Hello");
conv.ask(new Suggestions(["Suggestion 1", "Suggestion 2", "Suggestion 3"]));
`

**Comment by Crackpack** [comment]
I got it working. It seems we have to add string parameter for all Cards
" conv.ask(`Here's the color`,new BasicCard({  text: 'This is a basic card.'}));'
