### ISSUE TITLE
ReferenceError: UpdatePermission is not defined

### ISSUE THREAD

**Issue by JohannesMaier** [actions-on-google/actions-on-google-nodejs#240]
I would like to send Push Notifications via google-actions to my clients. According to this **[manual](https://developers.google.com/actions/assistant/updates/notifications)** I have to ask them for Permission with a command like this:
> conv.ask(new UpdatePermission({intent: 'tell_latest_tip'}));

But whenever this command comes to action, my app throws following error:
>ReferenceError: UpdatePermission is not defined

However, the SignIn-command "new SignIn()" works completely fine.

What have to be done, to get this command work?

**Comment by yoichiro** [comment]
@JohannesMaier Is the `UpdatePermission` imported in your code as like the following?

```js
const {
  UpdatePermission,
  ...
} = require("actions-on-google");
```

**Comment by JohannesMaier** [comment]
Hi @yoichiro, 
thanks this solved my error!!


Now I get the following error in the error log of the actions console:
```
MalformedResponse
expected_inputs[0].possible_intents[0].input_value_data: The intent the app is asking for permission to send updates for is not found..
```
Althought I created the intent I want the permission for. 
Do you also know a solution for this one?

Thanks!
Johannes

**Comment by JohannesMaier** [comment]
I found the solution for this one. For the push notification you have to use a **implicit invocation intents**, which can be created in Dialogflow -> Integrations -> Integration Settings. Then you have to go to the AoGC and turn on the **User engagement** for this intent.
