### ISSUE TITLE
Missing Conversation Data Context

### ISSUE THREAD

**Issue by tkruener** [actions-on-google/actions-on-google-nodejs#241]
Hello,

It might be wrong usage of conversation data on my side, but when i save session with 

`conversation.data.foo=5` i expect it to be saved for the life span of the session via a dialog flow context no matter what.
However, i noticed a strange case where conversation data is not contained inside the response object,
which happens whenever the final conversation data is strictly equal to the initial one (which it is in most cases).

I'm setting up the initial state of the conversation app by passing an init function to the dialogflow functions, like here:

```
const app = dialogflow({
    debug: true,
    init: () => {
        return {
            data: {
                state: State.LAUNCH,
                foo: 5
            } 
        }
    }
}
```

I currently have to use syntax like `conversation.data = {...conversation.data}` to fix this issue.

I looked into the source of the library and found this snippet, which might be related:

```
if (convDataOut !== convDataIn) {
      // Previously was setting every webhook call
      // But now will only set if different so lifespan does not get reset
      this.contexts.set(CONV_DATA_CONTEXT, CONV_DATA_CONTEXT_LIFESPAN, {
        data: convDataOut,
      })
    }
``` 
(conv.ts, line 371) 

I would be happy about any feedback, as I'm greatly confused about this behaviour right 
now.

Affected version: 2.4.1

Best wishes,
tkruener

**Comment by Canain** [comment]
This should have been fixed by #295 so closing this issue.
