### ISSUE TITLE
"Webhook call failed. Error: 404 Not Found" 

### ISSUE THREAD

**Issue by khajam30** [actions-on-google/actions-on-google-nodejs#242]
Hello Experts 

I have linked my web-hook to dialogflow under fulfillment. When i test the app using the google assistant it fails with following response 

FULFILLMENT RESPONSE: 

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /findbus</pre>
</body>
</html> 

I tried to further look for logs I got the below 
**********************************
**2018-11-01 15:09:32.992 GST
Dialogflow fulfillment Error: { "code": 206, "errorType": "partial_content", "errorDetails": "Webhook call failed. Error: 404 Not Found" }
Expand all | Collapse all {
 insertId:  "8loj18femdowq"  
 labels: {
  protocol:  "V1"   
  request_id:  "50007b7d-ffa1-4cfd-8815-c246c66ef5d4"   
  type:  "dialogflow_fulfillment_error_response"   
 }
 logName:  "projects/travelbookingagent-3f53a/logs/dialogflow_agent"  
 receiveTimestamp:  "2018-11-01T11:09:33.048173109Z"  
 resource: {
  labels: {
   project_id:  "travelbookingagent-3f53a"    
  }
  type:  "global"   
 }
 severity:  "ERROR"  
 textPayload:  "Dialogflow fulfillment Error: {
  "code": 206,
  "errorType": "partial_content",
  "errorDetails": "Webhook call failed. Error: 404 Not Found"
}"  
 timestamp:  "2018-11-01T11:09:32.992Z"  
 trace:  "5ffd716a-82a6-dacf-9d82-012e6bdeb5af"  
}**

****************************

I am also attaching the index, server and packagejson files as 
Please help 

 
[server.zip](https://github.com/actions-on-google/actions-on-google-nodejs/files/2538492/server.zip)

**Comment by Fleker** [comment]
What fulfillment are you using?

**Comment by khajam30** [comment]
Dear Fleker
The below is the Fullfillment request
********************
{
  "id": "392ab510-70eb-49d6-a1a2-880a1c1b0b05",
  "timestamp": "2018-11-02T02:06:07.873Z",
  "lang": "en",
  "result": {
    "source": "agent",
    "resolvedQuery": "4 northbound",
    "speech": "",
    "action": "bus-requested",
    "actionIncomplete": false,
    "parameters": {
      "busnumber": 4,
      "direction": "northbound"
    },
    "contexts": [],
    "metadata": {
      "intentId": "cdd12462-c149-4522-b37e-9839b9410e8d",
      "webhookUsed": "true",
      "webhookForSlotFillingUsed": "false",
      "isFallbackIntent": "false",
      "intentName": "lookup Bus"
    },
    "fulfillment": {
      "speech": "You have entered in 4 northbound",
      "messages": [
        {
          "type": 0,
          "speech": "You have entered in 4 northbound"
        }
      ]
    },
    "score": 1
  },
  "status": {
    "code": 200,
    "errorType": "success"
  },
  "sessionId": "9e3a4e85-4ba6-8e7c-02ab-35029104f518"
}

***********************

**Comment by Fleker** [comment]
What fulfillment URL did you put in Dialogflow?

**Comment by khajam30** [comment]
https://0i991xgsndql3t1cdbus-appbusmodule.cfapps.us30.hana.ondemand.com/findbus

**Comment by Fleker** [comment]
In the Dialogflow console, under fulfillment, you put the entire URL?

**Comment by khajam30** [comment]
Yes Nick, have used the complete url with /findbus. 

FYI, i have already tested it using webhook on cloud functions usinv the index and packagejson.

But when now when i try this to deploy the code for webhook on a different platform i had to use server.js. 

Thanks for your help, kindky advice

**Comment by khajam30** [comment]
Can anybody suggest a sokutikn

**Comment by entertailion** [comment]
That HTTP URL does not support POST requests:
curl -X POST -v -i 'https://0i991xgsndql3t1cdbus-appbusmodule.cfapps.us30.hana.ondemand.com/findbus'

*   Trying 35.184.169.79...
* TCP_NODELAY set
* Connected to 0i991xgsndql3t1cdbus-appbusmodule.cfapps.us30.hana.ondemand.com (35.184.169.79) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=DE; L=Walldorf; O=SAP SE; OU=SAP Cloud Managed Services; CN=*.cf.us30.hana.ondemand.com
*  start date: Oct 25 00:00:00 2018 GMT
*  expire date: Apr 27 12:00:00 2020 GMT
*  subjectAltName: host "0i991xgsndql3t1cdbus-appbusmodule.cfapps.us30.hana.ondemand.com" matched cert's "*.cfapps.us30.hana.ondemand.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
> POST /findbus HTTP/1.1
> Host: 0i991xgsndql3t1cdbus-appbusmodule.cfapps.us30.hana.ondemand.com
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
< Content-Length: 147
Content-Length: 147
< Content-Security-Policy: default-src 'self'
Content-Security-Policy: default-src 'self'
< Content-Type: text/html; charset=utf-8
Content-Type: text/html; charset=utf-8
< Date: Mon, 05 Nov 2018 16:47:59 GMT
Date: Mon, 05 Nov 2018 16:47:59 GMT
< X-Content-Type-Options: nosniff
X-Content-Type-Options: nosniff
< X-Powered-By: Express
X-Powered-By: Express
< X-Vcap-Request-Id: 9e961036-8bee-4f96-7080-db4e82f33a55
X-Vcap-Request-Id: 9e961036-8bee-4f96-7080-db4e82f33a55

< 
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /findbus</pre>
</body>
</html>
* Connection #0 to host 0i991xgsndql3t1cdbus-appbusmodule.cfapps.us30.hana.ondemand.com left intact

**Comment by khajam30** [comment]
Hi Leon
Thanks for the input, I am new to this. Could you please elaborate and suggest how i can solve this issue.
By the way when i used  the same code for index and package and deployed it in google functions the the fulfillment was working, but now when i deployed it on a different  cloud platform with a additional server js code It doesnt allow. Could you please advice

Thanks

**Comment by entertailion** [comment]
You need to confirm that the platform supports HTTP POSTs. You might only have it configured for HTTP GETs.

**Comment by khajam30** [comment]
Thanks Leon.. 
Do you mean i should update my code with http post or i should check the config of the cloud platform if it is allowing post requests from dialogflow

Thanks

**Comment by khajam30** [comment]
Hi 
I have updated the code to use "app.post", and tried testing it with **curl**. Below are the following outputs. I get a new error **Internal server error**  
Scenario : 1
**********************************************************************
Tried to run only with / as per the below code
  app.post('/findbus', (req, res) => {
          console.log("findbus application triggered");
          myindex.findBus();
    });
Response: 
C:\Users\007394\Downloads\curl-7.62.0-win64-mingw\curl-7.62.0-win64-mingw\bin>cu
rl -X POST -v -i https://0i991xgsndql3t1cdbus-appbusmodule.cfapps.us30.hana.onde
mand.com/findbus
*   Trying 35.184.169.79...
* TCP_NODELAY set
* Connected to 0i991xgsndql3t1cdbus-appbusmodule.cfapps.us30.hana.ondemand.com (
35.184.169.79) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: C:\Users\007394\Downloads\curl-7.62.0-win64-mingw\curl-7.62.0-win64-
mingw\bin\curl-ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=DE; L=Walldorf; O=SAP SE; OU=SAP Cloud Managed Services; CN=*.cf.u
s30.hana.ondemand.com
*  start date: Oct 25 00:00:00 2018 GMT
*  expire date: Apr 27 12:00:00 2020 GMT
*  subjectAltName: host "0i991xgsndql3t1cdbus-appbusmodule.cfapps.us30.hana.onde
mand.com" matched cert's "*.cfapps.us30.hana.ondemand.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
> POST /findbus HTTP/1.1
> Host: 0i991xgsndql3t1cdbus-appbusmodule.cfapps.us30.hana.ondemand.com
> User-Agent: curl/7.62.0
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
HTTP/1.1 500 Internal Server Error
< Content-Length: 148
Content-Length: 148
< Content-Security-Policy: default-src 'self'
Content-Security-Policy: default-src 'self'
< Content-Type: text/html; charset=utf-8
Content-Type: text/html; charset=utf-8
< Date: Tue, 06 Nov 2018 12:17:31 GMT
Date: Tue, 06 Nov 2018 12:17:31 GMT
< X-Content-Type-Options: nosniff
X-Content-Type-Options: nosniff
< X-Powered-By: Express
X-Powered-By: Express
< X-Vcap-Request-Id: 43dbd2c7-defe-4ea1-7cd0-d9afa21d5342
X-Vcap-Request-Id: 43dbd2c7-defe-4ea1-7cd0-d9afa21d5342

<
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Internal Server Error</pre>
</body>
</html>
* Connection #0 to host 0i991xgsndql3t1cdbus-appbusmodule.cfapps.us30.hana.ondem
and.com left intact
*****************************************************************************************************
**Here I get the 500 Internal server error** 




Scenario : 2
**********************************************************************
Tried to run only with / as per the below code
app.post('/', function (req, res) {
   res.send('Hello World');
});
Response: 
curl -X POST -v -i https://0i991xgsndql3t1cdbus-appbusmodule.cfapps.us30.hana.ondemand.com/
*   Trying 35.184.169.79...
* TCP_NODELAY set
* Connected to 0i991xgsndql3t1cdbus-appbusmodule.cfapps.us30.hana.ondemand.com (
35.184.169.79) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: C:\Users\007394\Downloads\curl-7.62.0-win64-mingw\curl-7.62.0-win64-
mingw\bin\curl-ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=DE; L=Walldorf; O=SAP SE; OU=SAP Cloud Managed Services; CN=*.cf.u
s30.hana.ondemand.com
*  start date: Oct 25 00:00:00 2018 GMT
*  expire date: Apr 27 12:00:00 2020 GMT
*  subjectAltName: host "0i991xgsndql3t1cdbus-appbusmodule.cfapps.us30.hana.onde
mand.com" matched cert's "*.cfapps.us30.hana.ondemand.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
> POST / HTTP/1.1
> Host: 0i991xgsndql3t1cdbus-appbusmodule.cfapps.us30.hana.ondemand.com
> User-Agent: curl/7.62.0
> Accept: */*
>
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Content-Length: 11
Content-Length: 11
< Content-Type: text/html; charset=utf-8
Content-Type: text/html; charset=utf-8
< Date: Tue, 06 Nov 2018 12:15:00 GMT
Date: Tue, 06 Nov 2018 12:15:00 GMT
< Etag: W/"b-Ck1VqNd45QIvq3AZd8XYQLvEhtA"
Etag: W/"b-Ck1VqNd45QIvq3AZd8XYQLvEhtA"
< X-Powered-By: Express
X-Powered-By: Express
< X-Vcap-Request-Id: bb0b1c31-ab8a-4dfc-6cd6-0d502b5b3fb2
X-Vcap-Request-Id: bb0b1c31-ab8a-4dfc-6cd6-0d502b5b3fb2

<
Hello World* Connection #0 to host 0i991xgsndql3t1cdbus-appbusmodule.cfapps.us30
.hana.ondemand.com left intact
***********************************************************************************************
Here it looks like the POST works 


Please suggest

**Comment by igilham** [comment]
Your application appears to be crashing after receiving the POST data. This is nothing to do with the SDK but you may find the source of the problem in the logs.

**Comment by khajam30** [comment]
Hello

When I just entered 
https://0i991xgsndql3t1cdbus-appbusmodule.cfapps.us30.hana.ondemand.com/findbus

I get the following 

findbus application triggered
findbus application triggered in indexapp
0i991xgsndql3t1cdbus-appbusmodule.cfapps.us30.hana.ondemand.com - [2018-11-07T04:13:43.595+0000] "GET /findbus HTTP/1.1" 500 0 148 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36" "-" "10.1.9.16:63713" x_forwarded_for:"-" x_forwarded_proto:"https" vcap_request_id:"a6c235af-6aed-40af-71f7-65c073cdff12" response_time:0.020206216 app_id:"638660a0-7f80-40db-a80a-b1c70a63ef01" app_index:"0" x_b3_traceid:"66a6cd435d4638a7" x_b3_spanid:"66a6cd435d4638a7" x_b3_parentspanid:"-"

TypeError: Cannot read property 'result' of undefined
    at DialogflowApp.getIntent_ (/home/vcap/app/node_modules/actions-on-google/dialogflow-app.js:980:20)
    at DialogflowApp.getIntent (/home/vcap/app/node_modules/actions-on-google/dialogflow-app.js:182:25)
    at DialogflowApp.handleRequestAsync (/home/vcap/app/node_modules/actions-on-google/assistant-app.js:529:27)
    at DialogflowApp.handleRequest (/home/vcap/app/node_modules/actions-on-google/assistant-app.js:419:10)
    at Object.exports.findBus (/home/vcap/app/index.js:119:15)
    at app.get (/home/vcap/app/server.js:26:19)
    at Layer.handle [as handle_request] (/home/vcap/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/vcap/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/vcap/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/vcap/app/node_modules/express/lib/router/layer.js:95:5)

**Comment by khajam30** [comment]
Thanks experts issue resolved, 

the application was crashing since the required handler was not getting triggered, I made the code simple by calling app.post and triggering the required function.

Will come back again with new issues

Thanks
