### ISSUE TITLE
MediaObject Pause and Play.

### ISSUE THREAD

**Issue by paigurunath** [actions-on-google/actions-on-google-nodejs#243]
Is there any way to Pause and resume MediaObject using this lib ?

I have a use to implement where i can get the offset of the player and store in database and resume back with the previous offset. It is possible through ask-sdk of Alexa, do we have any alternative solution here.

Thanks
Guru Pai.

**Comment by entertailion** [comment]
The media player does provide controls for the user the play/pause the media. There isn't currently a way to resume the media playback from an offset.

**Comment by maaaaaaaax** [comment]
Due to more than 4 months of inactivity, this issue is being closed.

If you think the resolution is in error, please re-open the request with fresh information.

**Comment by igilham** [comment]
I want this too but it requires platform features that don't exist yet. Might be worth revisiting if and when the platform is more mature.

**Comment by paigurunath** [comment]
Hey my apologies for the delay in response @entertailion & @maaaaaaaax .

Hi @igilham currently Play, Pause is supported by default by the MediaObject. offset is not available for now. As you said we need to wait till the API is going to provide it.

Thanks
Guru Pai.

**Comment by amit-dp** [comment]
There are many dialogflow projects on hold due to lack of these features. Really hope they can implemented quickly.

**Comment by solyarisoftware** [comment]
> The media player does provide controls for the user the play/pause the media. There isn't currently a way to resume the media playback from an offset.

yes @entertailion, but I guess the initial @paigurunath request was about an actions on google programmatic feature. Me too I'd need a way so the user could "barge-in" a media response audio play, to ask something. The audio stream is supposed to pause and resume after the "intent" fulfillment of user request that interrupted audio playing. 

Any news about that possibel enhancement?

Thanks
giorgio
