### ISSUE TITLE
Request for Sample code and Tutorial for AoG-nodejs / Dialogflow / AWS Lambda integration and deployment

### ISSUE THREAD

**Issue by Thomas-A-Reinert** [actions-on-google/actions-on-google-nodejs#248]
Hi! I got my Action fully working with Actions-on-Google-nodejs, Dialogflow and Firebase. Due to project requirements I now need to move the Firebase portion to an AWS Lambda instance and fail miserably in trying to do so.

What I'am painfully missing right now is some simple sample code and tutorial to get this thing to work on Lambda. I read through every Lamdba issue here, but seem to be unable to nail everything together without a little help.

I (and according to some other issues I am not alone) could really need a working example with instructions on how to set up everything up to the last detail. Any hints/RTFM links/code snippets would be deeply appreciated!

**Comment by igilham** [comment]
Most of the discussion on this topic is in #219. There is not yet a released solution or set of documentation to meet your needs but the code samples in there are a good starting point.

The hard part is configuring a REST API in API Gateway to work with the assumptions you are forced to make in the Lambda function's event handler code then setting up the right permissions in the Lambda's execution role.

The execution role needs to let the Lambda function perform `sts:AssumeRole` on the resource `apigateway.amazonaws.com`.

The Gateway Rest API will need to accept HTTP POST requests only. It will also need a request template similar to the below to pass headers to the Lambda function:

```velocity
{
    "application/json": {
        "method": "$context.httpMethod",
        "body" : $input.json('$'),
        "headers": {
            #foreach($param in $input.params().header.keySet())
                "$param": "$util.escapeJavaScript($input.params().header.get($param))"
                #if($foreach.hasNext),#end
            #end
        }
    }
}
```

We really need a fully worked example from Google, but hopefully that'll help you out for now.

**Comment by Thomas-A-Reinert** [comment]
Thanks for your help, Ian.  Found the issue you referred to already, but cannot really make much of it.
The reason why I raised an issue for Sample code/Tutorial that was to make it something like a "ticket" or such.

I'll try to wrap my head around your code, even though I already fear that I won't get too far with it.

**Comment by Thomas-A-Reinert** [comment]
Found a solution to deploy the functions on Lambda using [serverless](https://serverless.com/) which didn't cause any headache and works like a charm. I can really recommend that.

**Comment by chl03ks** [comment]
@Thomas-A-Reinert  can  you share your solution ?

**Comment by Thomas-A-Reinert** [comment]
Sure, @chl03ks , I´ll give it a try. Cannot promise that I can recall everything though, but I´ll try to be as precise as possible. In case you encounter any problems, just holla and I´ll try to reproduce it, okay?

This tut gave me the necessary hints: https://medium.com/@marcorei/developing-for-the-google-assistant-using-typescript-and-amazon-web-services-e7c81df9a436

**Notice:** I converted the whole action to Typescript, so in case you don´t need that, just skip the respective packages etc. It´s not really necessary to get it working.



1. Install all the necessary dependencies from Chapter ["**Serverless Setup**"](https://medium.com/@marcorei/developing-for-the-google-assistant-using-typescript-and-amazon-web-services-e7c81df9a436#5676)
2. Authenticate as described to use your AWS Lambda credentials.
3. Edit `serverless.yml` to your needs.
4. Make sure to exclude _ANYTHING_ not really needed for function exection in `serverless.yml` like documentation / Readme or whatever. Keep things tight for upload - or you´ll may get charged!
5. Run https://medium.com/@marcorei/developing-for-the-google-assistant-using-typescript-and-amazon-web-services-e7c81df9a436#b46c minus the npm install @types/actions-on-google --save-dev part in case you don´t use Typescript.

Sorry, it´s really late already. Need to go to bed, will continue tomorrow.
