### ISSUE TITLE
Dialog Flow not working on live website

### ISSUE THREAD

**Issue by brijkhatri5** [actions-on-google/actions-on-google-nodejs#249]
Hello, I am developing project on dialog flow. I have created a card which shows perfectly on Dialog flow's Console but when implementing the dialog flow live on my website I am not getting the card on my website's dialog flow. Please Help ASAP.

**Comment by Canain** [comment]
Hi, this looks like a question concerning Dialogflow itself not Actions on Google.

Feel free to create a post on Stackoverflow or use the [Dialogflow Node.js fulfillment GitHub issue tracker](https://github.com/dialogflow/dialogflow-fulfillment-nodejs/issues).

**Comment by mishushakov** [comment]
Dialogflow's web integration doesn't support Cards. Use [Dialogflow for Web](https://github.com/mishushakov/dialogflow-web-v2) instead
