### ISSUE TITLE
SSML code ignored when speak tag is used 

### ISSUE THREAD

**Issue by ds8k** [actions-on-google/actions-on-google-nodejs#25]
I have a service that returns a strings with SSML strings in them. If I pass this to the ApiAiAssistant SDK wrapped in a `<speak>` tag, Google Home complete ignores everything inside the <say-as> tag. Is this because the app hasn't been fully deployed?

Examples:

```
const phonetic_name = 'Product <say-as interpret-as="characters">ABC1</say-as> - Bottle';

//  Google Home says: "We found Product less-than say as interpret as equals 
//  characters greater-than A-B-C-1 less-than say as greater-than Bottle"
assistant.ask(`We found ${phonetic_name}`);

//  Google Home says: "We found less-than speak greater-than Product 
//  less-than say as interpret as equals characters greater-than A-B-C-1 less-than
//  say as greater-than Bottle less-than speak greater-than
assistant.ask(`We found <speak>${phonetic_name}</speak>`)

//  Google Home says: "We found Product Bottle"
//  Web simulator response:
//  { "response": "We found Product<unknown word to simulator>- Bottle\n" }
//
//  Further down in the debugInfo:
//  "final_response": {
//    "rich_response": {
//      "items": [{
//        "simple_response": {
//          "ssml": "<speak>We found Product <say-as interpret-as=\"characters\">ABC1</say-as> - Bottle</speak>"
//        }
//      }]
//    }
//  }
assistant.ask(`<speak>We found ${phonetic_name}</speak>`)
```

The last one seems to be the correct way to do this, however in both the simulator and on the Google Home device it's refusing say the things inside the `say-as` tags. Am I doing something wrong?

**Comment by smishra2** [comment]
Yes you're correct that you need to wrap your entire spoken statement in open and close tags (i.e.,  <speak>...</speak>). As for the `say-as` tags, what you have (`assistant.ask('<speak>We found Product <say-as interpret-as=\"characters\">ABC1</say-as> - Bottle</speak>')`) should work. I just tested in the web sim and got the expected result. Try putting this string directly in APIAI as a text response and see if it works there, that might be helpful to debug.

**Comment by ds8k** [comment]
API.AI has no problem reading the string.

```
// Google Home says: "We found Product Bottle"
assistant.tell('<speak>We found Product <say-as interpret-as=\"characters\">ABC1</say-as> - Bottle</speak>');

Response: {
  "response": "We found Product<unknown word to simulator>- Bottle\n",
    "debugInfo": {
      "agentToAssistantDebug": {
        "agentToAssistantJson": {
          "conversation_token": "[]",
            "expect_user_response": false,
            "final_response": {
              "rich_response": {
                "items": [{
                    "simple_response": {
                        "ssml": "<speak>We found Product <say-as interpret-as=\"characters\">ABC1</say-as> - Bottle</speak>"
                    }
                }]
              }
            }
          }
      }
    }
}
```

**Comment by smishra2** [comment]
Hi @ds8k, sorry for the late response on this. I think the issue might be that the SSML transducer doesn't understand 'ABC1' as a character string. Just 'ABC' does work. Try moving the '1' outside the say-as tags. In my testing, I didn't need the say-as tags at all.

**Comment by Swivelgames** [comment]
@smishra2 That sounds like it would become a major problem, especially if "ABC1" is being pulled from a database or outside source of some sort...

**Comment by nominator** [comment]
Any update on this one @ds8k @smishra2 ? I have a long number that I want Google Assistant to speaks as individual digits and it is giving me same 'unknown word to simulator' error.

**Comment by Swivelgames** [comment]
@ds8k @nominator A temporary alternative may be to use a utility function to generate the tags that you need, at least until this bug is **acknowledged** and fixed.

Something similar to this maybe?
```javascript
const sayAsCharacters = (text) => {
    let ret = '';
    let chars = text.split('');
    let c = '';
    while(c = chars.shift()) {
        let prevChar = ret.slice(-1);
        if (isNaN(parseInt(c))) {
            if (!isNaN(parseInt(prevChar)) || !prevChar) {
                ret += ` <say-as interpret-as="characters">`;
            }
            ret += c;
            if (chars.length === 0) ret += `</say-as> `;
        } else {
            if (isNaN(parseInt(prevChar))) ret += `</say-as> ${c}`;
            else ret += ` ${c}`;
        }
    }
    return ret;
};
```

The above produces the following:
```
sayAsCharacters('foo12bar');
" <say-as interpret-as="characters">foo</say-as> 1 2 <say-as interpret-as="characters">bar</say-as> "
```

**Comment by glittle** [comment]
I've got a number like 982968761 that I want to have read as characters: 9 8 2 9 6... not "nine hundred eighty two million, ..."

Using this should work, but doesn't:
````
<speak>
The code is:  <say-as interpret-as="characters">982968761</say-as>
</speak>
````

**Comment by Swivelgames** [comment]
@glittle Please see my solution and let me know if it works for you.

**Comment by glittle** [comment]
I don't think it did. I got what I needed by doing  `'my number'.split('').join(' ')` and it correctly reads the numbers for me.
