### ISSUE TITLE
Table rows cannot have empty strings

### ISSUE THREAD

**Issue by JamesIves** [actions-on-google/actions-on-google-nodejs#250]
I ran into this the other day and it took a really long time to figure out, I'm not really sure if this is a bug or not but figured I'd bring this to your attention.

> Failed to parse Dialogflow response into AppResponse

In my case I was generating a table with some data from an API endpoint like so:

```javascript
const timetableCells = timetable.Trains.map((item) => {
  return {
    cells: [item.Line, item.Destination, item.Car, item.Min],
  }
})

conv.ask(new Table({
  title: `Rail Timetable for ${station}`,
  subtitle: 'Timetable as of x date',
  image: new Image({
    url: 'http://google.com/image.png',
    alt: 'Logo'
  }),
  columns: [
    {
      header: 'Line',
      align: 'LEADING'
    },
    {
      header: 'Destination',
      align: 'LEADING'
    },
    {
      header: 'Car',
      align: 'LEADING'
    },
    {
      header: 'Arrival',
      align: 'LEADING'
    },
  ],
  rows: timetableCells,
  buttons: new Button({
    title: 'Button Title',
    url: 'https://github.com/actions-on-google'
  })
}))
```

The returned data from `timetable` looks like this and the array I'm generating from map followed the correct schema for `rows`, as far as I could tell there should have been no issues as the generated JSON was valid. 

```
{"Trains":[{"Car":"8","Destination":"Glenmont","DestinationCode":"B11","DestinationName":"Glenmont","Group":"1","Line":"RD","LocationCode":"B09","LocationName":"Forest Glen","Min":"9"},{"Car":"8","Destination":"Glenmont","DestinationCode":"B11","DestinationName":"Glenmont","Group":"1","Line":"RD","LocationCode":"B09","LocationName":"Forest Glen","Min":"18"},{"Car":"8","Destination":"Glenmont","DestinationCode":"B11","DestinationName":"Glenmont","Group":"1","Line":"RD","LocationCode":"B09","LocationName":"Forest Glen","Min":"36"},{"Car":"8","Destination":"Shady Gr","DestinationCode":"A15","DestinationName":"Shady Grove","Group":"2","Line":"RD","LocationCode":"B09","LocationName":"Forest Glen","Min":""}]}
```

timetableCells:

<img width="406" alt="screen shot 2018-11-26 at 8 29 13 am" src="https://user-images.githubusercontent.com/10888441/49016897-6ee7cf80-f155-11e8-9cce-17a0c0f2b7ae.png">

DialogFlow kept throwing a JSON parsing error and I couldn't seem to figure out what the issue was, it was obvious to me that the data length needed to match the headers, but what wasn't obvious was that data in row cells **cannot** be empty strings. Sometimes the API endpoint returns empty strings for some data that isn't available yet. I resolved the issue with the following:

```javascript
const timetableCells = timetable.Trains.map((item) => {
  return {
    cells: [item.Line || "N/A", item.Destination || "N/A", item.Car || "TBD", item.Min || "TDB"],
  }
})
```

I spent quite a long time debugging this, and I think this would be a good addition to the [documentation](https://developers.google.com/actions/assistant/responses#table_card) if it's indeed intended and not a bug.

**Comment by JamesIves** [comment]
I tried to address this within this repo but I guess the error isn't being thrown here after looking into the code. I'll gladly post this in the right repository if pointed in the right direction.

**Comment by Fleker** [comment]
The error probably happens on the Google Assistant side after it processes your webhook response.

**Comment by Fleker** [comment]
The server-side parts of the Google Assistant are not open source. Any fixes would need to be done on the side of the developer to validate the input before it is returned (plus adding a note in the documentation).

**Comment by JamesIves** [comment]
Where can I file the bug report?

**Comment by Fleker** [comment]
I can no longer reproduce this. A cell with an empty string will render without throwing an exception.
