### ISSUE TITLE
embed action in website?

### ISSUE THREAD

**Issue by CoreyCole** [actions-on-google/actions-on-google-nodejs#251]
I'm interested in creating a google action for web. By that I mean using a user's own personal microphone interfacing with a web app, not requiring a google home device or android/ios phone. I'm wondering if there are any ideas to bring google actions to some sort of web component or angular plugin.

Or, if there is a way or some path to do it currently, I'd be interested to hear 😄

**Comment by Fleker** [comment]
You can embed a Dialogflow agent [in a web browser](https://dialogflow.com/docs/integrations/web-demo).

**Comment by CoreyCole** [comment]
@Fleker interesting, but I don't think that's exactly what I'm looking for. I'm looking for something handsfree, I.e. saying "hey google" to let the component listen instead of needing to click that microphone button in the dialogflow widget.

**Comment by Fleker** [comment]
That does sound interesting. Currently, I think that's only done in the simulator and not more broadly available on the web. You could try to throw something together with the [Google Assistant SDK](https://developers.google.com/assistant/sdk/overview) but you wouldn't have the hotword detection so you'd need to find some web-based hotword detection library.

**Comment by igilham** [comment]
The closest thing I've seen to this use case is Azure Bot Services, which can be plugged into Google Assistant to build a cross-platform experience if needed.

**Comment by mishushakov** [comment]
@CoreyCole My [Dialogflow for Web](https://github.com/mishushakov/dialogflow-web-v2) supports Actions on Google. Check it out, if you haven't yet
