### ISSUE TITLE
can I set some parameter in NLU process

### ISSUE THREAD

**Issue by Wolke** [actions-on-google/actions-on-google-nodejs#253]
for example:
when I take a flight,
the flight attendant will ask "do you need coffee or tea?"
and the answer is looking for coffee or tea,
even I pronounce   like "key",
the flight attendant still know I  mean "tea",
so is there any way I can set parameter in this?

because I figure out Cloud speech API have this solution.

**Comment by Fleker** [comment]
You can use Dialogflow, which can help with speech biasing.
