### ISSUE TITLE
How to get the userID required for assistant push notification?

### ISSUE THREAD

**Issue by JohannesMaier** [actions-on-google/actions-on-google-nodejs#254]
Recording to [this manual](https://developers.google.com/actions/assistant/updates/notifications#dialogflow), you have to use **conv.arguments.get('UPDATES_USER_ID')** to get the **userID** in "finalize subscription" - Intent. But I am only able to get _undefined_. 
After looking at the **conv**, you can see there in no ID in the whole json:
```
{  
    "parsed":{  
        "input":{  
            "PERMISSION":true
        },
        "list":[  
            true,
            null
        ]
    },
    "status":{  
        "input":{  

        },
        "list":[  
            null,
            null
        ]
    },
    "raw":{  
        "list":[  
            {  
                "textValue":"true",
                "name":"PERMISSION",
                "boolValue":true
            },
            {  
                "name":"text"
            }
        ],
        "input":{  
            "PERMISSION":{  
                "textValue":"true",
                "name":"PERMISSION",
                "boolValue":true
            },
            "text":{  
                "name":"text"
            }
        }
    }
}

```

So how do I get the actual userID.
I also would be pleased if there is the possibity of a broadcast.
Do you know a solutions?

**Comment by JohannesMaier** [comment]
Thanks for the fast respond!

Yes, this is the response after asking for permission. Further details can be found in the comments of the following snipped:
```javascript
google.intent('finish_alarm', conv => {  //Intent which is triggered by the actions_intent_PERMISSION event
    if (conv.arguments.get('PERMISSION')) {  //"conv.arguments.get('PERMISSION')" returns true
        const userID = conv.arguments.get('UPDATES_USER_ID');

        console.log(userID); //undefined
        console.log(JSON.stringify(conv.arguments)); //JSON I already posted

        conv.ask("Ok, I'll start alerting you.");
    } else {
        conv.ask(`Ok, I won't alert you.`);
    }
})


```

**Comment by JohannesMaier** [comment]
@Fleker do you have any idea? I could add you as a alpha tester if you need more details.

**Comment by Fleker** [comment]
I'm not _too_ familiar with the push notification API. It looks to match the snippets. The first thing I think of is that this may be on a smart speaker without voice match, or some account setting that prevents you from actually getting a user id.

**Comment by thomasvt1** [comment]
I too have the same issue

**Comment by JohannesMaier** [comment]
@thomasvt1 Try another account. I tried three accounts and one worked. But I have not yet figured out why the other accounts fail.

**Comment by JohannesMaier** [comment]
I tried both now, but I get different IDs. Did you managed it to get receive notifications with `conv.user.id`?

**Comment by thomasvt1** [comment]
> I tried both now, but I get different IDs. Did you managed it to get receive notifications with `conv.user.id`?

Yes I was able to receive the notification using `conv.user.id` as userId

**Comment by JohannesMaier** [comment]
@thomasvt1 have you tried it with more than ohne account, and does it work?

I tried it with six accounts now, only one of them returns an actuel user_id when using `conv.arguments.get('UPDATES_USER_ID')`, this account does also receive notifications with this ID. 
The other Accounts return a user_id with `conv.user.id` and one of them return an ID like `15444490177063679112345` but none of them receive notifications with those IDs.

Now I am realy confused :/

**Comment by JohannesMaier** [comment]
Is there any way to track those notifications or are they stored in some kind of history or sth?

**Comment by santhosh-ktec** [comment]
Its receiving for first time but not on consequent calls to get permissions for same intent
