### ISSUE TITLE
Depreciated UserId warning not showing when using dashbot

### ISSUE THREAD

**Issue by grctest** [actions-on-google/actions-on-google-nodejs#257]
Dashbot uses userId which is depreciating next year, and if you reference it manually within cloud functions you get a warning message in the cloud function logs, but despite dashbot using the userID this warning isn't showing. Dashbot's userId migration plan is out of scope, but it's interesting to see this warning not trigger.

**Comment by Fleker** [comment]
I think [this is the source](https://github.com/actionably/dashbot/blob/master/src/dashbot-google.js) for Dashbot's NPM module. It seems like they're directly doing parsing on the request, not using this library. This would explain why they aren't running into any warnings.

**Comment by grctest** [comment]
Cool, makes sense, don't think it'd be possible to detect direct request parsing so I'll close this issue. Hopefully Dashbot's got an userId migration plan for next year 🤞
