### ISSUE TITLE
android Auto get GPS location

### ISSUE THREAD

**Issue by Wolke** [actions-on-google/actions-on-google-nodejs#258]
https://play.google.com/store/apps/details?id=com.google.android.projection.gearhead&rdid=com.google.android.projection.gearhead

how to make inside google assistant to get  GPS locations
when call the action I wrote,
action can not get GPS location.
or It is only happen on test version?

**Comment by Fleker** [comment]
Does your action get the location within the Assistant app itself?

**Comment by Wolke** [comment]
no, you can try the app Android Auto.
it look like this App can not get GPS from phone

**Comment by Wolke** [comment]
and the APP Android auto is set to be device not the phone

**Comment by Canain** [comment]
Right now you can only get the phone location on a per use basis through Location Permission.

See [our docs](https://developers.google.com/actions/assistant/helpers#user_information) and [samples](https://github.com/actions-on-google/dialogflow-name-psychic-nodejs/blob/4df026326dfff622473978318667b46aa2c3cc41/functions/index.js#L150) for examples on how to do this.
