### ISSUE TITLE
TableCard not always showing

### ISSUE THREAD

**Issue by grctest** [actions-on-google/actions-on-google-nodejs#259]
The TableCard response does not always show, it shows in the test simulator and generates correctly but it doesn't show for 1 google account despite working for other google accounts.

Correctly displays the following tablecard:
```
{"title":"Group Details","subtitle":"Summary of group activity","rows":[{"cells":[{"text":"Richard"},{"text":"16"},{"text":"1"}],"dividerAfter":true}],"columnProperties":[{"header":"Name"},{"header":"Ratings"},{"header":"Suggested Movies"}]}
```

Not displaying (in Android google assistant, works in test simulator) this tablecard:
```
{"title":"Group Details","subtitle":"Summary of group activity","rows":[{"cells":[{"text":"Ricky"},{"text":"5"},{"text":"3"}],"dividerAfter":true}],"columnProperties":[{"header":"Name"},{"header":"Ratings"},{"header":"Suggested Movies"}]}
```

The TableCard rows are being generated correctly, it shows in the test simulator for the affected user but not in the Android Google Assistant app. Other Google accounts are not similarly affected, does the TableCard require specific Google Assistant settings/permissions to display? I'm not getting any warnings about why it's not displaying.

It's not a severe issue affecting many users, but it's weird that it only affects a subset of the users, without warnings in the Android app only..

**Comment by Fleker** [comment]
Are these Android users using the new UI?

**Comment by grctest** [comment]
@fleker Android 8.0.0, latest production google assistant app, seems to be triggering for some accounts but not others?

**Comment by Fleker** [comment]
So the first table card _always_ shows up on _every_ device, but the second table card _does not_ show up on _any_ device?

This may be an issue with your table. I think you are not putting in as many entries into the table as expected in the second instance. Every cell should have a non-null value.
