### ISSUE TITLE
Support for api.ai webhooks deployed to AWS Lambda

### ISSUE THREAD

**Issue by jhrussell** [actions-on-google/actions-on-google-nodejs#26]
The current constructors require a request and response object, however lambda handlers only have the event/request body.

**Comment by OpenDog** [comment]
https://github.com/actions-on-google/actions-on-google-nodejs/issues/48

**Comment by Canain** [comment]
In [v2 of the library](medium.com/@silvano.luciani/actions-on-google-client-library-for-node-js-v2-0-0-alpha-c92361167f15), we added a better abstraction for request parsing and response generation which allows you to seamlessly use any web framework.

Try it out and let us know what you think so we can polish it up currently during the alpha phase.

**Comment by Canain** [comment]
closing this issue now that v2 is general availability
