### ISSUE TITLE
Parameters are ignored in followup events

### ISSUE THREAD

**Issue by eriklindebratt** [actions-on-google/actions-on-google-nodejs#261]
There appears to be be issues with passing parameters to a followup event. When the followup event is fired, and the intent matching it is triggered, there are no parameters present in any contexts.

For example:
```javascript
conv.followup('my-custom-event-name', { myProp: 'myValue '});
```

Above code will trigger the intent matching the event "my-custom-event-name" but no parameters are included in any contexts.

Seems like the only way to work around this currently is to store parameters in `conv.data`.

Other users are reporting the same issue:
- https://github.com/actions-on-google/actions-on-google-nodejs/issues/64#issuecomment-422072205
- https://github.com/actions-on-google/actions-on-google-nodejs/issues/64#issuecomment-438545077
- https://github.com/actions-on-google/actions-on-google-nodejs/issues/64#issuecomment-438680872

**Comment by andyvanhelsing** [comment]
I have the same issue but then I realized the parameters are added to the EVENT, not the intent. These do not seem present in the conv object, instead they need t be pulled out in the dialogflow console. See https://miningbusinessdata.com/api-ai-tutorial-passing-data-from-browser-localstorage-to-webhooks/

**Comment by Canain** [comment]
Yes, that is correct. The parameters are passed to the intent triggered using the event rather than any specific context.

But like you said, `conv.data` can be a simple alternative to passing data for followup.
