### ISSUE TITLE
Validation error in cloud function logs, but not in test simulator?

### ISSUE THREAD

**Issue by grctest** [actions-on-google/actions-on-google-nodejs#262]
`validation error:  {"success":false,"errors":[{"message":"at least one of [items[0].simpleResponse.displayText or speech or expectedInputs[0].inputPrompt.initialPrompts[0].ssml or expectedInputs[0].inputPrompt.initialPrompts[0].textToSpeech or richResponse.items[0].simpleResponse.displayText or richResponse.items[0].simpleResponse.ssml or expectedInputs[0].inputPrompt.richInitialPrompt.items[0].simpleResponse.textToSpeech or finalResponse.speechResponse.textToSpeech or fulfillmentText or data.google.richResponse.items[0].simpleResponse.displayText or data.google.richResponse.items[0].simpleResponse.ssml or data.google.richResponse.items[0].simpleResponse.textToSpeech or payload.google.richResponse.items[0].simpleResponse.textToSpeech or payload.google.richResponse.items[0].simpleResponse.displayText or payload.google.richResponse.items[1].simpleResponse.textToSpeech or payload.google.richResponse.items[1].simpleResponse.displayText or fulfillmentMessages[0].simpleResponses.simpleResponses[0].textToSpeech or fulfillmentMessages[0].simpleResponses.simpleResponses[0].displayText] needs to be present in post body"}]}`

The above is showing every time I successfully show a list selector with 28 items in it, the error message is not however showing within the test simulator. Sometimes when I click on the list selector it doesn't seem to trigger the inbuilt confirmation intent, possibly unrelated?

Do I need to worry about the above? Could it be interfering with the functionality of the list?

Cheers 👍

**Comment by andyvanhelsing** [comment]
@grctest are you using the conv.followup('EVENT_NAME') method? I've been tracking this error in my code and it seems to occur consistently on the intent that was triggered with the followup function

**Comment by andyvanhelsing** [comment]
From what I've seen this error is benign but should still be fixed to prevent confusion and so it is not taken into account in health metrics

**Comment by andyvanhelsing** [comment]
@grctest are you using dashbot integration? I discovered this line of code while hunting down our bug and it looks like this might be the source of our confusion:
`if (response.status === 400) {
        return response.text().then(function(text)  {
          console.log('validation error: ', text)
          return response
        })
      }`

**Comment by andyvanhelsing** [comment]
I did a little peaking around dashbot and there's a way to turn off statements by adding configurations when dashbot is declared:

const dashbot = require('dashbot')(YOUR_KEY,{printErrors: false}).google;

I have it deployed and it's working so far

**Comment by andyvanhelsing** [comment]
I opened an issue on their github
https://github.com/actionably/dashbot/issues/30
