### ISSUE TITLE
How to set context in AWS Lambda handler? 

### ISSUE THREAD

**Issue by luomanke** [actions-on-google/actions-on-google-nodejs#265]
My code works fine with this code: 
```
const {dialogflow} = require('actions-on-google');
const app = dialogflow();
// bunch of app.intent()
exports.handler = app;
```

Now I want to set `context.callbackWaitsForEmptyEventLoop` in AWS Lambda handler function in order to make my backend code work, and I did some search and tried this: 
```
const {dialogflow} = require('actions-on-google');
const app = dialogflow();
// bunch of app.intent()
exports.handler = async function(event, context) {
    logger.info("got event: " + event)
    context.callbackWaitsForEmptyEventLoop = false;
    try {
        let body = JSON.parse(event.body);
        let headers = event.headers;
        let response = await app.handler(body, headers)
        logger.info(response)
        return response
    } catch (err) {
        logger.info("err: " + err)
    }
}; 
```
The code above provides a good response, but dialogflow received the following: 
> Webhook call failed. Error: 502 Bad Gateway

The documents only give the line `exports.fulfillment = app` which is not informative about how to set the content inside. 

Can someone please help me with this? Any help is appreciated.

**Comment by luomanke** [comment]
Found the solution in #219 : 
```
const app = dialogflow()
app.frameworks.lambda.responder = (event, context, callback, result) => {
  if (result.status >= 200 && result.status < 300) {
    callback(null, result.body)
  } else {
    callback(JSON.stringify(result))
  }
}
// ...
exports.handler = app 
```

Closing this issue.

**Comment by Canain** [comment]
Hi @luomanke currently that code isn't implemented yet in the library. You would have to use something like
```javascript
exports.handler = async (event, context, callback) => {
  const body = event.body || event
  const headers = event.headers || context.request.headers || []
  const result = await app.handler(body, headers);
  if (result.status >= 200 && result.status < 300) {
    callback(null, result.body);
  } else {
    callback(JSON.stringify(result));
  }
}
```

The code in the documentation is for AWS Lambda API Gateway/HTTP Proxy integration.

**Comment by luomanke** [comment]
Hi @Canain , I just found out that my solution is not correct, this part of code is not working (the program is still using the line `exports.handler = app` ): 
```
app.frameworks.lambda.responder = (event, context, callback, result) => {
  if (result.status >= 200 && result.status < 300) {
    callback(null, result.body)
  } else {
    callback(JSON.stringify(result))
  }
}
exports.handler = app 
```
Than I tried the code you provided as well, and it reported and error: `'No intent was provided and fallback handler is not defined.'`

Do you have any idea what might be the issue here? Thanks in advance.

**Comment by igilham** [comment]
Your app can't do anything unless you define either at least one intent or a fallback handler. This is described in the [documentation](https://developers.google.com/actions/dialogflow/fulfillment).

**Comment by luomanke** [comment]
Hi @igilham , thanks for the response. I do have a bunch of intents in my code: 
``` 
const {dialogflow} = require('actions-on-google');
const app = dialogflow();

app.intent('Default Welcome Intent', (conv) => {
    conv.ask('Welcome to my app');
});

// bunch of other intents here as well. 

app.intent('Default Fallback Intent', conv => {
    conv.ask(`I didn't understand. Can you tell me something else?`)
})

exports.handler = async (event, context, callback) => {
  context.callbackWaitsForEmptyEventLoop = false;
  const body = event.body || event;
  const headers = event.headers || context.request.headers || [];
  const result = await app.handler(body, headers);
  if (result.status >= 200 && result.status < 300) {
    callback(null, result.body);
  } else {
    callback(JSON.stringify(result));
  }
}
``` 
If I use `exports.handler = app`, it works perfectly. But somehow in my case `app.handler` did not get these `app.intent()` above.

**Comment by luomanke** [comment]
Found the solution in [this link](https://aws.amazon.com/premiumsupport/knowledge-center/malformed-502-api-gateway/). Basically it's because the line `const result = await app.handler(JSON.parse(body), headers);` provided a JSON object that the AWS API Gateway cannot understand. 

The `result` generated in my code gives: 
``` 
{
        "status": 200,
        "headers": {
            "content-type": "application/json;charset=utf-8"
        },
        "body": {
            "followupEventInput": {
                "name": "ask-something",
                "languageCode": "en"
            }
        }
}
```

But what the API Gateway needs is something like this: 
```
{
        "statusCode": 200,
        "headers": {
            "content-type": "application/json;charset=utf-8"
        },
        "body": "{\"payload\":{\"google\":{\"expectUserResponse\":true,\"systemIntent\":{\"intent\":\"actions.intent.SIGN_IN\",\"data\":{\"@type\":\"type.googleapis.com/google.actions.v2.SignInValueSpec\"}}}}}",
        "isBase64Encoded": false
}
``` 

3 fields went wrong here: 
1. `"status"` should change to `"statusCode"`. 
2. `"body"` is followed by a JSON string instead of an object. 
3. `"isBase64Encoded"` is not defined. 

So the working code is like this: 
``` 
exports.handler = async (event, context) => {
    context.callbackWaitsForEmptyEventLoop = false;
    const body = event.body || event;
    const headers = event.headers || context.request.headers || [];
    const result = await app.handler(JSON.parse(body), headers);
    
    if (result.status >= 200 && result.status < 300) {
        let response = {
            "statusCode": result.status, 
            "headers": result.headers, 
            "body": JSON.stringify(result.body), 
            "isBase64Encoded": false
        }
        return response
    } 
}
``` 

Can someone fix this issue in the library, so that the response generated from `app.handler()` function can be used in AWS API Gateway directly without reformatting.

**Comment by Canain** [comment]
@luomanke The code snippet there is just for people not using the AWS API Gateway mode.

Since you are using that, you should be able to just do
```javascript
exports.handler = app
```

Which will respond in the format you described. When you are using app.handler, you are actually bypassing the lambda response generation and instead get the standard format for a generic web framework and thus need to manually transform the format.

**Comment by luomanke** [comment]
@Canain , you are right, but in my case, I need to set 
```
context.callbackWaitsForEmptyEventLoop = false;
```
 in order to make sequelizejs to work properly in the AWS lambda function. If I use
 ```
 exports.handler = app
 ``` 
there is no clue how to set context, so I have to construct a customized handler.

**Comment by Canain** [comment]
Try to see if this works:

```javascript
app.middleware((conv, framework) => {
  if (framework.lambda) {
    framework.lambda.context.callbackWaitsForEmptyEventLoop = false
  }
})
```

**Comment by luomanke** [comment]
@Canain This works as well. Thanks for your help!
