### ISSUE TITLE
GoogleActionsV2UiElementsListSelectListItem can I set a url for user to click and open url or app

### ISSUE THREAD

**Issue by Wolke** [actions-on-google/actions-on-google-nodejs#268]
https://actions-on-google.github.io/actions-on-google-nodejs/interfaces/actionssdk_api_v2.googleactionsv2uielementslistselectlistitem.html

to be like button

**Comment by entertailion** [comment]
Only the rich responses allow you to provide buttons or links to open URL's: https://developers.google.com/actions/assistant/responses

**Comment by Thomas-A-Reinert** [comment]
To be precise that´s only button in cards, browsing carousel items, suggestions chips and buttons in table cards, correct?
I´d personally also strongly vote to have them in media responses (as button or click on image for visual devices) and lists.
Think of the following scenarios:

- Linking to additional info about the track playing
- Displaying recipes or such in a list

Is there any chance to consider that to be integrated?
