### ISSUE TITLE
MediaObject automatically plays in Simulator, but not on Android

### ISSUE THREAD

**Issue by CoreyCole** [actions-on-google/actions-on-google-nodejs#269]
### Problem
The audio file in a Media Object response automatically starts playing in the simulator, but does not automatically start playing on Android assistant.

### Code
```typescript
app.intent('LaunchRequest', (conv): DialogflowConversation<{}, {}, Contexts> => {
    console.log('[LaunchRequest]');
    conv.ask('Welcome! Starting the audio loop...');
    conv.ask(new MediaObject({
        name: 'piano file loop',
        description: 'testing auto play',
        url: 'https://s3-us-west-2.amazonaws.com/hallooinc/audio/harmony-silent-file_v2.mp3'
    }));
    conv.ask(new Suggestions('cancel'));
    return conv;
});
```

### Environment
I'm using Dialogflow with AWS Lambda for fulfillment. I have not attempted to reproduce this problem using Google cloud functions.
```json
"dependencies": {
        "actions-on-google": "2.5.0",
        "rxjs": "^6.3.3"
},
"devDependencies": {
        "@types/actions-on-google": "1.10.2",
        "@types/aws-lambda": "8.10.15",
        "@types/node": "10.12.11",
        "actions-on-google-testing": "0.2.4",
        "bespoken-tools": "2.1.2",
        "nodemon": "1.18.7",
        "serverless-plugin-bespoken": "0.1.3",
        "serverless-webpack": "5.2.0",
        "ts-loader": "5.3.1",
        "tslint": "5.11.0",
        "typescript": "2.8.3",
        "webpack": "4.26.1",
        "webpack-cli": "3.1.2",
        "webpack-node-externals": "1.7.2"
}
```

### Reproduction Steps
1) Set up an action on Dialogflow 
    - here is my exported Dialogflow project [MediaTester.zip](https://github.com/actions-on-google/actions-on-google-nodejs/files/2725712/MediaTester.zip)
2) Deploy [my fulfillment code](https://github.com/CoreyCole/media-tester/blob/master/src/index.ts) in AWS Lambda, add it as fulfillment for Dialogflow using AWS API Gateway
3) Invoke my two intents in the simulator to see they automatically start the audio file
4) Invoke my two intents on Android to see that the audio file does not automatically start. All the metadata about the audio file is there, as well as the SimpleResponse, but the audio does not start until I manually press the play button.

**Comment by CoreyCole** [comment]
Looks like I jumped the gun on the diagnosis, because neither intents automatically play audio on Android

**Comment by maaaaaaaax** [comment]
Hi Corey! Thanks for reporting this issue. I was able to replicate your code's described behavior, and I've filed an internal feature request that documents your use case.

If you're still facing an issue like this, please consider posting a question on StackOverflow.

**Comment by tobbaumgartner** [comment]
Any updates on this issue? Still doesn't work for me.

**Comment by bonly** [comment]
i had same problem！how to fix it？

**Comment by bonly** [comment]
> your

same problem, how can I fix it ?
