### ISSUE TITLE
Sending cards to devices when using API.AI

### ISSUE THREAD

**Issue by ds8k** [actions-on-google/actions-on-google-nodejs#27]
Is it possible to send cards to users devices when using the SDK? It looks like I can do it within API.AI itself, but can't find any references in the SDK docs.

**Comment by smishra2** [comment]
Hi @ds8k, we just introduced visual components in Actions on Google at IO! You can use them now under the Actions on Google response tab in APIAI, or using the RichResponse builders you can now find in this sample! Check it out!
