### ISSUE TITLE
Whitelist google owned URLs in the openURLAction

### ISSUE THREAD

**Issue by mv288** [actions-on-google/actions-on-google-nodejs#271]
Please refer:
https://github.com/actions-on-google/actions-on-google-nodejs/issues/96

According to

https://developers.google.com/actions/reference/rest/Shared.Types/AppResponse#LinkOutSuggestion

"The URL of the App or Site to open when the user taps the suggestion chip. Ownership of this App/URL must be validated in the Actions on Google developer console, or the suggestion will not be shown to the user. Open URL Action supports http, https and intent URLs. For Intent URLs refer to: https://developer.chrome.com/multidevice/android/intents"

It appears to be a final stance for link out suggestions, however I'm able to use OpenUrlAction within the basic card & carousel item, without verifying ownership of the outbound hyperlink domain.
---
Is there any specific reason OpenUrlAction is disabled only for the LinkOutSuggestion and not the links in other cards?.

If thats the case, can you whitelist Google owned URLs, from Maps, Youtube, Play links etc.,?

**Comment by maaaaaaaax** [comment]
Due to more than 3 months of inactivity, this issue is being closed. 

If you think the resolution is in error, please re-open the request with fresh information.
