### ISSUE TITLE
ActionsSdkApp Response Validation Errors

### ISSUE THREAD

**Issue by poerwiyanto** [actions-on-google/actions-on-google-nodejs#28]
Hi, I got this error message ("expected_inputs[0].possible_intents[0]: intent 'actions.intent.OPTION' is only supported for version 2 and above.") when I used askWithList() in ActionsSdkApp. What should I do?

**Comment by smishra2** [comment]
Hi @poerwiyanto. To help us figure out the issue, could you tell us if you created this project from scratch using the [Actions console](https://console.actions.google.com) or if you used this we a pre-existing project?

**Comment by poerwiyanto** [comment]
Hi, @smishra2. I created this project from scratch using the Actions console. I used the Node.js client library (ActionsSdkApp) and some functions, like ask() and buildInputPrompt(), work well, but whenever I used askWithCarousel() and askWithList(), I got that error message. I tried to run the sample code in https://developers.google.com/actions/reference/nodejs/ActionsSdkApp#askWithList and still got the same error in simulator. Thanks.

**Comment by poerwiyanto** [comment]
Hi, @smishra2. I have updated to version 1.1.1, but the problem remains the same. Is there anything that I missed (like header)? I have also tried response-builder.js to create carousel or list, but nothing worked. Thanks in advance.

**Comment by smishra2** [comment]
Hi @poerwiyanto, sorry for the confusion. Could you try creating a new Actions project, with an identical Action package. But use add `"fulfillmentApiVersion": 2` to your conversation object, so your Action Package is something like this:

```
{
	"actions": [
      {
        "description": "Default Welcome Intent",
        "name": "MAIN",
        "fulfillment": {
          "conversationName": "welcome"
        },
        "intent": {
          "name": "actions.intent.MAIN"
        }
      }
    ],
    "conversations": {
      "welcome": {
        "name": "welcome",
        "url": "https://example.com",
        "fulfillmentApiVersion": 2
      }
    }

}
```

**Comment by smishra2** [comment]
Actually you should be able to update your existing Action Package and Actions project, and then use `gactions test` to push it

**Comment by poerwiyanto** [comment]
Thank you very much. It works!
