### ISSUE TITLE
Say/display something before a helper

### ISSUE THREAD

**Issue by AmineI** [actions-on-google/actions-on-google-nodejs#281]
Hi ! 
Currently, calling a helper (like the sign in helper or the confirmation helper) will skip any "conv.ask" made before, regardless of its type (basic card, table, etc).
(There is an example in #181, like this :
```
conv.ask("You need to Sign In so that the App can better help you")
conv.ask(new SignIn())
```
where the first text will be skipped.)

I'm actually trying to display a basic card before a confirmation request, if a screen is available, and can't find a way to since the confirmation request "overrides" the basic card and any text written.

Is there currently a way to do so without giving up the helper ?

**Comment by lucaswadedavis** [comment]
Hey Aminel! You can pass that string "You need to Sign In so that the App can better help you" as an argument to the SignIn helper itself.

```
conv.ask(new SignIn("You need to Sign In so that the App can better help you"));
```

**Comment by lucaswadedavis** [comment]
The platform just doesn't support multiple responses when using a helper.

**Comment by AmineI** [comment]
Thanks for the suggestion - in my case, as I mentioned I was looking for an actual card that before a confirmation helper, where the text wouldn't be enough I believe. I'll create a confirmation intent manually then

I see ! Thanks for the information, I don't remember noticing that in the AoG plateform docs, so I'll be sure to keep that in mind :) .
