### ISSUE TITLE
unable to set HTTP status in AoG intent handler

### ISSUE THREAD

**Issue by adambezecny** [actions-on-google/actions-on-google-nodejs#286]
hi,

I am trying to sent HTTP header 401 from AoG intent handler. Basically I have implemened OAuth account linking and in particular situation want to revoke the access and force the action to go to authorization endpoint again. I have registered middleware in order to get the access to Express framework response object:

    this.app.middleware((conv: any, framework: any) => {
      return new Promise(resolve => {
        if (framework.express) {
          conv.expressResObject = framework.express.response
        }
        resolve()
      })
    })

and then trying to call within AoG action handler this code:

        return new Promise((resolve, reject) => {
            const _conv  =  this.conv as any
            const expressRes = _conv.expressResObject
            expressRes.status(401).json({ error: 'user_not_found' })
            resolve()
        })

I am getting:

2019-02-11T20:21:55.292Z [server.ts] error: Unahndled promise rejection detected!
2019-02-11T20:21:55.293Z [server.ts] error: Unhandled Rejection at: Promise
2019-02-11T20:21:55.293Z [server.ts] error: Error: Can't set headers after they are sent.

at standard.then.catch (...\node_modules\actions-on-google\dist\framework\express.js:38:38)

Any idea how to sent custom HTTP status from action handler?

**Comment by Canain** [comment]
Hi, now the library supports a clear way to set the HTTP 401 Status code. See #187 for more details.

> Now with [`2.6.0`](https://github.com/actions-on-google/actions-on-google-nodejs/releases/tag/v2.6.0) in [7fb220d](https://github.com/actions-on-google/actions-on-google-nodejs/commit/7fb220d6c5d7e5ce3b61c7bccbeccbc2d73915d2), we added support for returning a HTTP 401 status code by throwing a customized error:
> 
> ```js
> const { dialogflow, UnauthorizedError } = require('actions-on-google')
> 
> const app = dialogflow()
> 
> // If using Actions SDK:
> // const app = actionssdk()
> 
> app.intent('intent', conv => {
>   // ...
> 
>   // given a function to check if a user auth is still valid
>   const valid = checkUserAuthValid(conv)
>   if (!valid) {
>     throw new UnauthorizedError()
>   }
> 
>   // ...
> })
> ```
> 
> This should allow you to respond with this and invalidate the token.
> 
> Let us know if you have any issues.
