### ISSUE TITLE
Execute the request handlers in their own context

### ISSUE THREAD

**Issue by jaibatrik** [actions-on-google/actions-on-google-nodejs#29]
When we set the handlers in the actions map and pass it to `handleRequest`, we don't have an option to pass the context to the executor. See the following code for example - 

```javascript
let teach = new (require('./teach').teach)(admin);

let actionMap = new Map();
    
actionMap.set(ACTION_LEARN, teach.handleRequest);
actionMap.set(ACTION_PRACTICE, check.handleRequest);
actionMap.set(HANDLE_ANSWER, match.handleRequest);

app.handleRequest(actionMap);
```

In the above example, the `handleRequest` methods are called in the context of `ApiApp` (though the `ApiApp` is also passed as an argument to the method) and not in the context of, say `teach` or `check`.

Is there any way of executing the methods in their proper context?

**Comment by Canain** [comment]
It sounds like you want to use the `this` variable inside the handleRequest function to refer to `teach`, `check`, or `match`, is that correct?

If so, then you would want to `bind` the functions like this:
```javascript
let teach = new (require('./teach').teach)(admin);

let actionMap = new Map();
    
actionMap.set(ACTION_LEARN, teach.handleRequest.bind(teach));
actionMap.set(ACTION_PRACTICE, check.handleRequest.bind(check));
actionMap.set(HANDLE_ANSWER, match.handleRequest.bind(match));

app.handleRequest(actionMap);
```

`bind` will bind the `this` variable to whatever you pass to it in the first argument of `bind`

Here's a reliable documentation on the usage of `bind`
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind

Let me know if that's not what you mean

**Comment by jaibatrik** [comment]
Appears to be working. Thanks!
