### ISSUE TITLE
unable to get calling google action reference in google functions

### ISSUE THREAD

**Issue by rrrepos** [actions-on-google/actions-on-google-nodejs#291]
I have **two google actions** that point to the **same google function** as the fulfilment url. The idea being that the google function receive some parameter from each of the **google action url** which will identify itself and the google function takes appropriate action based on it. However, I am unable to get any sort of reference to the calling google action.

I have tried:
```
...
app.middleware((conv, framework) => {
  return new Promise(resolve => {
    if (framework.express) {
      console.log(framework.express.request);
      conv.variable =  .. // update some variable in the conversation
    }
    resolve()
  })
})
...
```

I picked the above suggestion in another issue in this forum but when I look at the contents of the express request it does not show any url. Infact, the `request.originalUrl` shows "/".

What would be the best method to have a common function across multiple actions. Thanks

**Comment by Canain** [comment]
Hi, this seems to be a Cloud Functions issue.

Instead of reading the `originalUrl`, you should try to read from the header data instead.

See this [Stackoverflow post](https://stackoverflow.com/questions/51195552/how-can-i-get-the-hosting-url-instead-of-functions-url-in-firebase-functions-for/51200572#51200572) for more info.

**Comment by rrrepos** [comment]
Thanks @Canain for the reference. However, I find that `x-forwarded-host` and `x-original-url` are not available in the `request.headers`. Pasting the log below

```
{
 insertId:  "000000-2ad56a49-3aef-4a35-9bb6-be867e123ec3"  
 labels: {…}  
 logName:  "projects/<project-id>/logs/cloudfunctions.googleapis.com%2Fcloud-functions"  
 receiveTimestamp:  "2019-03-05T02:54:49.911736883Z"  
 resource: {…}  
 severity:  "INFO"  
 textPayload:  "3 { host: 'us-central1-<project-id>.cloudfunctions.net',
  'user-agent': 'Mozilla/5.0 (compatible; Google-Cloud-Functions/2.1; +http://www.google.com/bot.html)',
  'transfer-encoding': 'chunked',
  'accept-encoding': 'gzip,deflate,br',
  authorization: <auth-string>,
  'content-type': 'application/json;charset=UTF-8',
  'function-execution-id': '8cl34u1ln672',
  'google-actions-api-version': '2',
  'x-appengine-api-ticket': '1de759530ac73aff',
  'x-appengine-city': '?',
  'x-appengine-citylatlong': '0.000000,0.000000',
  'x-appengine-country': 'US',
  'x-appengine-default-version-hostname': 'waa6724a81642cc53-tp.appspot.com',
  'x-appengine-https': 'on',
  'x-appengine-region': '?',
  'x-appengine-request-log-id': '5c7de4f300ff0363790f9b56a50001737e77616136373234613831363432636335332d7470000134633862303838323938363732646631306539663232666665313933393535353a363239000100',
  'x-appengine-user-ip': '64.233.173.140',
  'x-cloud-trace-context': '9f110e188ba212b12537d613f86c5d14/796832618524352505;o=1',
  'x-forwarded-for': '64.233.173.140',
  'x-forwarded-proto': 'https' }"  
 timestamp:  "2019-03-05T02:54:43.393Z"  
 trace:  "<project-id>/traces/9f110e188ba212b12537d613f86c5d14"  
}
```

**Comment by rrrepos** [comment]
@Canain : I was thinking getting the project id of the calling google-action project is similar to what is provided in verification of a project-id during `actionssdk` initialisation. The only difference is we use that option when we wish to verify which project called the function, while I am seeking a way to find out which project is calling the function. Hence the question is: is that attribute available or can it be offered as an enhancement? Thanks

**Comment by rrrepos** [comment]
what seems to have worked is:
1. getting the Authorization header from the express framework.
2. calling the googleapi to decode the token payload.
3. get the actions project id in the aud object.

For 1, as above

```
...
app.middleware((conv, framework) => {
  return new Promise(resolve => {
    if (framework.express) {
      conv.authToken =  framework.express.request.authorization; 
    }
    resolve()
  })
})
...
```
For (2) and (3) used request-promise library

```
const rp = require('request-promise');
var options = {
    uri: 'https://oauth2.googleapis.com/tokeninfo?id_token=' + conv.authtoken,
    headers: {
      'User-Agent': 'Request-Promise'
    },
    json: true
  };
rp(options)
  .then(function(resp) {
    conv.user.storage.projectid = resp.aud; // aud(ience) stores the actions project id
  })
  .catch(function(err) {
    console.log('error:', err);
 });
```

**Comment by rrrepos** [comment]
While the above does not get the url of the request, it gives the project id which helps for my use-case which was: multiple actions project calling the same fulfillment function.
