### ISSUE TITLE
getting and setting raw json with this library

### ISSUE THREAD

**Issue by rrrepos** [actions-on-google/actions-on-google-nodejs#297]
This is a question not an issue. Two related questions.

1. If a conversation response has been created (say a simple response or basic card using this library), is there a way (property or method) to the json response (actions sdk json) that is finally received by the google actions client? Like the one we see in the simulator.

2. And is there a way, again, to set the response to the google actions client if the json is know? Meaning not using the actions sdk (new BasicCard) type of code

Thanks

**Comment by Canain** [comment]
Hi, can you clarify what you want to do for question 1?

If you want to log the json response, you can just pass the option `debug: true` to the service function like:

```javascript
const app = actionssdk({ debug: true })
```

This will log out the request and response.

If you want a way to see how different types of JSON look like, then you can use our [Conversation API Playground](https://developers.google.com/actions/conversation-api-playground) to play around with responses.

For question 2, you can use the `conv.json()` method to set the response.

For example:
```javascript
app.intent('actions.intent.MAIN', conv => {
  conv.json({
    key: 'value',
  })
}) 
```

**Comment by rrrepos** [comment]
Thanks @Canain the answer to Q2 was what you shared. On Q1, I plan to use a (templating) function to build the conversation response (based on some business logic). What I am currently doing is: **passing the conv object** to that function which sets the `conv.ask` content. However, I would prefer that the templating function pass the result to the calling function for which I require q2. 

What I am not able to understand is how the library converts a response to json. For example: if one create a response like `new SimpleResponse({...})` and I pass return it to the intent, can I do something like: 

```
const functionname = (input) => {
  return new Promise( resolve => {
   // some logic to determine the response
    var simpleR = new SimpleResponse({...})
    var basicCard = new BasicCard({..});
    // then perhaps put it in some array
    var arr = [];
   arr.push(simpleR);
   arr.push(basicCard);
  return arr; 
 });
};

app.intent('actions.intent.MAIN', (conv, input) => {
  return functionname(input)
   .then(arr => {
     // how do I render the response
 });
}) 
```

In fact, in my proposed thinking the functionname will be in another server (I am calling it a platform server that holds the business logic for the responses). So the return will be a return from another server that runs express using the request-promise library. My tests of code show that what is returned in the array are some json structure that I cannot directly use the intent logic. 

The only thing I have not tried is to build the responses in the function as json responses (and the playground will definitely help) and send them. But then I thought I am not leveraging the library that has been made to create different responses.

**Comment by rrrepos** [comment]
For example if a simple Response object is created as
```
var simpleR = new SimpleResponse({text: 'hello text', speech: 'hello speech'});
```

It is returned as: `{ textToSpeech: 'hello text', displayText: 'hello speech' }`

How, then can it be used in the intent to set the conversation response to this?

**Comment by rrrepos** [comment]
What I am currently implementing is: creating a response in the webhook function using the json return as above. Something like:

`conv.ask(new SimpleResponse({text:jsonresponse.displayText, speech:jsonresponse.textToSpeech});`

This seems unnecessary and reinventing what the library does. Hence, I am looking at an elegant solution for the above. Thanks

**Comment by Fleker** [comment]
If you look at the [conversation playground](https://developers.google.com/actions/conversation-api-playground) you'll see that the JSON response is wrapped a few times in higher-order fields.

```json
{
  "expectUserResponse": true,
  "expectedInputs": [
    {
      "inputPrompt": {
        "richInitialPrompt": {
          "items": [
            {
              "simpleResponse": {
                "textToSpeech": "Howdy! I can tell you fun facts about almost any number, like 42. What do you have in mind?",
                "displayText": "Howdy! I can tell you fun facts about almost any number, like 42. What do you have in mind?"
              }
            }
          ]
        }
      },
      "possibleIntents": [
        {
          "intent": "actions.intent.TEXT"
        }
      ]
    }
  ]
}
```

**Comment by rrrepos** [comment]
@Fleker : I have studied the json format using the playground. The question I have is: does the library have a way to create this json **before** using it in a conversation. Then, as I have explained above, this can be done by my business layer server and the result can be attached to a conversation by the webhook

**Comment by Canain** [comment]
You can use `conv.serialize()` on a `new ActionsSdkConversation` to generate the entire JSON.

Example:

```javascript
const { ActionsSdkConversation, SimpleResponse } = require('actions-on-google')

const request = {}
const headers = {}

const conv = new ActionsSdkConversation({ request, headers })

conv.ask(new SimpleResponse({
  text: 'hello text',
  speech: 'hello speech'
}))

// copy the json
const json = JSON.parse(JSON.stringify(conv.serialize()))

console.log(JSON.stringify(json, null, 2))
```

**Comment by rrrepos** [comment]
That is perfect, @Canain . Just what I was looking for. Thanks

**Comment by rrrepos** [comment]
Hello @Canain . Need help on just one more thing. While I could get the conversation responses updated via the json as suggested by you, in my use-case I need to update the `user.storage` too by what the business logic function sends.

In my webhook, the following works
```
...
// assume json being sent is: {convresp: ..., userstorage: ...}

conv.json(json.convresp); // this works
conv.user.storage = json.userstorage; // this does not work

Do we need to update the storage fields in the conv response? Thanks

**Comment by Canain** [comment]
Yeah, you would need to update it in the `conv` instance you created beforehand with `new ActionsSdkConversation`.

`conv.json` overrides the entire response

**Comment by rrrepos** [comment]
Thanks @Canain . That helps.
