### ISSUE TITLE
Incompatible with Node < 6.13.0 - package.json is inaccurate

### ISSUE THREAD

**Issue by helmutkian** [actions-on-google/actions-on-google-nodejs#298]
The package.json indicates this library ought to work on Node version >= 6.0.0 (https://github.com/actions-on-google/actions-on-google-nodejs/blob/master/package.json#L10)

However this library has a dependency on `gaxios` which requires a minimum version of 6.13.0, and running the library on version < 6.13.0 results in the error `TypeError: URL is not a constructor at Gaxios.validateOpts`.

The package.json ought to be updated to reflect this.

**Comment by kulinsj** [comment]
Noticing the same behaviour in the [@google-cloud/language](https://www.npmjs.com/package/@google-cloud/language) module

**Comment by Canain** [comment]
Thanks for the report! We will update the package.json version requirement accordingly.
