### ISSUE TITLE
How to get accessToken of user in every request of google assistant in NodeJS?

### ISSUE THREAD

**Issue by iamrahulmaru** [actions-on-google/actions-on-google-nodejs#299]
I'm developing new app in dialogflow using Action On Google.
i've used Account Linking with oAuth with Implicit mode.

How do i get accessToken or user Info (Like email,token) in every request of google assistant in nodeJS?

**Comment by ataillefer** [comment]
Hi, as mentioned in the [documentation](https://developers.google.com/actions/assistant/helpers#getting_the_results_of_the_helper_4), once signed in, the access token is available in the conversation: `conv.user.access.token`.

Hope this helps!

**Comment by iamrahulmaru** [comment]
> Hi, as mentioned in the [documentation](https://developers.google.com/actions/assistant/helpers#getting_the_results_of_the_helper_4), once signed in, the access token is available in the conversation: `conv.user.access.token`.
> 
> Hope this helps!

Thanks
i got it using `conv.request.user.accessToken`
