### ISSUE TITLE
A simple response is required in addition to this type of response

### ISSUE THREAD

**Issue by crispywong** [actions-on-google/actions-on-google-nodejs#300]
Hi,

I am having error when returning fulfillment response (A simple response is required in addition to this type of response).
Following is the **_fulfillmentResponse_**
```
{
  "error": "A simple response is required in addition to this type of response"
}
```
**Information**

> DialogFlow API version: V2 API
> Node version: v8.10.0
> actions-on-google version: ^2.6.0
> body-parser version: ^1.18.3
> express: ^4.16.4
> 

Following is the code snippet
```
const app = express();
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
const agent = dialogflow();
agent.intent("dummyIntent", (conv, input) => {
  if (conv.action === "dummyAction") {
    conv.ask(
      new Carousel({
        items: {
          car: {
            title: "Car",
            description: "A four wheel vehicle",
            synonyms: ["automobile", "vehicle"]
          },
          plane: {
            title: "Plane",
            description: "A flying machine",
            synonyms: ["aeroplane", "jet"]
          }
        }
      })
    );
  }
});

app.post("/webhook", agent);

app.listen(port, () => {
  console.log("Server is up and listening on port" + process.env.PORT);
});
```

I have tried using **new Image()**, **new BasicCard()**, all giving same error.

Your help is much appreciated.

Thanks in advanced.

**Comment by ataillefer** [comment]
Hi, as stated in this [documentation](https://developers.google.com/actions/assistant/responses#visual_selection_responses),
> Visual selection responses have the following requirements and optional properties that you can configure:
> The first item in a visual selection response must be a simple response.

So you need to add something like:
```
conv.ask('Here are some interesting machines:');
conv.ask(
  new Carousel({
    ...
  })
);
```
This will display a chat bubble just before the Carousel.

Regards

**Comment by crispywong** [comment]
Hi @ataillefer ,

Thanks for reply.

I had added line
```
conv.ask("This is category list")
conv.ask(
  new Carousel({
    ...
  })
);
```

**This is the fulfillment response**
```
{
  "payload": {
    "google": {
      "expectUserResponse": true,
      "systemIntent": {
        "intent": "actions.intent.OPTION",
        "data": {
          "@type": "type.googleapis.com/google.actions.v2.OptionValueSpec",
          "carouselSelect": {
            "items": [
              {
                "optionInfo": {
                  "key": "car",
                  "synonyms": [
                    "automobile",
                    "vehicle"
                  ]
                },
                "description": "A four wheel vehicle",
                "title": "Car"
              },
              {
                "optionInfo": {
                  "key": "plane",
                  "synonyms": [
                    "aeroplane",
                    "jet"
                  ]
                },
                "description": "A flying machine",
                "title": "Plane"
              }
            ]
          }
        }
      },
      "richResponse": {
        "items": [
          {
            "simpleResponse": {
              "textToSpeech": "This is category list"
            }
          }
        ]
      }
    }
  },
  "fulfillmentText": "Cannot display response in Dialogflow simulator. Please test on the Google Assistant simulator instead."
}
```

Chat bubble **_"This is category list"_** did not display. Instead it display **_fulfillmentText_** when using the **_"try it now"_** container. Please refer to attached image.
![image](https://user-images.githubusercontent.com/23627899/55148798-e5d4b980-5183-11e9-9613-b255bf2f04d8.png)

When I tried with my device, it did not show any chat bubble. 
I have no idea where does "fulfillmentText" set. I have searched about it, does it related to middleware as mentioned in this [comment](https://github.com/codeforequity-at/botium-core/issues/78#issuecomment-403475666)
```
app.use(conv => {
    const { handler } = conv;
    conv.handler = async function() {
        const res = await handler.apply(this, arguments);
        const { simpleResponse } = res.body.payload.google.richResponse.items.find(item => item.simpleResponse) || {};
        if (simpleResponse) res.body.fulfillmentText = simpleResponse.textToSpeech;
        return res;
    };
});
```

Thanks.

Regards.

**Comment by Fleker** [comment]
When you are sending multiple responses, especially with richer responses, the Dialogflow simulator stops working. You'll want to use the simulator in the Actions console instead to verify the behavior of your action.

**Comment by crispywong** [comment]
Hi,

Thanks for reply, able to display carousel view when using google assistant.

However when I try using **_Telegram_**, it didn't display the list. Does it mean **actions-on-google** can only be implemented in google assistant?

Or any other way I can send rich text response to other channels like **_Facebook_**, **_Telegram_**, **_Skype_**...?

Thanks.

Regards.

**Comment by Fleker** [comment]
The `actions-on-google` library is meant only for Actions on Google. If you want to support a variety of services, you will want to use the [`dialogflow-fulfillment` library](https://dialogflow.com/docs/fulfillment/node-libraries). But some rich responses like carousels may not be available on every platform.
