### ISSUE TITLE
Return responses back to Dialogflow

### ISSUE THREAD

**Issue by mishushakov** [actions-on-google/actions-on-google-nodejs#303]
Hi,
I want to use Actions SDK together with Dialogflow. It works for Google Assistant, but for Dialogflow the response is always `Cannot display response in Dialogflow simulator.  Please test on the Google Assistant simulator instead`. Don't get me wrong, I do understand, that Google Assistant compared to Dialogflow has greater capabilities, like access to user's profile and location. But I do want to receive the responses on Dialogflow though (for my third-party integrations). When working with both Dialogflow NodeJS fulfilment and Actions SDK, I noticed, than the responses are formatted differently. And it's clear for me too, because Dialogflow is built to be cross-platform and some platforms (like messenger) do not have the ability to display some of those components.

What I wish is, if Actions on Google SDK could return the responses back natively to Dialogflow as `ACTIONS_ON_GOOGLE` platform components. What I actually mean by that, is for example if I return a Card with Actions on Google SDK, the card should also be returned in Dialogflow's default `fulfillmentMessages` field and in correct format, instead of the `webhookPayload` and it's own format. I hope for your understanding and wish, that you have wonderful day!

**Comment by Fleker** [comment]
If you want to support multiple platforms through Dialogflow, then you should use the [dialogflow-fulfillment](https://www.npmjs.com/package/dialogflow-fulfillment) library. The Actions on Google library is meant for developers only building Actions.

**Comment by mishushakov** [comment]
Hi, @Fleker thanks for your response. Isn't that a bit disappointing, that I, as developer have to write and maintain my code twice for the same function? One for Actions on Google and one for Dialogflow. I mean I do really want to get both platforms working seamlessly together, but I do not want to do it this way. Im now working on [Dialogflow Gateway](https://dialogflow.cloud.ushakov.co), which is a project, that is trying to address the issue with different formats of responses returned by Dialogflow, so proper third-party integrations could made possible. It has a formatting feature, which is combining all the different types of Dialogflow responses into a single tree, which makes it convenient to draw component-based UI's (like my [Dialogflow for Web](https://github.com/mishushakov/dialogflow-web-v2)).

I have just started working on adding Actions on Google format as well and wanted to know, whether is is maybe possible from your side, to just return the components back to Dialogflow (without having me to make a fork of this library or convert the components by myself). Please let me know, what you think about it. Thanks

**Comment by Fleker** [comment]
You can return responses to Actions on Google using the Dialogflow Fulfillment library, but not all of the AoG components are cross-platform, so you'll still need to do a lot of reformatting to get things to work in a cross-compatible way.

If you want to see a little more of how to get JSON from the various AoG components, you can check out #297.

**Comment by mishushakov** [comment]
Ok, I have successfully integrated Actions on Google format into my Integration. Here a demo: https://app-of-the-day-9a9f6.ui.dialogflow.cloud.ushakov.co

Thanks.

**Comment by kolban-google** [comment]
Late to the party on this question ... when we now look at the dialogflow fulfillment library found here:

https://github.com/dialogflow/dialogflow-fulfillment-nodejs#readme

we see it flagged as

```
Warning: This library is no longer maintained. It should only be used when using the inline editor.
```
