### ISSUE TITLE
Allow routine actions to be added to custom routines

### ISSUE THREAD

**Issue by andreask1** [actions-on-google/actions-on-google-nodejs#305]
Currently it is only possible to add routine actions to ready-made routines such as "Good morning" or "Bedtime".

Please allow routine actions to be added to custom routines as well. Most important, please allow them to be added to routines in the Google Clock app (because with them it is not even possible to add custom commands for integrating third-party actions).

**Comment by maaaaaaaax** [comment]
As a policy, Google doesn't comment on future releases. Please consider submitting a pull request, if you like.
