### ISSUE TITLE
Actions SDK - Is There a Way to Pass a Payload on Suggestions?

### ISSUE THREAD

**Issue by rafapetter** [actions-on-google/actions-on-google-nodejs#306]
Hey guys, I'm trying to send some payload data when the user clicks on a Suggestion chip. But so far I've only found that is possible passing a simple string, representing the Title.

Is there a way to pass this payload/data on Suggestion chips or any other Rich Response alternative?

Thanks

**Comment by Fleker** [comment]
You can store your suggestions and content as a Map in the conversation session data.

```
const suggestionMap = {
  Title: {
     foo: 'bar'
  }
}
conv.ask(new Suggestions(Object.keys(suggestionMap)))
conv.data.suggestions = suggestionMap

// Later
const payload = conv.data.suggestions[suggestion]
```

**Comment by rafapetter** [comment]
Hi @Fleker , good point. Thank you.

The only problem is that if I use the title as some sort of key, I may lose the payload. So for instance, I could have two Suggestion chips with the same title but different payloads.

**Comment by Fleker** [comment]
The suggestion chip itself should have a specific unique label, which you could use as an identifying key. Maybe you structure it like:

const suggestionMap = {
  key1: {
    foo: 'bar'
    title: 'Title'
  },
  key2 {
    foo: 'baz'
    title: 'Title'
  }
}
```

Then you'd need to do an O(N) search through your `conv.data` object, but would allow you to do:

```
conv.ask(new Suggestions(Object.values(suggestionMap).map(obj => obj.title)));
```

**Comment by rafapetter** [comment]
Thanks @Fleker I'll try that =)
