### ISSUE TITLE
[SOLVED] new SignIn() not working at iOS platform

### ISSUE THREAD

**Issue by danihenrique** [actions-on-google/actions-on-google-nodejs#307]
Hello,

We have a Google Assistant App published.
The app uses Link Account Authentication with OAuth Implicit configured.

Inside our intent we check if there is an "accessToken" in the request, if it's not, we call
new SignIn() from const { SignIn } = require('actions-on-google');

It works with Android, the App open a dialog to choose for a Google Account or for a custom login inside the company.
Choosing the second option, the user is redirected to our Auth service, after logged
we are able to catch the accessToken at (originalRequest.payload.user.accessToken);

The problem is using iOS platform, the dialog doesn't show up to choose an account and be redirect, but got an error instead:
```
Assertion response must contain one of 'error' or 'acess_token'
```

We test the App with Android in different devices and all works fine. But
for iOS, we tested with 3 devices (2 iPhone, 1 iPad), and failure as explained above.

How can we make it works for iOS too?

Thanks a lot for any help.

**Comment by henriquekdias** [comment]
I'm having the same issue on an Action I'm working on

**Comment by Canain** [comment]
Hi, thanks for creating this issue!

That error message implies that part of the oauth implement isn't implemented correctly.
Can you verify that ["Check if the Google account is already present in your authentication system"](https://developers.google.com/actions/identity/google-sign-in-oauth#check_if_the_google_account_is_already_present_in_your_authentication_system) is implemented correctly?

On Android, it's possible that the account linking process never hit that scenario which explains why it would work on Android and not iOS.

**Comment by danihenrique** [comment]
Thanks @Canain for your attention!

We solved this problem, changing the "Linking Type" option inside "Google Actions->Account linking".
From: "OAuth & Google Sign In" ----> To: "OAuth".

After that, the user is redirected to our Auth service in both platforms.

Thanks again!

**Comment by sedhalgetstartedspace** [comment]
OAuth & Google Sign In > It's not working on google home mini
