### ISSUE TITLE
incompatible type in DialogflowMiddleware

### ISSUE THREAD

**Issue by panaC** [actions-on-google/actions-on-google-nodejs#308]
Hello,

In dialogflow.ts
The type `DialogflowConversation<{}, {}, Contexts>` is set for conv in middleware : 

```
export interface DialogflowMiddleware<
  TConversationPlugin extends DialogflowConversation<{}, {}, Contexts>
> {
  (
    /** @public */
    conv: DialogflowConversation<{}, {}, Contexts>,

    /** @public */
    framework: BuiltinFrameworkMetadata,
  ): (DialogflowConversation<{}, {}, Contexts> & TConversationPlugin) |
    void |
    Promise<DialogflowConversation<{}, {}, Contexts> & TConversationPlugin> |
    Promise<void>
}
```

I cannot used my own type with : 

`app.middleware<DFConv> ((conv) => {`

May I submit a pull request ?

**Comment by Canain** [comment]
Yeah, feel free to submit a PR with your proposal.

I was testing some various fixes for this and there isn't one best one I found so it would be nice to see what developers would expect.

**Comment by maaaaaaaax** [comment]
In order to quickly identify new issues, I'm closing this issue. Feel free to open this again when you submit a pull request.
