### ISSUE TITLE
transactions.js - setPrice function doesn't work for decimal amounts less than $1

### ISSUE THREAD

**Issue by shivanykshenoy** [actions-on-google/actions-on-google-nodejs#31]
We were experiencing an issue where Tax was not getting displayed in Order Summary.  In troubleshooting, found for example, if units is 0, we're throwing an error 'Invalid units', and not setting the correct value -

Example for tax amount:
amount: { currencyCode: 'USD', units: 0, nanos: 680000000 } 

problem is occurring in this specific code block (see highlighted portion):
![image](https://user-images.githubusercontent.com/3410399/27627031-f1fca78e-5baf-11e7-8138-ef0507f84d39.png)

**Comment by smishra2** [comment]
Hi @shivanykshenoy, great catch! We're working on a fix. In the meantime, we'd recommend changing that conditional statement to:

`if (typeof units !== 'number' || Number.isNaN(units))`

**Comment by shivanykshenoy** [comment]
Will do 👍

**Comment by smishra2** [comment]
This should be fixed now, but reopen if you see any issues
