### ISSUE TITLE
Response error execute intent but google home mini/ google home app always return success

### ISSUE THREAD

**Issue by HayTran94** [actions-on-google/actions-on-google-nodejs#313]
I response error `execute intent `for offline devices like the following code:
```
const {smarthome} = require('actions-on-google');
const app = smarthome();
// ...
app.onExecute((body, headers) => {
  // TODO Send command to device
  return {
    requestId: body.requestId,
    payload: {
      commands: [{
        ids: ["456"],
        status: "ERROR",
        errorCode: "offline"
      }]
    }
  };
});

```
 But google home mini/ google home app say "you got it, turn xxx on/off".

**Comment by Fleker** [comment]
If you log responses with the `debug` option, ie `smarthome({debug:true})`, are you seeing it get to the error flow? There may be something in that logic which means it doesn't get to the offline error.

**Comment by HayTran94** [comment]
Hello @Fleker, I use `debug` option like your suggestion.
With the following response for `execute` intent: 
```
{  
   requestId:'17604075478207596115',
   payload:{  
      commands:[  
         {  
            ids:[  
               20
            ],
            status:'ERROR',
            errorCode:'offline'
         }
      ]
   }
}
```
I will get the following logs: 
```
Response{  
   "status":200,
   "headers":{  
      "content-type":"application/json;charset=utf-8"
   },
   "body":{  
      "requestId":"17604075478207596115",
      "payload":{  
         "commands":[  
            {  
               "ids":[  
                  20
               ],
               "status":"ERROR",
               "errorCode":"offline"
            }
         ]
      }
   }
}
```
So, Is there any error in this case?

**Comment by Fleker** [comment]
It looks like your response is correct, so I'm not sure why it would give a success. What if you set the `status` to `OFFLINE`?

**Comment by HayTran94** [comment]
Hello @Fleker,

I implement that as your suggestion but it's still not working? Might you review that use case for me? 
Thank you very much!

**Comment by Fleker** [comment]
I'm not able to reproduce this issue,

**Comment by HayTran94** [comment]
Hello @Fleker,

My project is still in development stage, has not ever released yet. Does this cause the problem?

**Comment by Fleker** [comment]
That shouldn't be an issue, as I have a few test projects that I use.

**Comment by HayTran94** [comment]
What's wrong with my project? Do you have any suggestion?

**Comment by Fleker** [comment]
This is the body that I've been using successfully. Maybe the `errorCode` should be `deviceOffline`.

```
{
    "requestId": "16687992520954586968",
    "payload": {
      "commands": [
        {
          "ids": [],
          "status": "SUCCESS",
          "states": {}
        },
        {
          "ids": [
            "device"
          ],
          "status": "ERROR",
          "errorCode": "deviceOffline"
        }
      ]
    }
  }
```

**Comment by Sebclem** [comment]
Ok, i have the same problème, and i finally find the solution.
You'r `ids []` need to contain   `string` not `int` so juste use `id.toString`.
It work for me.

**Comment by HayTran94** [comment]
> Ok, i have the same problème, and i finally find the solution.
> You'r `ids []` need to contain `string` not `int` so juste use `id.toString`.
> It work for me.

I'll try following your suggestion. Thank in advance
