### ISSUE TITLE
SYNC requests may not be received on fullfilment, but Successfully linked your xxxx account

### ISSUE THREAD

**Issue by zzy0331** [actions-on-google/actions-on-google-nodejs#314]
After OAuth authentication was passed, I did not receive SYNC, and it was not found in nginx access and error log. I could visit the fulfillment url by curl.

I hope  someone can help me.

![Screenshot_20190411_174434_com google android goo](https://user-images.githubusercontent.com/32786684/55948205-96fa4a00-5c82-11e9-9163-e48c66792c1f.jpg)
![TIM截图20190411194544](https://user-images.githubusercontent.com/32786684/55954876-71753c80-5c92-11e9-8f1d-f2aa5763c76e.png)

**Comment by Fleker** [comment]
It looks like the linking worked. You could try unlinking and relinking, or saying "Hey Google, sync my devices".

**Comment by zzy0331** [comment]
> It looks like the linking worked. You could try unlinking and relinking, or saying "Hey Google, sync my devices".

I've tried many times, but it also did not work, View log  is INTERNAL_ERROR

**Comment by Fleker** [comment]
If authentication works, but there is an error with the SYNC request, you should check how your SYNC request is being generated and handled to ensure it is free of errors and responds in a timely manner.
