### ISSUE TITLE
Actions SDK IntentHandler not found

### ISSUE THREAD

**Issue by rrrepos** [actions-on-google/actions-on-google-nodejs#315]
I have a **reasonably** stable google actions project running using actions sdk. However, I find that intermittently I get a Actions SDK Handler error. I set debug to true and found that just before it occurs, the request object is blank `{}`. This does not happen for any particular conversation thread or request. Often, after some 15 or 20 requests.

Prior to the point of the errors the log shows (when it works)
`Request { "user": { "userId": "ABw ....`

while just before the error, the log shows
`Request {}`

I have posted on so too: 
https://stackoverflow.com/questions/55811762/google-actions-actions-sdk-intenthandler-not-found-for-intent

Are there any clues or direction for me to deep dive to know why this would happen? I will appreciate any help. Thanks

**Comment by rrrepos** [comment]
Despite the randomness with which this issues occurs it **does** occur. I am wondering if there is some likely reason why the request object is blank. Any help will be useful. Thanks

**Comment by Canain** [comment]
Hi, to help debug this, are you able to deploy this to another Node.js hosting solution?

The issue could be something to do with Firebase Functions or Actions SDK, so it would be good to try to isolate the problem.

**Comment by rrrepos** [comment]
ok @Canain. Will set up something on AWS and report back if the problem shows up. Thanks

**Comment by rrrepos** [comment]
In case it helps this is the full error message
```
Error: Actions SDK IntentHandler not found for intent: at Function.<anonymous> (/srv/node_modules/actions-on-google/dist/service/actionssdk/actionssdk.js:128:31) at Generator.next (<anonymous>) at /srv/node_modules/actions-on-google/dist/service/actionssdk/actionssdk.js:22:71 at new Promise (<anonymous>) at __awaiter (/srv/node_modules/actions-on-google/dist/service/actionssdk/actionssdk.js:18:12) at Function.handler (/srv/node_modules/actions-on-google/dist/service/actionssdk/actionssdk.js:86:16) at Object.<anonymous> (/srv/node_modules/actions-on-google/dist/assistant.js:55:32) at Generator.next (<anonymous>) at /srv/node_modules/actions-on-google/dist/assistant.js:22:71 at new Promise (<anonymous>)
```

**Comment by GledsonAfonso** [comment]
Don't know if someone will see this, but I was facing a similar problem, but manage to fix it exchanging this:

`const {actionssdk} = require('actions-on-google');`

for this:

`const {dialogflow} = require('actions-on-google');`

Hope this helps.
