### ISSUE TITLE
TypeError: smarthome is not a function

### ISSUE THREAD

**Issue by kirantpatil** [actions-on-google/actions-on-google-nodejs#317]
We are trying to implement Report State API.

Now we are getting below issue, which we could not resolve.

Could you please help us to resolve this issue ?

We have added below lines to openhab.js file

const {smarthome} = require('actions-on-google');
const app = smarthome({
});

Please find the below console output.

smartfueb_march_gmail_com@instance-1-ubuntu16:/home/smartfueb_march/openhab-google-assistant/functions$ gcloud beta functions deploy openhabGoogleAssistant --stage-bucket smart_test1 --trigger-http

Deploying function (may take a while - up to 2 minutes)...failed.
ERROR: (gcloud.beta.functions.deploy) OperationError: code=3, message=Function failed on loading user code. Error message: Code in file index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: TypeError: smarthome is not a function
at Object.<anonymous> (/user_code/openhab.js:23:13)
at Module._compile (module.js:577:32)
at Object.Module._extensions..js (module.js:586:10)
at Module.load (module.js:494:32)
at tryModuleLoad (module.js:453:12)
at Function.Module._load (module.js:445:3)
at Module.require (module.js:504:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/user_code/index.js:18:17)
at Module._compile (module.js:577:32)

**Comment by Fleker** [comment]
Which version of `actions-on-google` are you using?

**Comment by kirantpatil** [comment]
We are using “actions-on-google” version “2.6.0”

**Comment by Fleker** [comment]
How are you mapping the `smarthome` object to a cloud function? Using gcloud instead of the Firebase CLI may require you to change the way it is configured, which may be causing the error.

**Comment by kirantpatil** [comment]
We are implementing ReportState API at https://github.com/openhab/openhab-google-assistant

**Comment by Canain** [comment]
The current version seems to have `smarthome` included correctly.

```bash
$ npm install actions-on-google
$ node
> typeof require('actions-on-google').smarthome
'function'
```

I would double check that you are looking at the right `package.json`.

Try logging the actual version loaded with:

```javascript
console.log(require('actions-on-google/package.json').version)
```

Make sure it is `2.6.0`

**Comment by kirantpatil** [comment]
We could resolve the issue of smarthome is not function by using  below commands and changing the package.json file to 2.6.0.

$ sudo npm install -g actions-on-google@latest

**Comment by kirantpatil** [comment]
@Canain, we again revisited as per your suggestion and that was the issue.
