### ISSUE TITLE
Standard practice to save a response

### ISSUE THREAD

**Issue by lemonbuzz** [actions-on-google/actions-on-google-nodejs#318]
I would like to know if there are any standard or common practices for handling cases where the user asks to repeat the last response. I searched the docs and haven't found anything.

I'm currently migrating v1 to v2 and the last step is to migrate our "Repeat" handler.
In the v1, the strategy we used was to simply store the responses in the app data object and retrieve the last one, whether it was a simple string response or a rich one returned from a builder.

The problem I am facing now though is that when I try to send a **rich response** (simple strings work) which have been retrieved from conv data, the response doesn't seem to go through and to top it all off, I don't get any error outputs, just the Google Assistant simulator saying the agent isn't responding. The only thing I can suspect is that when I store the data, it is stored as plain JSON so when I retrieve it, it doesn't have its type anymore ( Carousel, SimpleResponse, BasicCard, etc... ). I have no idea if this has an impact or not since i'm no expert in TS/JS

Some pointers would be appreciated, but also confirming the approach is the right one or not would be nice to know too.

Thank you

**Comment by Canain** [comment]
This is a result of the v2 library now representing the RichResponse item types directly instead of a RichResponse item containing the property for the type.

v1 object
```json
{
  "simpleResponse": {
    "displayText": "How are you?"
  }
}
```

v2 serialized object
```javascript
JSON.stringify(new SimpleResponse({
  displayText: 'How are you?',
}), null, 2);
```
```json
{
  "displayText": "How are you?"
}
```

As you can see, in v2 manipulating the object is simpler as you can just directly access the properties in the top level, but as a result, it no longer contain the type information.

But good news! You can use the `RichResponse` class to serialize it correctly so you can store the items later on.

Something like this should work:
```javascript
const { RichResponse }  = require('actions-on-google')
// ...

// save items to conv.data
const items = [
  new SimpleResponse({
    displayText: 'How are you?',
  }),
]

const response = new RichResponse(items)
conv.data.items = response.items

// load items from conv.data

conv.ask(...conv.data.items)
```

**Comment by lemonbuzz** [comment]
Thank you for the response! It is very appreciated. We ended up simply not repeating the rich response as we felt it didn't add much value. We simply store the speech and repeat it on demand.
