### ISSUE TITLE
Support for newer Node releases?

### ISSUE THREAD

**Issue by grctest** [actions-on-google/actions-on-google-nodejs#319]
I got an email from Google cloud functions stating the following:

> We're writing to let you know that the Node.js 6 runtime on Cloud Functions is deprecated and will be decommissioned on April 22, 2020. To avoid any potential disruptions or security risks, please update your functions to use the Node.js 8 (generally available) or Node.js 10 (beta) runtimes as soon as possible.

This repo only supports v6 at the moment, right?

**Comment by Fleker** [comment]
No, you can build Actions using Node 8. Many of our samples have been updated to use Node 8.

**Comment by Canain** [comment]
If you check the [`package.json`](https://github.com/actions-on-google/actions-on-google-nodejs/blob/bc2eb49dfc8c46bcba8410d9c3dc0bbb874036f8/package.json#L10), you can see that it supports Node 6 **and above**:

```json
  "engines": {
    "node": ">=6.13.0"
  },
```
