### ISSUE TITLE
Persisting data across intents

### ISSUE THREAD

**Issue by copperstick6** [actions-on-google/actions-on-google-nodejs#32]
I'm working on an application that needs data to be persistent across intents (i.e., data calculated in one intent and then that data used in the next intent). How would I go about doing this? (I'm using API.ai).

**Comment by entertailion** [comment]
The client library provides a convenient storage mechanism to store data within a session. Use "app.data" to store JSON values that can then be retrieved by the intent handlers of subsequent parts of the conversation.

**Comment by seep** [comment]
I had some issues getting this feature to work. Data stored on `app.data` wasn't persisted until I created shared input & output contexts for the intents in Dialogflow; is this intended?
