### ISSUE TITLE
TS2339: Property 'status' does not exist on type 'string | number | boolean | GoogleActionsV2DateTime | ApiClientObjectMap<any> | GoogleActionsV2Location | GoogleRpcStatus'.

### ISSUE THREAD

**Issue by iamsayantan** [actions-on-google/actions-on-google-nodejs#323]
Hi, I am getting this error during account linking. Account linking is successfully done, but while I check for `signin` status in the intent I get the above error.

```
dialogFlowApp.intent('sign_in', (conv, params, signIn) => {
    if(signIn.status === 'OK') {
        conv.ask('Your account is successfully linked with google.');
    } else {
        conv.end('No worries. You can always come back and link your account.');
    }
  })
```
And I get compilation error for this,

> TSError: ⨯ Unable to compile TypeScript:
> src/assistant/index.ts(35,37): error TS2339: Property 'status' does not exist on type 'string | number | boolean | GoogleActionsV2DateTime | ApiClientObjectMap<any> | GoogleActionsV2Location | GoogleRpcStatus'.
>   Property 'status' does not exist on type 'string'.
> 
>     at createTSError (/var/www/secnyx/node_modules/ts-node/src/index.ts:261:12)
>     at getOutput (/var/www/secnyx/node_modules/ts-node/src/index.ts:367:40)
>     at Object.compile (/var/www/secnyx/node_modules/ts-node/src/index.ts:558:11)
>     at Module.m._compile (/var/www/secnyx/node_modules/ts-node/src/index.ts:439:43)
>     at Module._extensions..js (module.js:671:10)
>     at Object.require.extensions.(anonymous function) [as .ts] (/var/www/secnyx/node_modules/ts-node/src/index.ts:442:12)
>     at Module.load (module.js:573:32)
>     at tryModuleLoad (module.js:513:12)
>     at Function.Module._load (module.js:505:3)
>     at Module.require (module.js:604:17)
> 
I've checked the sample repo for account linking, and this is the way its been done. What am I doing wrong?

**Comment by Canain** [comment]
Since you are using TypeScript, you need to specify the type of the argument `signIn`.

You can do this by importing the `SignInArgument` type and passing it as a generic parameter to the `intent` method. Also, `conv.end` should be `conv.close`.

```typescript
import { dialogflow, SignInArgument } from 'actions-on-google';

const app = dialogflow();

app.intent<SignInArgument>('sign_in', (conv, params, signIn) => {
  if(signIn.status === 'OK') {
    conv.ask('Your account is successfully linked with google.');
  } else {
    conv.close('No worries. You can always come back and link your account.');
  }
});
```

**Comment by iamsayantan** [comment]
Thank you. Makes it clear now.
