### ISSUE TITLE
MediaObject does not appear but plays sound

### ISSUE THREAD

**Issue by konradowy** [actions-on-google/actions-on-google-nodejs#326]
I've just noticed that all agents using MediaObject does not appear the object (with picture and progress bar) but plays sound. Both platforms: iOS and Android. 

Action's Simulator shows the object correctly.

**Comment by Fleker** [comment]
On Android, do you see a media player notification appear?

**Comment by konradowy** [comment]
notification was ok. 
Seems that problem is fixed already.
