### ISSUE TITLE
dialogflow webhook integrated with hangouts chat is not working properly

### ISSUE THREAD

**Issue by Sampoorna12S** [actions-on-google/actions-on-google-nodejs#327]
I have connected dialogflow with the hangouts chat. By enabling the webhook in dialogflow for a intent, from firebase i am getting the response as per that intent in dialogflow test app,but that response is not showing in hangouts chat.Is there any specific format for sending response to hangouts chat from dialogflow?

This is the code i have tried:

const functions = require('firebase-functions');
const app = dialogflow({debug: true});
const {dialogflow, BasicCard, Permission, Suggestions,} 
=require('actions-on-google');
app.intent('id', (conv, {name}) =>
 {
  conv.close(`People here are always available.So,you can call ${name} anytime`)
});

**Comment by Fleker** [comment]
The Actions on Google is not expected to work with Hangouts Chat. They're different platforms. In this case, you'd want to go to the more generic [Dialogflow fulfillment library](https://github.com/dialogflow/dialogflow-fulfillment-nodejs).

**Comment by maaaaaaaax** [comment]
Please reopen this issue if you have new information to add!
