### ISSUE TITLE
Selecting from a list doesn't work if the text is in Hebrew

### ISSUE THREAD

**Issue by ofekashery** [actions-on-google/actions-on-google-nodejs#328]
I do not know where I'm supposed to report it...

### English item (Request from Google)
![image](https://user-images.githubusercontent.com/16443111/59263045-07085a80-8c49-11e9-861f-b5a162621d7c.png)

### Hebrew item (Request from Google)
![image](https://user-images.githubusercontent.com/16443111/59262988-ee984000-8c48-11e9-9ff4-2306ccfa302a.png)

It's the same ``listSelect``.

**Comment by sarahdwyer** [comment]
Unfortunately, Hebrew isn't currently a supported locale.

**Comment by ofekashery** [comment]
I'm not sure it's related, it's just comparing strings.
