### ISSUE TITLE
Unable to retrieve verification certificates

### ISSUE THREAD

**Issue by davedodea** [actions-on-google/actions-on-google-nodejs#331]
For the past few hours, I have been getting the following error when launching a nodejs webhook which sevices a Actions on Google/DialogFlow agent. Looks like it can't exhange the client tokens, may be that there is an outage, but I don't see any reports online:

```
Error: connect ETIMEDOUT 74.125.193.95:443
    at OAuth2Client.<anonymous> (.../node_modules/google-auth-library/build/src/auth/oauth2client.js:580:31)
```

**Comment by Fleker** [comment]
Are you doing any specific OAuth in your Action? I can open a generic Action without an issue.

**Comment by davedodea** [comment]
Account linking - issue seems to be resolved now. I think it was local to my region (Dublin, IRE).
Closing
