### ISSUE TITLE
Disable unnecessary logs

### ISSUE THREAD

**Issue by ravirupareliya** [actions-on-google/actions-on-google-nodejs#332]
I am using this library firebase-cloud-functions. I just want to delete logs which are defaultly logged into console.

![Untitled](https://user-images.githubusercontent.com/17959204/59972883-abc55900-95b4-11e9-99ae-b0135d638710.png)

As you can see in above image logs like `Response` , `Conversation`, `Headers`, `Request`. I have not written those logs in my function.

How can I disable it?

**Comment by Fleker** [comment]
You may be adding a debug flag in your Actions on Google constructor:

`const app = dialogflow({ debug: true })`

If you don't include this field, the logs won't happen.

**Comment by ravirupareliya** [comment]
@Fleker Yes that worked, Thank you :)
