### ISSUE TITLE
Parse exception in web-hook node js app [body value is undefined]

### ISSUE THREAD

**Issue by nagesh007** [actions-on-google/actions-on-google-nodejs#34]
Hi,

I have attached a web-hook to my actions app. Whenever i was testing the app from actual google home and simulator "web-hook" code was crashing

undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
at JSON.parse (<anonymous>)
at ApiAiApp.AssistantApp (/data/app/node_modules/actions-on-google/assistant-app.js:128:23)
at ApiAiApp (/data/app/node_modules/actions-on-google/api-ai-app.js:78:5)
at Server.<anonymous> (/data/app/app.js:16:13)
at Server.<anonymous> (/data/app/node_modules/engine.io/lib/server.js:472:22)
at Server.<anonymous> (/data/app/node_modules/socket.io/lib/index.js:307:16)
at emitTwo (events.js:125:13)
at Server.emit (events.js:213:7)
at parserOnIncoming (_http_server.js:602:12)
at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)

Later i tried printing body of the request  but  it was printing undefined.
Why google is not sending data to web-hook?

**Can you please help? Thanks in advance**

**Comment by smishra2** [comment]
How have you deployed your webhook? The client library assumes an [Express](http://expressjs.com/en/api.html#req.body)-like request body, as is used in [Cloud Functions for Firebase](https://firebase.google.com/docs/functions/http-events), for instance.

**Comment by nagesh007** [comment]
Hi,

Thanks for the reply. I tried with both the approaches , one with express and another one without express.  With express also error was visible. I will try once again with express and get back to you with logs.


Some more details : 
--------------------------
I have hosted in 2 places.  

* Even node hosting.
* Go-daddy cloud server hosting.

_Note: I tested in both_

**Comment by nagesh007** [comment]
Hi,

I enabled express https server code.

Now API.AI is unable to communicate with my web-hook. I didn't receive any request at server side.

I am listening to port number : 443

Please check the JSON response in API.AI
```

{
  "id": "455b5241-353b-4f7a-a5c7-964b3e88cdb3",
  "timestamp": "2017-07-16T10:53:19.621Z",
  "lang": "en",
  "result": {
    "source": "agent",
    "resolvedQuery": "volume up",
    "action": "volume",
    "actionIncomplete": false,
    "parameters": {
      "percentage": "",
      "volume_operation": ""
    },
    "contexts": [],
    "metadata": {
      "intentId": "2feb27ec-f6fd-46a2-ba9d-81b077dd0804",
      "webhookUsed": "true",
      "webhookForSlotFillingUsed": "true",
      "intentName": "volume"
    },
    "fulfillment": {
      "speech": "",
      "messages": [
        {
          "type": 0,
          "speech": ""
        }
      ]
    },
    "score": 1
  },
  "status": {
    "code": 206,
    "errorType": "partial_content",
    "errorDetails": "Webhook call failed. Error: 404 Not Found"
  },
  "sessionId": "b8bc03fd-a7ea-4e96-82c9-21352c4a6672"
}
```

Note: I have socket io code also [but now i have commented the socket-io code]


Can you please help ?

**Comment by afirstenberg** [comment]
That the call was working before (you got the exception) and isn't now suggests that you've changed the URL for the endpoint or something along those lines. Without seeing your configuration, it is pretty hard to diagnose.

**Comment by nagesh007** [comment]
Code :
```
var express=require('express');
var expressApp=express();
const fs = require('fs');


// related to ssl
var key = fs.readFileSync('encryption/nagesh1989.key');
var cert = fs.readFileSync( 'encryption/5014f700263908f.crt' );
var ca = fs.readFileSync( 'encryption/gd_bundle-g2-g1.crt' );

var sslOptions = {

  key: key,

  cert: cert,

  ca:ca

};

const App = require('actions-on-google').ApiAiApp;


expressApp.get('/home', function(request,response)
{

  console.log("Route access ");
  /*
  Google Actions
  */

  const app = new App({request: request, response: response});

  function tvSearch(app)
  {
    console.log("Search");
    app.ask("thanks for searching");
  }

  // map request
  const actionsMap=new Map();
  actionsMap.set('tv_search',tvSearch);
  app.handleRequest(actionsMap);

});

var server=require('https').createServer(sslOptions,expressApp);
server.listen(443);
```

**Comment by entertailion** [comment]
Is the cert self-signed? You cannot use self-signed certs for doing HTTPS for the fulfillment URL.

**Comment by nagesh007** [comment]
Certificate is not self-signed

**Comment by entertailion** [comment]
Are you seeing the incoming requests in your server logs?

**Comment by nagesh007** [comment]
No but if we fire URL from web-browser logs are coming. Any solution ?

**Comment by entertailion** [comment]
Double-check that the fulfillment URL is configured correctly. Use curl to check that the URL is good for a Conversational API request.

**Comment by nagesh007** [comment]
I am able to access via curl.  Please suggest

**Comment by entertailion** [comment]
Have you tried using ngrok to use a locally hosted server? This is to eliminate any hosting configuration issues you might have.

**Comment by zpv** [comment]
Install and make express use `body-parser`
It will not handle the response correctly without it.

**Comment by nagesh007** [comment]
Hi all,

Sorry for the inconvenience caused.

I was trying different methods to debug,  finally I realized that  I had given GET request instead of POST request. I am really sorry.  Server is able to receive the request but same parse exception is coming 

```
SyntaxError: Unexpected token u in JSON at position 0
    at Object.parse (native)
    at ApiAiApp.AssistantApp (/home/nagesh1989/goldenbox/node_modules/actions-on-google/assistant-app.js:129:23)
    at ApiAiApp (/home/nagesh1989/goldenbox/node_modules/actions-on-google/api-ai-app.js:76:5)
    at /home/nagesh1989/goldenbox/app.js:38:15
    at Layer.handle [as handle_request] (/home/nagesh1989/goldenbox/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/nagesh1989/goldenbox/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/nagesh1989/goldenbox/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/nagesh1989/goldenbox/node_modules/express/lib/router/layer.js:95:5)
    at /home/nagesh1989/goldenbox/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/nagesh1989/goldenbox/node_modules/express/lib/router/index.js:335:12)
```

**Please help me to solve this .**  
I will explore on body-parser [ @zpv  thanks ]

**Comment by nagesh007** [comment]
_@zpv_  Thanks I am able to speak with my server from google home simulator. I used **_body-parser_**. It worked

**Thanks to  _@entertailion_ ,  _@afirstenberg_  and  _@smishra2_  for support.**
