### ISSUE TITLE
Old googleapis dependency with vulnerabilities

### ISSUE THREAD

**Issue by rullan939** [actions-on-google/actions-on-google-nodejs#341]
Doing 'npm audit' in the project reports 1 high severity vulnerability:

High          │ Improper Authorization
Package    │ googleapis
Patched in │ >=38.0.0
Dependency of │ actions-on-google
Path          │ actions-on-google > googleapis
More info     │ https://npmjs.com/advisories/791

**Comment by Fleker** [comment]
We're aware of this. @Canain is working on an update.

**Comment by Canain** [comment]
This is now fixed with 2.9.0 in 6988e867767d97c614393e734558af523bbe8e81
