### ISSUE TITLE
code = InvalidArgument desc = Request contains an invalid argument.

### ISSUE THREAD

**Issue by fbens** [actions-on-google/actions-on-google-nodejs#343]
**Error Code**
When I call the [ReportStateAndNotification](https://developers.google.com/actions/smarthome/reference/rpc/google.home.graph.v1#google.home.graph.v1.HomeGraphApiService.ReportStateAndNotification) rpc function, it return this error all the time.
```shell
error: rpc error: code = InvalidArgument 
desc = Request contains an invalid argument.
```

**Data Send**
test1
```json
{
	"request_id": "ff36a3cc-ec34-1e6-b1a0-64510650abcf",
	"agent_user_id": "2476592",
	"payload": {
		"devices": {
			"states": {
				"2251959347": {
					"on": true
				}
			}
		}
	}
}
```

test2
```json
{
	"requestId": "ff36a3cc-ec34-11e6-b1a0-6451065abcf",
	"agentUserId": "2476592",
	"payload": {
		"devices": {
			"states": {
				"2251959347": {
					"on": true
				}
			}
		}
	}
}
```
This error show all the time no matter  data I sended with name `agent_user_id` or `agentUserId` like above. but I was writted according to the official example [ReportStateAndNotificationRequest](https://developers.google.com/actions/smarthome/reference/rpc/google.home.graph.v1#google.home.graph.v1.ReportStateAndNotificationRequest) the parameters send example like below. I am so confused what parameters should I sended

![屏幕快照 2019-07-21 13 14 57](https://user-images.githubusercontent.com/1414939/61587275-91819980-abb9-11e9-9abc-5a3db4707e88.png)

**Comment by Fleker** [comment]
Is the agentUserId a valid id? Does the device have the OnOff trait?

**Comment by fbens** [comment]
@Fleker 
It's an valid agentUserId and the device has `action.devices.traits.OnOff` traits
below is the response when calling the  [Sync ](https://developers.google.com/actions/smarthome/reference/rpc/google.home.graph.v1#google.home.graph.v1.HomeGraphApiService.Sync) function:

```json
{
	"agent_user_id": "2476592",
	"device": {
		"id": "2251959347",
		"type": "action.devices.types.CAMERA",
		"traits": "action.devices.traits.CameraStream",
		"name": {
			"name": "DEV02"
		},
		"will_report_state": true,
		"device_info": {},
		"attributes": "\n\n\u0010availableToggles\u0012k2i\ng*e\n\u0010\n\u0004name\u0012\u0008\u001a\u0006record\nQ\n\u000bname_values\u0012B2@\n\u003e*\u003c\n\u000c\n\u0004lang\u0012\u0004\u001a\u0002en\n,\n\u000cname_synonym\u0012\u001c2\u001a\n\u0008\u001a\u0006record\n\u000e\u001a\u000crecord video\n\u001f\n\u0019cameraStreamNeedAuthToken\u0012\u0002 \u0000\n#\n\u001dcameraStreamNeedDrmEncryption\u0012\u0002 \u0000\n+\n\u001ecameraStreamSupportedProtocols\u0012\t2\u0007\n\u0005\u001a\u0003hls",
		"custom_data": "{\"real_type\":null,\"system\":\"EseeCloud\"}"
	}
}
```

**Comment by Fleker** [comment]
Did you resolve the issue? Is that why you closed it?

**Comment by fbens** [comment]
@Fleker Yes, problem resolved, thank you very much. :-)
