### ISSUE TITLE
conv.user.storage not persisting data in "VERIFIED" users

### ISSUE THREAD

**Issue by wuelcas** [actions-on-google/actions-on-google-nodejs#358]
Hi everyone,

Is anyone having recent problems with `conv.user.storage` with persisting data between conversations? It was working just fine a few days ago or at least last week but today the data I save in storage is not persisting between conversations.

My user (and actually other users that used the action) has [Web & App Activity](https://support.google.com/googlenest/answer/7382500) enabled, personal results turn on and when I invoke my action the `userVerificationStatus` is set as `VERIFIED`. If I go to my [Web & App Activity history](https://myactivity.google.com/myactivity) I see the invocations I made to my action.

So, I'm guessing I have all the checks to be sure the data should persist but it's not, and I'm pretty sure it was working before. It persists in the same session but after I leave the action and come back the `conv.user.storage` is an empty object. Anyone having an issue like that? or maybe I'm missing something?

**Comment by Fleker** [comment]
We're currently investigating potential instances where user storage may not be provided.

**Comment by MkFoster** [comment]
I am having issues as well.  I am using the Google Assistant app on iOS to test.  The incoming request says the user is VERIFIED but storage is an empty object even though I verified I set it in the last session. 

`{
    "raw": {
        "locale": "en-US",
        "lastSeen": "2019-09-27T15:10:20Z",
        "userVerificationStatus": "VERIFIED"
    },
    "storage": {},
    "locale": "en-US",
    "verification": "VERIFIED",
    "permissions": [],
    "last": {
        "seen": "2019-09-27T15:10:20.000Z"
    },
    "name": {},
    "entitlements": [],
    "access": {},
    "profile": {}
}`

**Comment by wuelcas** [comment]
Hey everyone, looks like the issue is fixed. The data in `conv.user.storage` it's being persisted in my actions.
