### ISSUE TITLE
ApiAiApp.tell() not closing app

### ISSUE THREAD

**Issue by IkechukwuAKalu** [actions-on-google/actions-on-google-nodejs#36]
Hi,

The webhook for my actions app works fine but the app does not close (ie the mic is still open for user response) when I call the `tell()` method on the `ApiAiApp` class. I tested on the Google Assistant on my Android phone and the Actions Simulator

```javascript
/** 
 * @param {ApiAiApp} aiApp The ApiAi app instance
 * @param {String} speech the response to the user
 * @param {Array} suggestions a String array of suggestions
 * @param {Boolean} last true if this is the last response
 */
function buildResponse(aiApp, speech, suggestions, last){
    if (aiApp.hasSurfaceCapability(aiApp.SurfaceCapabilities.SCREEN_OUTPUT)){
        aiApp.ask(aiApp.buildRichResponse()
            .addSimpleResponse(speech)
            .addSuggestions(suggestions));
    } else {
        (last) ?  aiApp.tell(`${speech}`) : aiApp.ask(`${speech}`, []);
    }
}
```
Some inspection led me to use 
`aiApp.buildResponse_(speech, false);` which works

I may be doing something wrong, I don't know. **Any help is appreciated. Thanks**

**Comment by smishra2** [comment]
It would be helpful if you could paste the response JSON created by the client library here. It is returned from the tell() method and also usually logged as part of the client library output.

**Comment by IkechukwuAKalu** [comment]
Created a new test project to check if the problem was from code and it was. Just realized I only called the tell method for devices without a screen. Sorry for the stress and Thanks.
