### ISSUE TITLE
api ai does not send the noInputs in case of RichResponse (in function buildResponse_)

### ISSUE THREAD

**Issue by zuznow** [actions-on-google/actions-on-google-nodejs#37]
We tested a fix for it - change in the function buildResponse_
We tested it on real device for google home and it works correctly
Any reason not to enable this flow?

The fixed code in  buildResponse_ function
The result was getting both responses and after no input getting the prompt for no input
We want to send card and no input promt

response.data = isStringResponse ? {
      google: {
        
        expectUserResponse: expectUserResponse,
        isSsml: this.isSsml_(textToSpeech),
        noInputPrompts: noInputs
      }
    } : {
      google: {
        expectUserResponse: expectUserResponse,
        richResponse: textToSpeech,
        noInputPrompts: noInputs  // added by zuznow 
      }
    };

**Comment by Canain** [comment]
This should be [working right now](https://github.com/actions-on-google/actions-on-google-nodejs/blob/45296cbe4ce2a3089eb258ffc6812e0a574cc6a7/dialogflow-app.js#L1002). Closing this issue for now.

Feel free to let us know if this is still an issue.
