### ISSUE TITLE
How to add body information to action.json?

### ISSUE THREAD

**Issue by juxeii** [actions-on-google/actions-on-google-nodejs#376]
I want to deploy the action.json file with body information for the POST fulfillment.

So far I have this(for my self-hosted nodejs server):

```
{
  "actions": [
    {
      "description": "Default Welcome Intent",
      "name": "MAIN",
      "fulfillment": {
        "conversationName": "my calculator"
      },
      "intent": {
        "name": "actions.intent.MAIN",
        "trigger": {
          "queryPatterns": [
            "talk to my calculator"
          ]
        }
      }
    }
  ],
  "conversations": {
    "my calculator": {
      "name": "my calculator",
      "url": "http://some.server.com:8080/fulfillment",
      "token": "somePassword"
    }
  },
  "locale": "en"
}
```

The line `"token": "somePassword"` does not work as body information.

The error is
`ERROR: Invalid JSON payload received. Unknown name "token" at 'localized_action_packages[0].value.conversations[0].value': Cannot find field`

I need this additional json information for authentification purposes.

What is the correct syntax here?

**Comment by Fleker** [comment]
Did you read somewhere that the `token` field existed? The correct method of doing so is to check against the [authorization](https://developers.google.com/assistant/conversational/webhook/reference/verify-requests) field in the request.

**Comment by juxeii** [comment]
Yes, the key `token ` exists.
I need in the POST request this `token` in the body.
I also need to specify `Content-Type` in the header.
How can I achieve both with ` action.json`?

I found out that it is possible to:

```
"httpHeaders": {
          "token": "someValue"
 }

```
but I don't know if this correct.
Is there a schema for `action.json`?

**Comment by Fleker** [comment]
All the reference material is at https://developers.google.com/assistant/conversational/action-package/reference/ActionPackage

**Comment by juxeii** [comment]
There I could not find anything of what I want to achieve.
I think with current schema of `action.json` it is not possible to send custom body information.
That is quite a bit of a constraint :(

**Comment by Fleker** [comment]
You cannot send custom body information. The proper way is [to request this information in your fulfillment](https://developers.google.com/assistant/conversational/webhook/reference/verify-requests).

**Comment by juxeii** [comment]
Yes, but I cannot influence this on a 3rd party app.
For now I go with the "hack" of using httpHeaders as the information source.
Here you can specify key value pairs and check them in the app.
