### ISSUE TITLE
Fulfillment answers don't reach Telegram, Facebook and Slack integration

### ISSUE THREAD

**Issue by TiagoGouvea** [actions-on-google/actions-on-google-nodejs#397]
I created a simple bot to test some new resources, but I'm facing an issue with **fulfillment responses** on some clients. I'm testing with many integrations.   

- ✅ The **fulfillment** work fine with Web Demo and Dialogflow Messenger
- 🔥 The **fulfillment** fails with Facebook Messenger, Slack and Telegram

I wrote two intents to test:

1. "Hello" - Text Response Intent
1. "Hi" -  Fulfillment Intent answered by node using `actions-on-google` package.

What happened:

- "Hello" - intent works on all integrations, like expected.
- "Hi" - intent works like expected with Dialogflow native integrations (✅ )
- "Hi" - intent doesn't work with other integrations (🔥). It shows "Typing..." while my node backend creates the answer, but the text response is never showed.

* In debug mode, I see that the request is received, the intent match, and the `Response` object are like expected.

### Node code:
```
const { dialogflow } = require('actions-on-google');
const app = dialogflow({ debug: true });
... 

app.intent('Hi', conv => {
  console.log('>> Hi Fulfillment reached');
  conv.ask(`Hi! I'm a fulfillment response on node!`);
});
```

### Node response (console output):
```
>> Hi Fulfillment reached
Response {
  "status": 200,
  "headers": {
    "content-type": "application/json;charset=utf-8"
  },
  "body": {
    "payload": {
      "google": {
        "expectUserResponse": false,
        "richResponse": {
          "items": [
            {
              "simpleResponse": {
                "textToSpeech": "Hi! I'm a fulfillment response on node!"
              }
            }
          ]
        }
      }
    }
  }
}
POST /api/chatBot/ 200 156 - 1419.611 ms
```

I recorded my screen to show better that behavior.

![ezgif-2-8a0aac31033e](https://user-images.githubusercontent.com/2242549/84386189-499ba480-abc7-11ea-8503-a91a65e29c44.gif)

I also posted this as a question on [StackOverflow](https://stackoverflow.com/questions/62324056/dialogflow-fulfillment-answers-dont-reach-telegram-facebook-and-slack-integrat)

**Comment by Fleker** [comment]
This library is not designed to work with any platform other than Actions on Google. If you are looking at hosting your application on other platforms, you would do better to use [dialogflow-fulfillment](https://github.com/dialogflow/dialogflow-fulfillment-nodejs) which should be more generalized.

**Comment by TiagoGouvea** [comment]
Ok. Got it. Thank you @Fleker !
