### ISSUE TITLE
Actions cli oauth disabled

### ISSUE THREAD

**Issue by lemena86** [actions-on-google/actions-on-google-nodejs#398]
When i try to update my actions.json file this error shows up

Error 401: disabled_client
The OAuth client was disabled.

**Comment by Fleker** [comment]
This sample does not use actions.json. You can configure all settings through the Actions console.

**Comment by thomasw** [comment]
There was a gactions outage starting at 2020-06-10 17:57:20 UTC that lasted for just about 22 hours. All gactions auth flows should be working now. Thanks for reporting the issue.
