### ISSUE TITLE
Debug logs need review

### ISSUE THREAD

**Issue by rotero** [actions-on-google/actions-on-google-nodejs#4]
One example
ActionsSdkAssistant.prototype.ask = function (inputPrompt, possibleIntents, dialogState) {
  debug('ask: inputPrompt=%s, possibleIntents=%s,  dialogState=%s',
    inputPrompt, possibleIntents, dialogState);

all variables are Objects, so the output is pretty meaningless if the variables are not "stringified"

**Comment by entertailion** [comment]
Thanks. Will fix in next update. Also, see new method signature: ActionsSdkAssistant.prototype.ask = function (inputPrompt, dialogState)
