### ISSUE TITLE
api.ai does not send the intent in the correct format

### ISSUE THREAD

**Issue by pratomchaip** [actions-on-google/actions-on-google-nodejs#40]
api.ai sends the intent name in
`body_.result.metadata.intentName`
but the actions-on-google/api-ai-app.js library looks for the intent in:
`body_.result.action`

... which causes an `Action Error: Missing intent from request body` error.

**Comment by entertailion** [comment]
Can you confirm that your API.AI intent action value is filled in and you are not using the intent name in your fulfillment instead.

**Comment by smishra2** [comment]
Just for some context, https://api.ai/docs/actions-and-parameters

**Comment by pratomchaip** [comment]
Ok. My fault. Just realised that I only had the intent in the name and not in the action field.
Thanks guys.
Closing issue.
