### ISSUE TITLE
HtmlResponse Vs Canvas

### ISSUE THREAD

**Issue by awais786327** [actions-on-google/actions-on-google-nodejs#408]
I didn't see HtmlResponse in an updated version of action on google library is it depreciated or I am missing something also tell me about canvas response which one to use for building an interactive canvas project?

**Comment by taycaldwell** [comment]
Hi @awais786327,

If you are building your Interactive Canvas Action using Dialogflow with the [actions-on-google-nodejs](https://github.com/actions-on-google/actions-on-google-nodejs) library, you will need to send an [HtmlResponse](https://github.com/actions-on-google/actions-on-google-nodejs/blob/master/src/service/actionssdk/conversation/response/html.ts).

You can read more about developing Interactive Canvas Actions with Dialogflow [here](https://developers.google.com/assistant/conversational/df-asdk/interactivecanvas/build).

If you are building your Interactive Canvas Action using Actions Builder with the [assistant-conversation-nodejs](https://github.com/actions-on-google/assistant-conversation-nodejs) library, you will need to send a [Canvas](https://github.com/actions-on-google/assistant-conversation-nodejs/blob/master/src/conversation/prompt/canvas.ts) response.

You can read more about developing Interactive Canvas Actions with Actions Builder [here](https://developers.google.com/assistant/interactivecanvas/prompts).

**Comment by awais786327** [comment]
![image](https://user-images.githubusercontent.com/12613564/97088567-27bd2e80-164b-11eb-9388-76bf010ad70c.png)

ok one more question why interactive canvas checkbox is missing on my action on google page?

**Comment by awais786327** [comment]
@taycaldwell there i already have selected Games and fun catagory

**Comment by awais786327** [comment]
@taycaldwell from the picture above there I already have selected Games and fun category then why interactive canvas checkbox is missing on my action on google page?

**Comment by taycaldwell** [comment]
Hi @awais786327,

This setting has moved under **Develop > Interactive Canvas**, but it looks like it isn't present for Dialogflow projects. I have filed a bug internally to investigate and fix this issue.

Sorry for the inconvenience.
