### ISSUE TITLE
It does not run on apigee.

### ISSUE THREAD

**Issue by gakuba** [actions-on-google/actions-on-google-nodejs#41]
I suspect an issue with node version as apigee is still running a very old node version. Can you please confirm which versions are compatible with the module?
Here is the error returned when I run the module on apigee. Note that it works fine on my computer.
status code: 500

{
    "fault": {
        "faultstring": "Script node executed prematurely: missing ; before statement\nmissing ; before statement\n    at module.js:439\n    at module.js:474\n    at module.js:356\n    at module.js:312\n    at module.js:364\n    at require (module.js:380)\n    at /organization/environment/api/node_modules/actions-on-google/actions-on-google.js:24\n    at module.js:456\n    at module.js:474\n    at module.js:356\n    at module.js:312\n    at module.js:364\n    at require (module.js:380)\n    at /organization/environment/api/app.js:2\n    at module.js:456\n    at module.js:474\n    at module.js:356\n    at module.js:312\n    at module.js:364\n    at require (module.js:380)\n    at /organization/environment/api/routes/routes.js:4\n    at module.js:456\n    at module.js:474\n    at module.js:356\n    at module.js:312\n    at module.js:364\n    at require (module.js:380)\n    at /organization/environment/api/server.js:13\n    at module.js:456\n    at module.js:474\n    at module.js:356\n    at module.js:312\n    at module.js:497\n    at startup (trireme.js:142)\n    at trireme.js:923\n",
        "detail": {
            "errorcode": "scripts.node.runtime.ScriptExitedError"
        }
    }
}

**Comment by gustavo-moreira** [comment]
What's the Node.js version that you are running on apigee?
The client library only requires ES6 support, but we can test with the same version as in apigee locally to find out what's the issue.

**Comment by gakuba** [comment]
Hi Gustavo,

I am sure Apigee does not support ES6. currently Apigee runs node 0.1x. so sad.

**Comment by gustavo-moreira** [comment]
Unfortunately there isn't much we can do in this case then.
I'm closing this issue, but feel free to open it back again if it still doesn't work after they've added ES6 support to the platform.
