### ISSUE TITLE
queryText being sent to Dialogflow is not the original user query

### ISSUE THREAD

**Issue by jonny-ms** [actions-on-google/actions-on-google-nodejs#419]
The user input / queryText being sent to Dialogflow is not the expected, original user query.

![image](https://user-images.githubusercontent.com/52211082/110168278-8f834300-7dbc-11eb-8202-d3432a5ca2ac.png)

I then enabled "Log interactions to Google Cloud" in my Dialogflow project's settings. What I'm seeing is multiple request/response interactions before the actual request that goes to DF. In the example above, this is what I see: 

![image](https://user-images.githubusercontent.com/52211082/110166997-ba6c9780-7dba-11eb-928b-ae5bf4ee5541.png)

With the first debug resource showing post data with: 
```
"inputs":[{"rawInputs":[{"inputType":"UNSPECIFIED_INPUT_TYPE","query":"how long has it been on the market"}]
```
And 
```
resource: {
type: "assistant_action"
  labels: {
    project_id: "<MY-PROJECT-ID>"
    version_id: ""
    action_id: ""
  }
},
timestamp: "2021-03-05T18:41:44.142202856Z"
severity: "DEBUG"
labels: {
  channel: "production"
  querystream: "GOOGLE_USER"
  source: "AOG_REQUEST_RESPONSE"
}
```
 
The subsequent requests are the same but with modified input queries ("how long has it been on the market" -> "how long has something been on the market" -> "how long has us FDA been on the market"), the last one being the actual user query sent, the channel being preview and the action_id "actions.intent.TEXT".
```
resource: {
type: "assistant_action"
  labels: {
    project_id: "<MY-PROJECT-ID>"
    version_id: ""
    action_id: "actions.intent.TEXT"
  }
},
timestamp: "2021-03-05T18:41:45.942019959Z"
severity: "DEBUG"
labels: {
  channel: "preview"
  querystream: "GOOGLE_USER"
  source: "AOG_REQUEST_RESPONSE"
}
```

I should note that I am testing current drafts of an AoG project and have no releases let alone a production release. I have a denied beta, because of branding issues which I address with separate AoG/DF projects for PROD. I do not have any intents enabled for slot filling or any required entity parameters. And I have been noticing this on many occasions when getting unexpected fallbacks.

What are all these requests/responses happening before DF Fulfillment? Why is the query being changed?

**Comment by Fleker** [comment]
Your issue is that when you the explicit query with `it`, the `it` is replaced with `us FDA`?

**Comment by jonny-ms** [comment]
![aog_entity_resolution_lorem](https://user-images.githubusercontent.com/52211082/110832166-9ef10900-8260-11eb-9628-3a72504a1b3a.png)

To me, this is pretty clear evidence that Actions on Google is attempting entity resolution, before sending data to DF. How can I disable this?

**Comment by jonny-ms** [comment]
Closing this issue.

After having contacted someone at Google Cloud, I was informed this was something that had been raised by others and that AoG devs were looking into it.

As of a Mar 24 2021 release, I can no longer replicate the issue.
