### ISSUE TITLE
app.getUser().userId returns Epoch time value instead of actual userId

### ISSUE THREAD

**Issue by samsruti** [actions-on-google/actions-on-google-nodejs#46]
1. console.log(app.getUserId);
It returns:
Here userId is the Epoch time instead of the actual userID.

**Response:**

```
{ locale: 'en-US',
  userId: '1502723585291',
  user_id: '1502723585291',
  access_token: undefined,
  userName: null 
}
```

My actual userId = 112695425590278732409

**Expected Response:**

```
{ locale: 'en-US',
  userId: '112695425590278732409',
  user_id: '112695425590278732409',
  access_token: undefined,
  userName: null 
}
```

**Comment by OpenDog** [comment]
This is a device setup issue. If you hit "skip" on the "Get personal results" screen, Google will send epoch ids as a punishment. 

![img_1023](https://user-images.githubusercontent.com/6343300/29281751-3c0dd02e-80ee-11e7-8a65-9e0076ff3372.PNG)

**Comment by samsruti** [comment]
I was trying in Online Simulator and got the results.

**Comment by OpenDog** [comment]
Oh. Simulator is always epoch. Not sure if that's a bug or a feature ...

**Comment by samsruti** [comment]
I want to get to know how it is behaving in Google Assistant (Phone)?
Is it epoch or the actual id?

**Comment by OpenDog** [comment]
Well, actual id ... but currently it depends on the device setup. I think that's a bug.

**Comment by samsruti** [comment]
Thanks :)

**Comment by grctest** [comment]
Interesting.. so in order to differentiate between a legit anonymous google ID & the timestamp, some quick pseudocode:

```
userIDLength = userID.length;

if (userIDLength >= 21) {
  // Non personalized results
  app.tell();
}
```

Thanks for the heads up! 👍

**Comment by Fleker** [comment]
Have you updated to the latest version of the library (v2.X)? If so, do you still see this behavior?
