### ISSUE TITLE
Can you decouple dependency from express style req, res ?

### ISSUE THREAD

**Issue by jeveloper** [actions-on-google/actions-on-google-nodejs#48]
Hi there

I was fighting this problem for a while, wish it was actually described in the docs but i had realized that my request object didn't have a few properties.

Any chance you might specify which properties you need to be passed to constructor ? 

I would prefer if express wasn't involved hence making lightweight micro service using api ai.

thanks

**Comment by OpenDog** [comment]
You don't need to decouple. You can fool the sdk ... with mock request and response. We run the assistant in an AWS lambda! No kidding! Blasphemy! Check out the node-mocks-http package!

I do this to create an assistant from the request.

```
let Assistant = require("actions-on-google").ApiAiApp;
let expressMockery = require("node-mocks-http");

export function getAssistant(requestBody: RequestBody): any {

    // Prep the request and response.
    let mockRequest = expressMockery.createRequest({
        body: requestBody
    });

    let mockResponse = expressMockery.createResponse();

    // We need this monkey patch because node-mocks-http doesn't have the append.
    mockResponse["append"] = (header: string, value: string) => {
        console.log("Google SDK added a header: \"" + header + "\": \"" + value + "\"");
    };

    // Feed the request/response to the assistant SDK
    return new Assistant({ request: mockRequest, response: mockResponse });
}
```

then you do your thing

```
assistant.tell("We fooled you, Google! <insert evil laugh audio ssml here>")
```

and at the end you scoop out the response

```
let response = JSON.stringify(assistant.response_._getData());
```

**Comment by OpenDog** [comment]
Actually if the SDK guys like this I can add it and do a PR ...

**Comment by OpenDog** [comment]
Here is a working test:

https://github.com/OpenDog/actions-on-aws

**Comment by jeveloper** [comment]
It would've been nice if SDK stated exactly what it needs, e.g. headers, parsed json payload. That's about it. 
Thanks for the hack :) good job!

But i am trying to have as fewer dependencies as possible , so seeing this isn't great plus more cpu cycles

let mockRequest = expressMockery.createRequest({

**Comment by Canain** [comment]
In [v2](https://medium.com/@silvano.luciani/actions-on-google-client-library-for-node-js-v2-0-0-alpha-c92361167f15), we added a better abstraction for request parsing and response generation which allows you to seamlessly use any web framework. There is also a generic [StandardHandler](https://github.com/actions-on-google/actions-on-google-nodejs/blob/c84ba000b6257b4d932e022658405e8661524625/src/framework/framework.ts#L74) called using `app.handler` which takes a JSON object and Headers as inputs and outputs a JSON object and a status code in a Promise.

Try it out and let us know what you think so we can polish it up while it's still in alpha.

**Comment by Canain** [comment]
closing this issue now that v2 is general availability
