### ISSUE TITLE
ask breaks if dialogState exists

### ISSUE THREAD

**Issue by rotero** [actions-on-google/actions-on-google-nodejs#5]
I don't know if this is a bug or not, but I'm not capable of resolving it:

ActionsSdkAssistant.prototype.ask = function (inputPrompt, possibleIntents, dialogState) 

if dialogState is an empty object - ask fails with an "Invalid dialog state". But there is no possibility to reset the dialogState. The underlying issue might be either that the dialogState "survives" a crash or the missing possibility to reset the state.

**Comment by entertailion** [comment]
We had to remove support for the unsupported inDialogTriggers. See new method signature: ActionsSdkAssistant.prototype.ask = function (inputPrompt, dialogState)
