### ISSUE TITLE
OrderAction in Transactions.js is missing customer_service

### ISSUE THREAD

**Issue by shivanykshenoy** [actions-on-google/actions-on-google-nodejs#51]
OrderAction in transactions.js is missing a customer_service as an enum (very last one):  https://developers.google.com/actions/reference/rest/Shared.Types/ActionType?hl=vi

**Comment by Canain** [comment]
Looks like the [enum is there now in v2](https://github.com/actions-on-google/actions-on-google-nodejs/blob/2261c93cd158f316bde94f2ad28c65788a10386d/src/service/actionssdk/api/v2.ts#L57).
