### ISSUE TITLE
handleRequest should not swallow promise

### ISSUE THREAD

**Issue by sdolier** [actions-on-google/actions-on-google-nodejs#52]
Currently when handleRequest is called, and the map of request handlers contains functions that return promises, the promise is swallowed by handleRequest and we are unable to handle the then or catch events.

An example of when this would be useful is when we have a callback function to call in our nodejs environment that we would like to call after handleRequest has internally resolved the promises.

Our solution is to return the promise from within handleRequest and invokeIntentHandler_, or true/false for non promise handlers.

We have this implemented here: https://github.com/sdolier/actions-on-google-nodejs/commit/b5137225640c10435616e94d77ba8523dd0cdae3

If this change is acceptable we can submit a pull request.

**Comment by Canain** [comment]
Hi, thanks for bringing this up!

I think it would be a good idea to in general have handleRequest handle Promises better but I'm not completely sure if this is the best way to do this (I'm not sure if returning boolean or a Promise is good to have as the returning type then would not be really consistent).

Can you close this issue and create a pull request on here so we can continue discussing this change on the code itself?

**Comment by sdolier** [comment]
Thanks, I have created a pull request.
