### ISSUE TITLE
Tutorial for this library that does not involve Api.ai?

### ISSUE THREAD

**Issue by roschler** [actions-on-google/actions-on-google-nodejs#55]
1) Is there a step by step tutorial for this library?  Specifically, how to install and configure it on a Linux box and how to launch it under Node.js?

2) Is there a tutorial that explains how to use this node.js client library for Google Actions, a getting started or overview/tutorial?  It would be extremely helpful to find  one that does **not** use the Api.ai fulfillment side of the library since we have our own natural language processing library.

**Comment by Canain** [comment]
We currently have a sample which runs a Node.js server without a cloud platform which is the [Interactive Fiction Sample](https://github.com/actions-on-google/interactive-fiction-nodejs). That sample creates an express server in Node.js and serves it and has both an Actions SDK version [here](https://github.com/actions-on-google/interactive-fiction-nodejs/blob/master/actionsdk.js#L37) and a Dialogflow version [here](https://github.com/actions-on-google/interactive-fiction-nodejs/blob/master/app.js#L38).

The Actions SDK sample file [again here](https://github.com/actions-on-google/interactive-fiction-nodejs/blob/master/actionsdk.js#L37) is most likely what you are looking for. [Actions SDK](https://developers.google.com/actions/sdk/) gives you a more raw text input which you can then use your own natural language processing library to parse.

Other samples using Actions SDK are the [Eliza sample](https://github.com/actions-on-google/actionssdk-eliza-nodejs), the [Say a Number](https://github.com/actions-on-google/actionssdk-say-number-nodejs) sample, and the [Conversation Components](https://github.com/actions-on-google/conversation-components-nodejs/blob/master/actions-sdk/functions/index.js) sample (which has both a Actions SDK and a Dialogflow version).

Let me know if you would like more help or want more clarification about anything I mentioned.

**Comment by Canain** [comment]
Since there hasn't been more questions, closing this for now.

Feel free to open another issue if you have any more questions.
