### ISSUE TITLE
`isSsml_` fails to detect SSML when opening tag has attributes

### ISSUE THREAD

**Issue by jjjacksn** [actions-on-google/actions-on-google-nodejs#6]
The current implementation of `Assistant.isSsml_()` checks if the text begins with exactly `'<speak>'` and ends with exactly `'</speak>'`. This breaks down if your speak tag has any attributes, i.e. `'<speak version="1.0">Hello world!</speak>'`.

An improved implementation might only check for `'<speak'` at the beginning, or use a regular expression.

**Comment by entertailion** [comment]
Agreed. We will fix this in the next update.

**Comment by entertailion** [comment]
Fixed in 1.0.4
