### ISSUE TITLE
how to send followup event from webhook using action-on-google lib

### ISSUE THREAD

**Issue by malikasinger1** [actions-on-google/actions-on-google-nodejs#64]
by followupEvent i'm refering to this: 
https://api.ai/docs/fulfillment#response
https://api.ai/docs/events#invoking_event_from_webhook

I have read rest of the https://dialogflow.com/ document more then twice(since it is updating frequently) and I know well how to send followup events with simple webhook (with simple rest service webhook without action-on-google),
here is my repo with the sample of it (see commented code from line 35 to 54) https://github.com/malikasinger1/quizbot-reactjs-api.ai-firebase-function/blob/master/functions/src/lib/apiai-functions.ts

but my question is how to send it with action-on-google nodejs library (https://www.npmjs.com/package/actions-on-google) since we handover the request object to action-on-google and it gives us an object `app`, we have methods in the object like `app.ask()` `app.tell()`, `app.setContext()` so i was expecting for some method like:
```
app.followupEvent("<event_name>",{
         "<parameter_name>":"<parameter_value>>"
      }) 
app.ask();
```
OR
```
app.askWithFollowupEvent({...
})
```
so what you say about this? if you don't have these method you should add one,
and please let me know some place where you guise discuss future plannings

**Comment by DerGuteWolf** [comment]
I second this request, I am missing this badly!

**Comment by roschler** [comment]
I third it!  

Also, something that would allow us to send an E-mail to the user on behalf of our app?   On a Google Home app, where there is no display, it is a very common occurrence to want to send a user further materials in the form of a document or a link to a web page, etc.  It would be very helpful to send them such an item to their linked Google E-mail account.

**Comment by malikasinger1** [comment]
finally they took my question seriously :-)

> 
> ---------- Forwarded message ----------
> From: Actions on Google Support <aog-support@google.com>
> Date: Wed, Nov 15, 2017 at 7:50 PM
> Subject: Re: how to send followup event from webhook using action-on-google lib
> To: "malikasinger@gmail.com" <malikasinger@gmail.com>
> Cc: "aog-support@google.com" <aog-support@google.com>
> 
> 
> Hi,
> 
> Thank you for your patience in this case. I just got an answer from our engineers confirming that it was not possible to fire a followup event with the actions on google nodejs library.
> We have taken your request into account and will update you if the feature is pushed live.
> 
> Kind Regards,
> 
> Jean-Charles,
> Actions on Google Support Team.
> 
> 
> 
> --------------- Original Message ---------------
> From: inzamam malik [malikasinger@gmail.com]
> Sent: 10/7/2017 5:42 AM
> To: aog-support@google.com
> Subject: Re: how to send followup event from webhook using action-on-google lib
>  
> why you are not replying me so far
>

**Comment by mymro** [comment]
I really hope this will be added soo.

**Comment by malikasinger1** [comment]
hey collaborators, any update regarding this?

**Comment by mymro** [comment]
Well there is a pull request adding this(it works), however the person posting it, has yet to sign the CLA

**Comment by Iridio** [comment]
At the moment I do the following:
```
const response = {
    followupEvent: {
        name: "MyEventName",
        data: { value1: "asd", value2: "qwe" }
    }
}
return myDialogflowApp.response_.status(200).send(response);

```
It's dirty, but it works and while waiting for approval and eventual publish I think is better than nothing

**Comment by roschler** [comment]
Is this feature in the main branch yet, or is the CLA still pending?

**Comment by eriklindebratt** [comment]
+1!

**Comment by MizziM96** [comment]
Hi, I am trying to use the followupEvent by building the JSON response as shown in previous comments but I still cannot trigger the event I want. I get an input.unknown as a result. I have done nothing on the dialogflow side just normal intents with no input/output contexts and both intents are set to use the webhook. Can someone tell me if I have to set up the intents from the dialogflow side to be triggered or any other step that I might have missed? thanks :)

**Comment by Iridio** [comment]
The only thing I can think of, is that you did not create an intnet with the event you want to be activated by the followupEvent command.

**Comment by daevidov** [comment]
@Iridio this worked perfectly! Good temporary approach.

**Comment by Canain** [comment]
Closing this as it's [merged in v1](https://github.com/actions-on-google/actions-on-google-nodejs/pull/105) and [available in v2](https://github.com/actions-on-google/actions-on-google-nodejs/blob/2261c93cd158f316bde94f2ad28c65788a10386d/src/service/dialogflow/conv.ts#L303).

**Comment by malikasinger1** [comment]
is it possible in v2?

**Comment by jneveux** [comment]
@malikasinger1 

I could not find anything in the documentation. I found a function in v2 code `conv.js`

```
// See followup(event, parameters, lang).
    conv.followup(eventName);
```

**Comment by wubbajack** [comment]
It's there, typehint the conversation object as type DialogflowConversation in the conversation handler.
[See the docs](https://actions-on-google.github.io/actions-on-google-nodejs/classes/dialogflow.dialogflowconversation.html)

**Comment by HerrHansen** [comment]
Very hard to find. Cost me two days to find this hint. Thank you so much wubbajack!!

+1 for **conv.followup()**

https://actions-on-google.github.io/actions-on-google-nodejs/classes/dialogflow.dialogflowconversation.html

Google should update their documentation on dialogflow.com, to help everyone with that issue. And maybe create an example for actions-on-google V2 API. :-)

**Comment by grctest** [comment]
Has anyone had success passing parameter data through ```conv.followup()```?

I can successfully trigger the target intent via the event name configured within dialogflow, however the parameters don't seem to survive the trip other than as the original input parameter data stored in the ```_actions_on_google``` context stored prior to the followup triggering.

Do I need to be retrieving the passed parameter data from the event's contents explicitly, or should I be able to followup with parameters defined in the dialogflow intent?

Cheers 👍

**Comment by Iridio** [comment]
You should pass the parameters inside the event’s context and then access it from your intent.
Finally, in your intent you can create a context with the lifecycle that you prefer to pass the parameters to the next intent if you need it.


________________________________
Da: CM <notifications@github.com>
Inviato: lunedì, settembre 17, 2018 18:01
A: actions-on-google/actions-on-google-nodejs
Cc: Alessandro Colla; Mention
Oggetto: Re: [actions-on-google/actions-on-google-nodejs] how to send followup event from webhook using action-on-google lib (#64)


Has anyone had success passing parameter data through conv.followup() with the latest library version?

I can successfully trigger the target intent via the event name configured within dialogflow, however the parameters don't seem to survive the trip other than as the original input parameter data stored in the _actions_on_google context stored prior to the followup triggering.

Do I need to be retrieving the passed parameter data from the event's contents explicitly, or should I be able to followup with parameters defined in the dialogflow intent?

Cheers 👍

**Comment by kencanak** [comment]
> Has anyone had success passing parameter data through `conv.followup()` with the latest library version?
> 
> I can successfully trigger the target intent via the event name configured within dialogflow, however the parameters don't seem to survive the trip other than as the original input parameter data stored in the `_actions_on_google` context stored prior to the followup triggering.
> 
> Do I need to be retrieving the passed parameter data from the event's contents explicitly, or should I be able to followup with parameters defined in the dialogflow intent?
> 
> Cheers 👍

did you manage to get it work @grctest ? cause i am facing the same issue. can't seems to use the parameters value in my response

**Comment by grctest** [comment]
@kencanak I did not, however given that [v2.4.0 changed followup](https://github.com/actions-on-google/actions-on-google-nodejs/releases/tag/v2.4.0) to not purge 'conv.data', I've chosen to pass data to the followup intent via 'conv.data.variable' fields.

**Comment by sureshapn** [comment]
> The only thing I can think of, is that you did not create an intnet with the event you want to be activated by the followupEvent command.

Thankyou man

**Comment by eriklindebratt** [comment]
@grctest @kencanak Seeing the exact same thing, reported it in a [separate issue](https://github.com/actions-on-google/actions-on-google-nodejs/issues/261).

**Comment by valgaze** [comment]
For anyone doing archaeology on this issue in the future, here is the tl;dr:

- 2 Intents: Parent Intent & Child Intent

-  In the Dialogflow web console, add an event called "my_event" to Child Intent & no training input phrases

- In the fulfillment code for **Parent Intent**, you can trigger the Child Intent  (which is bound to event my_event) with the following:

```js
app.intent('parent intent', (conv, parameters) => {
   conv.followup('my_event');
});
```

- If you wanted to pass parameters with the event you can do this (but it probably won't work the way you're expecting):

```
app.intent('parent intent', (conv, parameters) => {
    const myData = { a:1, b:2, c:3, d: 'efgh' };
    conv.followup('my_event', myData); // pass in object
});
```

Then in DialogFlow web console, inside **Child Intent** you would select parameters & explicitly map each property as a parameter. 

Important trick: under the value column, you need to following the format of **#event.property**, ex

```
|| Value ||
#my_event.name.a
#my_event.name.b
#my_event.name.c
#my_event.name.d
```

Then in your **Child Intent** handler code you can access them as parameters:

```js
app.intent('child intent', (conv, parameters) => {
    const { a, b, c, d} = parameters;
    conv.ask(`Got the data! ${a}, ${b}, ${c}, {d}`)
});
```

If you can't be bothered with all that to pass around data & trigger an intent, you can use ```conv.data``` as an escape hatch of sorts. Note we still use an event to trigger/invoke the Child Intent, we just don't pass the event data.

From **Parent Intent** fulfillment handler:

```js
app.intent('parent intent', (conv, parameters) => {
    const myData = { a:1, b:2, c:3, d: 'efgh' };
    conv.data = myData; // attach whatever data to conv.data
    conv.followup('my_event_name'); // No data on event
});
```

And in **Child Intent** handler:

```js
app.intent('child intent', (conv, parameters) => {
    const { a, b, c, d } = conv.data;
    conv.ask(`Got the data! ${a}, ${b}, ${c}, {d}`)
});
```
