### ISSUE TITLE
Stack trace on error

### ISSUE THREAD

**Issue by Sangdol** [actions-on-google/actions-on-google-nodejs#67]
Hello,

Thanks for this awesome project.

One thing I miss is the ability to see the stack trace when an error occurred in my code. It's really hard to find a place where an error occurred for now as it shows this kind of limited message for now:

![screen shot 2017-10-26 at 14 51 50](https://user-images.githubusercontent.com/803223/32054106-a42f923e-ba5d-11e7-9ba3-d95094bfa020.png)

What I want to see is something like this:

![screen shot 2017-10-26 at 14 52 07](https://user-images.githubusercontent.com/803223/32054111-a689a9a2-ba5d-11e7-8ccf-7dbee1e8fd4d.png)

I think we can easily fix this by logging `reason.stack` instead of `reason.message` here:

https://github.com/actions-on-google/actions-on-google-nodejs/blob/8a3903085d0ad670590476c794c28551f32c65fc/assistant-app.js#L2004

Thanks,
Sang

**Comment by Canain** [comment]
Hi, in v2 we have better error propagation and a more standardized framework system which should show the stack trace now.

Feel free to try it out and if you want to migrate, you can take a look at our [v1 migration guide](https://developers.google.com/actions/reference/nodejs/lib-v1-migration).
