### ISSUE TITLE
Expected Intents

### ISSUE THREAD

**Issue by OpenDog** [actions-on-google/actions-on-google-nodejs#7]
In 1.0.4 the method ask doesn't take expected intents anymore but it still sneaks in the assistant.intent.action.TEXT as expected. Now all my intents come back as raw text. This worked in 1.0.2. 

Everything stopped working.

**Comment by entertailion** [comment]
We changed the ask method in 1.0.3, which unfortunately changed the method signature. We want to keep the Actions SDK focused on using your own NLU. As such, we now only return TEXT for all user responses. If you don't have your own NLU, we recommend using API.AI.

**Comment by OpenDog** [comment]
We? You mean Google? That means Google is promoting an SDK that is not compliant with their own protocol? API still takes the expected intents.

**Comment by claudiocherubino** [comment]
Our goal is to have a clear path for those who want to use their own NLU. This design gives developers the most flexibility when integrating their engine with the Actions SDK, while keeping API.AI as our recommendation for those who don’t have an NLU solution.
The change was applied to the SDK on the latest version, and rolling out to the Conversation API in stages, as we don't want to break apps that are already developed. We don’t recommend using expected intents with the Actions SDK, as there’s no guarantee that the API will support them in the future.

**Comment by OpenDog** [comment]
Claudio, thank you for the subtle warning ... 👍
