### ISSUE TITLE
getaddrinfo ENOTFOUND in dns.js

### ISSUE THREAD

**Issue by jiabailie** [actions-on-google/actions-on-google-nodejs#70]
In my app, I need to retrieve some contents from other web page.
So I use 'read-art' to get some content from other page, but I encounter below error.

             Error: getaddrinfo ENOTFOUND jiabailie.github.io jiabailie.github.io:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

Below is the code segment.
```
      read(webPage, function(err, art, options, resp) {
        if(err) {
          throw err;
        }
        var content = art.html;
        let inputPrompt = app.buildInputPrompt(true, '<speak>' + content + '</speak>', NO_INPUTS);
        app.ask(inputPrompt);
      })
```

**Comment by CorentinPacaud** [comment]
Hi,
I have the exact same problem.
It appears that Google Cloud Plateform doesn't allow you to make request on other API unless you have a paid account on GCP. You need to enable "Billing" on GCP : 
https://stackoverflow.com/a/42775841/2311451

**Comment by Canain** [comment]
Seems to be resolved. Let us know if you have more issues.
