### ISSUE TITLE
Unable to specify a platform in a RichResponse

### ISSUE THREAD

**Issue by jon301** [actions-on-google/actions-on-google-nodejs#72]
Hi

I am trying to add an image to a RichResponse object on the `facebook` platform using the `actions-on-google` sdk.

Here is my code (simplified) :

```
        const DialogflowApp = require('actions-on-google').DialogflowApp;
        const imageUrl = '...';
        const imageAlt = '...';

        app.ask(app.getIncomingRichResponse()
          .addSimpleResponse(imageAlt)
          .addBasicCard(new BasicCard()
            .setImage(imageUrl, imageAlt)
          )
        );
```

With the code above, the image is showing correctly in the Emulator, but not in production on my Facebook Messenger application, I only see the image URL in a text format.

From the [docs](https://developers.google.com/actions/reference/nodejs/RichResponse), it does not seem to be supported.

Any ideas ?

Thanks

**Comment by 0xcaff** [comment]
I believe the actions on google sdk is for interacting with dialogflow specifically for actions on google, not for facebook integration.

**Comment by Fleker** [comment]
The Actions on Google platform is designed specifically for Actions on Google. If you're using another platform like Facebook, you will have to look at [the Dialogflow fulfillment library](https://github.com/dialogflow/dialogflow-fulfillment-nodejs).
