### ISSUE TITLE
Simulator shows "My test app isn't responding right now. Try again soon" but works perfectly fine in Try it now

### ISSUE THREAD

**Issue by apal21** [actions-on-google/actions-on-google-nodejs#79]
I have written a code to test this app which returns the same string in the request.
It has no errors in try it now.

![image](https://user-images.githubusercontent.com/11748050/33807592-2e69f8da-ddff-11e7-96d4-c3a1c138541f.png)

But in simulator it shows : `MalformedResponse 'final_response' must be set.`

![image](https://user-images.githubusercontent.com/11748050/33807599-535e16ee-ddff-11e7-9b6c-9ba9b9ee4cd2.png)

I've not enabled API v2.

In "try it now", my webhook is triggered successfully and gives me the response code 200 but in simulator, my webhook is never triggered.

I also tried to set an input hello in Default Welcome Intent with default responses without any webhooks but the result is always same.

**Comment by chilno** [comment]
1. Do you have a text response in your welcome intent regardless of using webhook fulfillment? If Yes, and you still see the error => Go to 2, otherwise there is an issue with the response you are sending from your webhook.
2. Check the Debug tab and see if the parameter "curlCommand" in the AoG simulator contains the same token value as the one "Client access token" in the Dialogflow project under API keys. If not you might need to re-link your AoG project with the DIalogflow one.

**Comment by apal21** [comment]
Ohh. My client access token in project setting and the token in curlCommand are different.
How to re-link this project?

**Comment by chilno** [comment]
In Dialogflow > Integrations > Google Assistant > Update Draft

**Comment by apal21** [comment]
I did that but that didn't work. I also tried to refresh the keys but in curlCommand it shows the same key every time even after updating the draft.

**Comment by chilno** [comment]
Make sure you click on TEST DRAFT again in the AoG Console

**Comment by apal21** [comment]
Yes I did that too and I also restart my browser. I cleared cookies and cache. but none of them worked.

this is my client access token: `577fffec1013406db87b8ca6149659b2`

this is the curlCommand:
`"curlCommand": "curl -v 'https://api.api.ai/api/integrations/google?token=16d1c6c808f04dce95cdedbc09dd3543' -H 'Content-Type: application/json;charset=UTF-8' -H 'Google-Actions-API-Version: 2' -H 'Authorization: eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc5MWM0YjcxNWE1YzNiYTdhY2EyYmQzODgyMTE4MzFkZDMxNjZiNjIifQ.eyJhdWQiOiJ0ZXN0LWdhcy1zZXJ2ZXIiLCJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJqdGkiOiI5OWZiMzNlMzlkOThkYjMxM2FkNzZjMjE2NzY0OThlOGY4ZWFmZjFlIiwiaWF0IjoxNTEyOTgyOTY1LCJleHAiOjE1MTI5ODMwODUsIm5iZiI6MTUxMjk4MjY2NX0.s4NCy6nMJrMu5kaNJ18x-DkXA_rUcmPwS3JnBC_gtWSWYf3oSra0mONnr8drgtORzkYs0vF_9GotTkiPKe8bWqbDh3MMG9lk-5CCF0utuC3DHG3cLqLsWXOX8lp2IdifI2kOuY9iiKYmC5dxzRoGR5CTlaYCRpmLGx8BPmXt3ZCOvC5dKbfvdRpEVNrzvSB6QLnQF6dRxqix6CeI2OJoMd_wTpOy6Xz6Y0HEBnWma3Wj-ltU9O33wyVimWp2mjuOu_ik320PIug_WUEPzSE8iE08XOGoJ1fYOeKt2ACmT7xYan-bLZpR_Rx6l69XRj8LMSYAbw8Q237Phucvj9dCyQ'  -A 'Mozilla/5.0 (compatible; Google-Cloud-Functions/2.1; +http://www.google.com/bot.html)' -X POST -d '{\"user\":{\"userId\":\"ABwppHGZZMcTM7QsAv1aGAh3zOLDIzZYEU7yfEQtZyQIm12FlCFn2WRxRq2KdX9MTbF4csXJ1lrW0CUSoPt2\",\"locale\":\"en-US\",\"lastSeen\":\"2017-12-11T08:55:32Z\"},\"conversation\":{\"conversationId\":\"1512982965898\",\"type\":\"NEW\"},\"inputs\":[{\"intent\":\"actions.intent.MAIN\",\"rawInputs\":[{\"inputType\":\"KEYBOARD\",\"query\":\"Talk to my test app\"}]}],\"surface\":{\"capabilities\":[{\"name\":\"actions.capability.AUDIO_OUTPUT\"},{\"name\":\"actions.capability.SCREEN_OUTPUT\"}]},\"isInSandbox\":true,\"availableSurfaces\":[{\"capabilities\":[{\"name\":\"actions.capability.AUDIO_OUTPUT\"},{\"name\":\"actions.capability.SCREEN_OUTPUT\"}]}]}'"
  }`

**Comment by chilno** [comment]
1. In Dialogflow, make sure the Project ID is the same as the one you are using in the AoG console.
2. In Dialog flow, click on the "Refresh key" for the "Client access token" then redo the Integration > Google Assistant > Update Draft > Visit Console > Test Draft

**Comment by apal21** [comment]
I just delete this app, created a new one with different name and different google project but in simulator it shows the same token. I also deleted previous Google project and I am using correct Project in simulator

**Comment by apal21** [comment]
I don't know why but it is working now. I have done nothing.

**Comment by humphriest** [comment]
Any working solution I can use? I'm getting this error as well

**Comment by apal21** [comment]
First delete all the google console projects and then just wait.

**Comment by phuclm** [comment]
i'm faced with this issue, how to fix it. Waiting is too bad

**Comment by Anton-Prab** [comment]
Seriously guys.. Nothing worked out. Tried all sorts that mentioned above. Did anyone managed to get it right ? If so, please help us out.

**Comment by entertailion** [comment]
If you continue having issues with the simulator, contact support: https://developers.google.com/actions/support/

**Comment by apal21** [comment]
@phuclm  @Anton-Prab it took 3-4 days for me after deleting all the google projects and agents.

**Comment by phuclm** [comment]
@apal21 I was created new project using new Google to meet time condition :(

**Comment by apal21** [comment]
@phuclm  I can understand and Google should improve this. We cannot do anything.

**Comment by AshwiniBS** [comment]
I exported the data first and deleted the Dialogflow agent. And again created new one with the same name and imported the data. Everything works now. Hope it helps

**Comment by niranjan-infofaces1** [comment]
hi am also  face the same error right now.
![2](https://user-images.githubusercontent.com/36408162/36148109-d1a05d5a-10e0-11e8-94ac-3a8f63dbe864.png)

**Comment by warhost** [comment]
I am also facing the same issue.

Overall I have to say, developing for Alexa is so much easier than the mess that is Dialogflow, Actions SDK and the Assistant Console. Too many settings spread over too many different services, after 1,5 days I still don't know what the best setup might be for an Action I already have on Alexa. It's ridicolously confusing and not pleasing to work with.

**Comment by dearlk** [comment]
You might want to provide your feedback at their google plus community. 

I second your feelings by the way

**Comment by arnabsen** [comment]
Sometimes the Intents -> Response -> Google Assistant tab -> Use response from the DEFAULT tab as the first response gets unselected, so I resolved this error after re-enabling that.

**Comment by loretoparisi** [comment]
@chilno we are facing the same issue, and we use v2, and we can see that the DialogFlow **Client Access Token** i.e. the one defined in the Dialogflow dashboard differs from the one we can see from the API Response in the simulator i.e. the field _accessToken_ in the json response.
Is that correct?

**Comment by warhost** [comment]
@loretoparisi Try relinking the Dialogflow Agent with the Actions Simulator: Go to Integrations > Google Action > Settings > Test.

**Comment by loretoparisi** [comment]
I have furtherly debugged and I get internally this error: `Failed to parse the dialog flow response into AppResponse because of empty speech response`

**Comment by davidalbertonogueira** [comment]
Agreed, @warhost.

**Comment by loretoparisi** [comment]
@davidalbertonogueira take a look at the referenced issue...the problem seems to be elsewhere.

**Comment by davidalbertonogueira** [comment]
I already fixed my problem. I was using a python library and I would get this error message when using their "card". Now I'm sending just the speech text and it works.

**Comment by SiddAjmera** [comment]
@loretoparisi like you said, that's what's happening. But if we return a promise from it, a response get's sent out. Now initially I tried with a simple text response and it worked for me on the simulator.

But it's giving me this error when I'm trying to send out a custom response as `Payload`.

![image](https://user-images.githubusercontent.com/5053266/40449804-48aee39e-5ef7-11e8-8a37-6dd7c5fecdce.png)

@matthewayne , please help!

**Comment by wangkekekexili** [comment]
This issue happened to me today. I fixed it by adding "Google Assistant Welcome" to the "Default Welcome Intent" Events section.

**Comment by vaibhavkumar049** [comment]
I am facing same problem ,My welcome intent is working fine , but when I invoke my action its not working , It is deployed in firebase but when I test it on simulator . Its showing MalformedResponse 'final_response' must be set. I am giving you code (inedex.js). Please riview it.`'use strict'

const {dialogflow}=require('actions-on-google');
const functions = require('firebase-functions');
const d=require('date-and-time');
const app=dialogflow({debug : true });
let date = new Date();


app.intent('what should',(conv,{Work})=>{
  console.log(Work);
  if(Work === 'do'){
 if(d.format(date,'ddd')==='Mon' && d.format(date,'hh:mm')==='09:00'){
   conv.close("You have a class of Microprocessor in ICT 308 ,You can go a bit late.");
 }
 if(d.format(date,'ddd')==='Thu' && d.format(date,'hh:mm')==='09:00'){
   conv.close("You have a class of Microprocessor in ICT 308 ,You can go a bit late.");
 }
 else {
   conv.close("You should be sleeping now");

 }
}
 else{
   conv.close("i could not understood");
 }

// conv.close('good night');

});

exports.dialogflowFirebaseFulfillment = functions.https.onRequest(app);

//if (d.getDay()








// // Create and Deploy Your First Cloud Functions
// // https://firebase.google.com/docs/functions/write-firebase-functions
//
// exports.helloWorld = functions.https.onRequest((request, response) => {
//  response.send("Hello from Firebase!");
// });
`

**Comment by dariuxmx** [comment]
Try to update your draft in simulator.

**Comment by elyutrading** [comment]
dialogflaw

**Comment by irvingDevMobi** [comment]
For me, the solution was to set a name and use it instead of "my test app"
<img width="530" alt="image" src="https://user-images.githubusercontent.com/6054625/164953851-516a75e0-e7af-47d1-a369-e427f4134aed.png">
