### ISSUE TITLE
When will you add support for DFv2?

### ISSUE THREAD

**Issue by dima1034** [actions-on-google/actions-on-google-nodejs#80]

**Comment by ditomaximal** [comment]
This would be great. Is there a way to contribute?

**Comment by yardensk** [comment]
+1

**Comment by moshekr** [comment]
+1

**Comment by sk-eran** [comment]
+1

**Comment by sk-eran** [comment]
Does anyone know of a different project that does that?

**Comment by Canain** [comment]
The [v2 of the client library](https://medium.com/@silvano.luciani/actions-on-google-client-library-for-node-js-v2-0-0-alpha-c92361167f15) (currently in alpha) now supports Dialogflow v2.

Give it a shot and let us know of any feedback so we can polish it during alpha!

**Comment by Canain** [comment]
Closing this now that v2 is in general availability.
