### ISSUE TITLE
Support for chat integrations via "data" field in response

### ISSUE THREAD

**Issue by CodingDoug** [actions-on-google/actions-on-google-nodejs#86]
I'm putting together a fulfillment hook using the node API to act as a Slack bot.  The hook works fine in the Dialogflow tester, but it doesn't work with Slack integration.  I discovered that responses need to contain a special object for third party integrations:

https://dialogflow.com/docs/fulfillment#response

> Note: To send formatted messages to bots, use the following format for the data field:
>     ```"data": {"slack": {<slack_message>}}```

Unfortunately, I don't see a documented way to do this.  Digging around in the source, I discovered that I could call some private APIs to get this done, in lieu of `tell()`:

```
const text = "..."
const res = app.buildResponse_(text, false)
res.data.slack = { speech: text }
app.doResponse_(res, 200)
```

This works fine, but I'd obviously rather not call private APIs.  Would love to see proper support for setting free-form values in the `data` field in the response.

**Comment by smishra2** [comment]
This feature is out of scope for this library, as the library is mainly a solution for Actions on Google developers who may or may not be using Dialogflow. From that point of view, we have all the necessary conveniences for setting values in the `data` field.

However the fix you have here should work well for most of the related cases.

**Comment by matthewayne** [comment]
Dialogflow has released a fulfillment library you might be interested in: 

- https://github.com/dialogflow/dialogflow-fulfillment-nodejs
- https://npmjs.org/package/dialogflow-fulfillment
