### ISSUE TITLE
Overwrites DEBUG env var in utils/transform.js

### ISSUE THREAD

**Issue by teddis** [actions-on-google/actions-on-google-nodejs#87]
I spent 30 minutes chasing down why the DEBUG environment variable wasn't working to this package. Line 20 of utils/transform.js overwrites it. Please fix this immediately.

20: process.env.DEBUG = 'actions-on-google:*';

Who wrote this code?

**Comment by Canain** [comment]
Are you sure you are using the latest version of the client library?

The latest released version (1.7.0) does not have this code:
https://github.com/actions-on-google/actions-on-google-nodejs/blob/96c3ff937322b9b855e688e84d6cc0dc17deaf85/utils/transform.js#L20

Try updating it with `npm install actions-on-google@1.7.0`

**Comment by teddis** [comment]
Ah, thank you, I was still on 1.6.0.
