### ISSUE TITLE
Need to update ActionsSdkApp.isRequestFromGoogle ?

### ISSUE THREAD

**Issue by marcelobern** [actions-on-google/actions-on-google-nodejs#92]
In the last few days I started getting an error: "This method accepts an options object as the first parameter, which includes the idToken, audience, and maxExpiry."

This seems to be coming from "google-auth-library" new signature for verifyIdToken which now accepts an options object (https://github.com/google/google-auth-library-nodejs/pull/223), so 

https://github.com/actions-on-google/actions-on-google-nodejs/blob/26548b64806fd62a703d8e37d7727bb3bc56dd0f/actions-sdk-app.js#L161

would have to wrap jwtToken, projectId within an object, something like:

`googleAuthClient.verifyIdToken({
  idToken: jwtToken,
  audience: projectId
}, (err, login) => {`

Not sure on the _audience: projectId_ bit, though.

Thoughts?

**Comment by Fleker** [comment]
Off the top of my head, my guess is that the `projectId` would be the Google Cloud Project identifier for your project.

**Comment by marcelobern** [comment]
@Fleker yes, you are correct about the projectId.

The bit where I am unclear is if the projectId would be correct value to use as the audience for verifyIdToken.

I checked earlier code (https://github.com/google/google-auth-library-nodejs/commit/e74d66fc40e3fe9191d93a3bd9f0c46a205c8464#diff-649059573aff44b9518de20ec91a3f1a) and that seems to be the case.

**Comment by smishra2** [comment]
Turns out this is from PR #78. I'll work on the fix and submit a patch.

**Comment by marcelobern** [comment]
Great, thanks!
