### ISSUE TITLE
MalformedResponse 'final_response' must be set.

### ISSUE THREAD

**Issue by niranjan-infofaces1** [actions-on-google/actions-on-google-nodejs#97]
Hi when i tried to test my app on action simulator i face this error
**"MalformedResponse 'final_response' must be set."** . help me to solve this error.
Here's the debug info i got.
```
{
  "audioResponse": "//NExAAQMQ...",
  "conversationToken": "GidzaW11bG...",
  "debugInfo": {
    "agentToAssistantDebug": {
      "agentToAssistantJson": "{}"
    },
    "assistantToAgentDebug": {
      "assistantToAgentJson": "{\"user\":{\"userId\":\"ABwppHG7Kyq6lQuC4UQhVkNFxGJ3HlCPVLe03G5Jo9UUsXcg41z8LL0ppX3pIv36nDLcvJD8YNxQexCrqoywTg\",\"locale\":\"en-US\",\"lastSeen\":\"2018-02-13T11:38:02Z\",\"userStorage\":\"{\\\"data\\\":{}}\"},\"conversation\":{\"conversationId\":\"1518522266082\",\"type\":\"NEW\"},\"inputs\":[{\"intent\":\"actions.intent.MAIN\",\"rawInputs\":[{\"inputType\":\"KEYBOARD\",\"query\":\"Talk to my test app\"}]}],\"surface\":{\"capabilities\":[{\"name\":\"actions.capability.MEDIA_RESPONSE_AUDIO\"},{\"name\":\"actions.capability.SCREEN_OUTPUT\"},{\"name\":\"actions.capability.AUDIO_OUTPUT\"},{\"name\":\"actions.capability.WEB_BROWSER\"}]},\"isInSandbox\":true,\"availableSurfaces\":[{\"capabilities\":[{\"name\":\"actions.capability.SCREEN_OUTPUT\"},{\"name\":\"actions.capability.AUDIO_OUTPUT\"}]}]}",
      "curlCommand": "curl -v 'https://api.api.ai/api/integrations/google?token=e4092e2db85b4744be7d736861988a51' -H 'Content-Type: application/json;charset=UTF-8' -H 'Google-Actions-API-Version: 2' -H 'Authorization: eyJhbGciOiJSUzI1NiIsImtpZCI6ImUyNzY3MWQ3M2EyNjA1Y2NkNDU0NDEzYzRjOTRlMjViM2Y2NmNkZWEifQ.eyJhdWQiOiJyZXN0YXVyYW50LTRhYzMzIiwiYXpwIjoiMzk3NjQzMDYwNTkyLWlydW9ubHFzZ2cyZm81cnM1OXIwcGpkYTBxMjVsZjZsLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiZXhwIjoxNTE4NTIyMzg2LCJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJqdGkiOiJkMGQ4NjgwOWQ2MjQ1ZDhkY2MxN2Y1MDM0ZjkzOGMyZDkxNWNjNzA3IiwiaWF0IjoxNTE4NTIyMjY2LCJuYmYiOjE1MTg1MjE5NjZ9.DVEBelXmrohLzFiy5IYamMSYS543rY19qVORlLhTxInTwLI_-gqXMzAsTBiiC3y9mJI073EzOmiiN-KUHtxbAYonVp0sZFuaw8YJpYckrnsuGtt1MGNt4DETThuOPPXCa-JAabcr-OTEjrcYTuBqTvpR4pUIxjCg08phF8F03I9-btNI9erR990JFSwGYj2RAC4yVIK07uANdom6jPnumY79la-f0LFvGgMC9ZMj5aGIIqnqcJAZqm005NrLni-zJBaymhVNguGyFaTWRlAuFQ1YQMwHWq3_sAEgeTKNI0JhQ4-8FI6VsCtfz2jvs9ZZeBfH8UeG9FcPfuJ2uCgbuw'  -A 'Mozilla/5.0 (compatible; Google-Cloud-Functions/2.1; +http://www.google.com/bot.html)' -X POST -d '{\"user\":{\"userId\":\"ABwppHG7Kyq6lQuC4UQhVkNFxGJ3HlCPVLe03G5Jo9UUsXcg41z8LL0ppX3pIv36nDLcvJD8YNxQexCrqoywTg\",\"locale\":\"en-US\",\"lastSeen\":\"2018-02-13T11:38:02Z\",\"userStorage\":\"{\\\"data\\\":{}}\"},\"conversation\":{\"conversationId\":\"1518522266082\",\"type\":\"NEW\"},\"inputs\":[{\"intent\":\"actions.intent.MAIN\",\"rawInputs\":[{\"inputType\":\"KEYBOARD\",\"query\":\"Talk to my test app\"}]}],\"surface\":{\"capabilities\":[{\"name\":\"actions.capability.MEDIA_RESPONSE_AUDIO\"},{\"name\":\"actions.capability.SCREEN_OUTPUT\"},{\"name\":\"actions.capability.AUDIO_OUTPUT\"},{\"name\":\"actions.capability.WEB_BROWSER\"}]},\"isInSandbox\":true,\"availableSurfaces\":[{\"capabilities\":[{\"name\":\"actions.capability.SCREEN_OUTPUT\"},{\"name\":\"actions.capability.AUDIO_OUTPUT\"}]}]}'"
    },
    "sharedDebugInfo": [
      {
        "name": "ResponseValidation",
        "subDebugEntry": [
          {
            "debugInfo": "'final_response' must be set.",
            "name": "MalformedResponse"
          }
        ]
      }
    ]
  },
  "response": "My test app isn't responding right now. Try again soon.",
  "visualResponse": {
    "visualElements": []
  }
}
```
![2](https://user-images.githubusercontent.com/36408162/36148244-45ec71bc-10e1-11e8-91ff-de1f18cb7742.png)

**Comment by Fleker** [comment]
What exactly is your webhook doing? This question may be suited better for [StackOverflow](https://stackoverflow.com/questions/tagged/actions-on-google) as it's not related to the library directly.

**Comment by loretoparisi** [comment]
@Fleker We are facing the same issue, and there is no solution for that neither on SF or this issues threads like https://github.com/actions-on-google/actions-on-google-nodejs/issues/79

**Comment by sureshvv** [comment]
I have this exact same problem using the sample "Favorite Color" tutorial after following all the instructions

**Comment by igilham** [comment]
Looks like your app hasn't returned anything in the response:

```json
  "agentToAssistantDebug": {
      "agentToAssistantJson": "{}"
    },
```

**Comment by vaibhavkumar049** [comment]
facing same problem ,even after explicitly giving output
`'use strict'

const {dialogflow}=require('actions-on-google');
const functions = require('firebase-functions');
const d=require('date-and-time');
const app=dialogflow({debug : true });
let date = new Date();


app.intent('what should',(conv,{Work})=>{
  console.log(Work);
  //if(Work ==== 'do'){
 if(d.format(date,'ddd')==='Mon' && d.format(date,'hh:mm')==='09:00'){
   conv.close("You have a class of Microprocessor in ICT 308 ,You can go a bit late.");
 }
 if(d.format(date,'ddd')==='Thu' && d.format(date,'hh:mm')==='09:00'){
   conv.close("You have a class of Microprocessor in ICT 308 ,You can go a bit late.");
 }
 else {
   conv.close("You should be sleeping now");

 }
// }
//  else{
//    conv.close("i could not understood");
//  }

conv.close('good night');

});

exports.dialogflowFirebaseFulfillment = functions.https.onRequest(app);`

**Comment by Steven-G-Jet** [comment]
You might want to check if there are spelling/case issues with your intent's name. For example, if you named your intent "Favorite color" (uppercase F) but wrote "app.intent('favorite color', (conv, {color})"(lower case F), this will also lead to the response error.

**Comment by Canain** [comment]
Usually this is a problem with the webhook not sending a response back or erroring out.

For debugging, you might want to set a default response in Dialogflow that says "An error happened with the webhook" so it says that when your webhook has a problem (it'll fallback to Dialogflow responses when webhook fails).

Check the logs and make sure the intent names match and a response has been sent. Also check that if you are doing async calls, you are returning a Promise that resolves when all your responses have been generated and `conv.ask`ed.
